# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Removal of what Hammunition itself installed.

D-004 and DESIGN.md §7 fix the promise: no rollback, a transaction log, and an
``uninstall`` that removes what Hammunition added and reports honestly on what
it cannot safely reverse.

## What "Hammunition installed it" means

Attribution replays the transaction log's events in order; the command's own
recorded outcome is the source of truth, not the surrounding transaction —
a run that died on command 3 of 5 still installed whatever command 2
installed, and reading only completed transactions would deny that. Four
attribution routes, each exact:

- **apt packages** — ``command_end`` for ``apt-get install``/``remove``
  exiting 0 attributes/un-attributes the packages after ``--``.
- **files under the prefix** — ``command_end`` for the engine's own
  ``install -D -m 0755 … <dest>`` attributes *dest*; a successful
  ``rm -f -- <dest>`` un-attributes it. Nothing else in ``/usr/local/bin``
  is ever touched: a same-named file the operator put there predates the
  log and stays.
- **vendor .debs** — the fetch cache names every artifact
  ``<sha256>-<filename>``, so the recorded install argv carries the
  manifest's own digest. A deb unit is attributed when its digest appears
  in a successful ``apt-get install`` and its declared ``deb_package`` has
  not been apt-removed since.
- **namespaced trees and venvs** — ``<prefix>/share/hammunition/<name>``
  and the per-user ``venvs/<name>`` can only be ours; existence is
  attribution.

Wrappers and desktop entries in the operator's home are removed only after
reading them back: the launcher wrapper's ``generated by hammunition`` line,
a venv wrapper's exec into our venv tree, a desktop entry's
``X-Hammunition-Package`` key. A same-named file without the marker is
reported and left.

## What is refused, by name

- A source or git unit whose build ran a real ``make install`` into the
  shared prefix: there is no file manifest to reverse, and pretending with
  a file sweep would be the shim CLAUDE.md forbids. The refusal names the
  unit and the gap (a staged, recorded install is the future fix).
- A package that is installed but was not installed by Hammunition: it was
  there before us (or arrived by another road), and removing it would exceed
  the promise. It is reported and left in place.

Shared dependencies that apt pulled in are left for ``apt autoremove``, and
the plan says so: removing them by name risks removing what another unit —
or the user's own work — still needs. Group memberships and written config
files are not yet reversed; the log records them, and the plan says that too.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal

from hammunition.manifest.schema import (
    AptInstall,
    BinaryInstall,
    GitInstall,
    PackageManifest,
    ProfileManifest,
    SourceInstall,
    VenvInstall,
)

if TYPE_CHECKING:
    from hammunition.backends.apt import AptPackageState
    from hammunition.distro import Target
    from hammunition.state.log import TransactionLog

__all__ = [
    "ArtifactRemoval",
    "RemovalError",
    "RemovalPaths",
    "RemovalPlan",
    "deb_attributed",
    "files_installed_by_hammunition",
    "installed_by_hammunition",
    "plan_removal",
]


class RemovalError(Exception):
    """The removal could not be planned. The message carries every blocker."""


def installed_by_hammunition(log: TransactionLog) -> frozenset[str]:
    """Every apt package the log shows this engine installed and not removed.

    Replayed chronologically from ``command_end`` events with returncode 0.
    Unknown events are ignored, per the log's own reader contract.
    """
    attributed: set[str] = set()
    for entry in log.read():
        if entry.get("event") != "command_end" or entry.get("returncode") != 0:
            continue
        packages = _packages_after_dashes(entry.get("argv"))
        if packages is None:
            continue
        verb = entry["argv"][1]
        if verb == "install":
            attributed.update(packages)
        elif verb == "remove":
            attributed.difference_update(packages)
    return frozenset(attributed)


def _packages_after_dashes(argv: Any) -> list[str] | None:
    """The package arguments of an ``apt-get install``/``remove`` argv, else None."""
    if not isinstance(argv, list) or len(argv) < 2 or argv[0] != "apt-get":
        return None
    if argv[1] not in ("install", "remove"):
        return None
    if "--" not in argv:
        return None
    return [str(p) for p in argv[argv.index("--") + 1 :]]


def files_installed_by_hammunition(log: TransactionLog) -> frozenset[str]:
    """Every prefix file the log shows this engine installed and not removed.

    The engine's own binary-install command is ``install -D -m 0755 <src>
    <dest>`` (:func:`~hammunition.backends.source.install_binary_commands`);
    a successful one attributes *dest*. Its own removal command is
    ``rm -f -- <dest>``; a successful one un-attributes it. Everything else
    — including the operator's own ``install`` runs, which are not in this
    log — is invisible here, which is the point.
    """
    attributed: set[str] = set()
    for entry in log.read():
        event = entry.get("event")
        if event == "action_end" and entry.get("kind") == "install-binary":
            # The executable format installs in-process; its action_end
            # carries the destination as its detail (older logs carry no
            # detail field, and those installs stay unattributed — reported
            # and left in place rather than guessed at).
            detail = entry.get("detail")
            if isinstance(detail, str) and detail.startswith("/"):
                attributed.add(detail)
            continue
        if event != "command_end" or entry.get("returncode") != 0:
            continue
        argv = entry.get("argv")
        if not isinstance(argv, list) or not argv:
            continue
        if argv[:4] == ["install", "-D", "-m", "0755"] and len(argv) == 6:
            attributed.add(str(argv[5]))
        elif argv[:2] == ["rm", "-f"] and "--" in argv:
            attributed.difference_update(str(p) for p in argv[argv.index("--") + 1 :])
    return frozenset(attributed)


def deb_attributed(log: TransactionLog, *, sha256: str, deb_package: str) -> bool:
    """Whether a vendor .deb with this digest is currently ours to remove.

    The fetch cache names artifacts ``<sha256>-<filename>``, so the record of
    the install carries the manifest's digest. The install itself runs inside
    the backend's ``install-deb`` Action — its apt-get never appears as a
    ``command_end`` of its own — so the digest is read from that action's
    recorded outcome (``installed <sha256>-<file> through apt``, the
    backend's own single-writer string). Replayed in order: the digest's
    install attributes it, a later successful ``apt-get remove`` naming
    *deb_package* un-attributes it. An operator's own reinstall of the
    distribution package is invisible to this log and changes nothing here —
    ``plan_removal`` still checks what is installed *now* before acting.
    """
    attributed = False
    for entry in log.read():
        event = entry.get("event")
        if event == "action_end" and entry.get("kind") == "install-deb":
            outcome = entry.get("outcome")
            if isinstance(outcome, str) and f"installed {sha256}-" in outcome:
                attributed = True
            continue
        if event != "command_end" or entry.get("returncode") != 0:
            continue
        packages = _packages_after_dashes(entry.get("argv"))
        if packages is None:
            continue
        verb = entry["argv"][1]
        if verb == "install" and any(
            Path(str(p)).name.startswith(f"{sha256}-") for p in packages
        ):
            attributed = True
        elif verb == "remove" and deb_package in packages:
            attributed = False
    return attributed


@dataclass(frozen=True)
class ArtifactRemoval:
    """One non-apt artifact an uninstall will remove, and on what authority.

    ``basis`` is printed beside the path so the operator sees *why* the
    engine believes this is its own work: ``namespaced`` (the path lives
    under a hammunition-owned directory), ``log`` (the transaction log
    attributes its installation), or ``marker`` (the file will be read back
    and removed only if it carries the engine's generated marker).
    """

    kind: Literal["venv", "tree", "binary", "wrapper", "desktop-entry"]
    path: Path
    basis: Literal["namespaced", "log", "marker"]
    requires_root: bool = False


@dataclass(frozen=True)
class RemovalPaths:
    """Where this machine's non-apt artifacts live, from :mod:`~hammunition.paths`."""

    prefix: Path
    venv_root: Path
    bin_dir: Path
    applications_dir: Path


@dataclass(frozen=True)
class RemovalPlan:
    """What an uninstall will do, and everything it deliberately will not."""

    to_remove: dict[str, list[str]]
    """Unit name -> the apt packages that will be removed for it."""

    left_foreign: dict[str, list[str]]
    """Unit name -> installed packages left in place: not installed by us."""

    already_absent: dict[str, list[str]]
    """Unit name -> attributed packages that are already not installed."""

    artifacts: dict[str, list[ArtifactRemoval]] = field(default_factory=dict)
    """Unit name -> non-apt artifacts (venvs, trees, binaries, launchers)."""

    left_unattributed: dict[str, list[str]] = field(default_factory=dict)
    """Unit name -> present prefix files left in place: the log does not
    attribute them, so they predate us or arrived by another road."""

    apt_packages: tuple[str, ...] = field(init=False)
    """The flat, sorted set the single ``apt-get remove`` will name."""

    def __post_init__(self) -> None:
        flat = sorted({p for packages in self.to_remove.values() for p in packages})
        object.__setattr__(self, "apt_packages", tuple(flat))


def plan_removal(
    names: list[str],
    *,
    catalog: dict[str, PackageManifest],
    profiles: dict[str, ProfileManifest],
    target: Target,
    attributed: frozenset[str],
    states: dict[str, AptPackageState],
    paths: RemovalPaths,
    attributed_files: frozenset[str] = frozenset(),
    log: TransactionLog | None = None,
) -> RemovalPlan:
    """Resolve names to a removal plan, or raise with every blocker at once.

    ``states`` is the current apt view of every package the plan touches
    (from ``AptBackend.probe``) — what is installed *now*, not what the log
    said at install time. ``attributed_files`` is
    :func:`files_installed_by_hammunition` over the same log; ``log`` itself
    is only consulted for vendor-.deb digest attribution.
    """
    blockers: list[str] = []
    units: list[str] = []
    for name in names:
        if name in profiles:
            units.extend(profiles[name].packages)
        elif name in catalog:
            units.append(name)
        else:
            blockers.append(f"{name}: not a package or profile in this catalog")

    to_remove: dict[str, list[str]] = {}
    left_foreign: dict[str, list[str]] = {}
    already_absent: dict[str, list[str]] = {}
    artifacts: dict[str, list[ArtifactRemoval]] = {}
    left_unattributed: dict[str, list[str]] = {}

    def add(unit: str, removal: ArtifactRemoval) -> None:
        if removal.path.exists() or removal.path.is_symlink():
            artifacts.setdefault(unit, []).append(removal)

    def plan_binaries(unit: str, manifest: PackageManifest) -> None:
        """Prefix binaries the engine copied — removable only on log evidence."""
        for binary in manifest.binaries:
            dest = paths.prefix / "bin" / binary.install_as
            if str(dest) in attributed_files:
                add(unit, ArtifactRemoval("binary", dest, "log", requires_root=True))
            elif dest.exists():
                left_unattributed.setdefault(unit, []).append(str(dest))

    for unit in dict.fromkeys(units):  # preserve order, drop duplicates
        manifest = catalog[unit]
        block = manifest.resolve(target.distro, target.version, target.arch)
        if block is None:
            # Nothing installable here means nothing to remove here; if the
            # log attributed packages under another distro, that machine's
            # log is not this machine's.
            already_absent[unit] = []
            continue
        install = block.install

        if isinstance(install, AptInstall):
            for package in install.packages:
                state = states.get(package)
                currently = state is not None and state.is_installed
                if package in attributed and currently:
                    to_remove.setdefault(unit, []).append(package)
                elif currently:
                    left_foreign.setdefault(unit, []).append(package)
                else:
                    already_absent.setdefault(unit, []).append(package)

        elif isinstance(install, VenvInstall):
            add(
                unit,
                ArtifactRemoval("venv", paths.venv_root / manifest.name, "namespaced"),
            )
            # The backend stages the hash-pinned requirements file beside the
            # venv; it is namespaced the same way and leaves with it.
            add(
                unit,
                ArtifactRemoval(
                    "venv",
                    paths.venv_root / f"{manifest.name}.requirements.txt",
                    "namespaced",
                ),
            )
            for script in install.expose:
                add(unit, ArtifactRemoval("wrapper", paths.bin_dir / script, "marker"))

        elif isinstance(install, BinaryInstall):
            if install.format == "deb":
                deb_pkg = install.deb_package
                assert deb_pkg is not None  # schema validator guarantees it
                state = states.get(deb_pkg)
                currently = state is not None and state.is_installed
                ours = log is not None and deb_attributed(
                    log, sha256=install.artifact.sha256, deb_package=deb_pkg
                )
                if currently and ours:
                    to_remove.setdefault(unit, []).append(deb_pkg)
                elif currently:
                    left_foreign.setdefault(unit, []).append(deb_pkg)
                else:
                    already_absent.setdefault(unit, []).append(deb_pkg)
            else:
                plan_binaries(unit, manifest)
                if install.install_tree:
                    add(
                        unit,
                        ArtifactRemoval(
                            "tree",
                            paths.prefix / "share" / "hammunition" / manifest.name,
                            "namespaced",
                            requires_root=True,
                        ),
                    )

        elif isinstance(install, SourceInstall | GitInstall):
            reversible = not install.provides_install_target or install.install_tree
            if not reversible:
                blockers.append(
                    f"{unit}: built from {install.method} with a real `make "
                    f"install` into {paths.prefix}, which leaves no file "
                    f"manifest to reverse — a staged, recorded install is the "
                    f"planned fix. What it wrote is in the transaction log"
                )
                continue
            if not install.provides_install_target:
                plan_binaries(unit, manifest)
            if install.install_tree:
                add(
                    unit,
                    ArtifactRemoval(
                        "tree",
                        paths.prefix / "share" / "hammunition" / manifest.name,
                        "namespaced",
                        requires_root=True,
                    ),
                )
        else:
            blockers.append(
                f"{unit}: installed via the {install.method} backend, and "
                f"uninstall for {install.method} is not implemented — what "
                f"it wrote is in the transaction log"
            )
            continue

        for launcher in manifest.launchers:
            add(unit, ArtifactRemoval("wrapper", paths.bin_dir / launcher.name, "marker"))
            add(
                unit,
                ArtifactRemoval(
                    "desktop-entry",
                    paths.applications_dir / f"hammunition-{launcher.name}.desktop",
                    "marker",
                ),
            )

    if blockers:
        raise RemovalError(
            "this removal cannot be planned:\n  " + "\n  ".join(sorted(blockers))
        )
    return RemovalPlan(
        to_remove=to_remove,
        left_foreign=left_foreign,
        already_absent=already_absent,
        artifacts=artifacts,
        left_unattributed=left_unattributed,
    )
