# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""CoMaps' map files: the index, the generated pins, the station's regions.  D-069.

CoMaps publishes its maps as one ``.mwm`` file per country or part of one, at
``https://cdn-fi-1.comaps.app/maps/<series>/<version>/<id>.mwm``. What each
file should be is in the app's own ``data/countries.txt``: a tree of groups
whose leaves carry the file's size (``s``) and a base64 SHA-1
(``sha1_base64``). There is no signature and no sha256 anywhere. So the check
for a map is the one the publisher gives, the SHA-1 from the index at the
commit the ``comaps`` unit builds, plus the exact size -- CoMaps' mirrors
answer a missing file with ``200`` and an HTML page, so a status proves
nothing. The plan says which check it is, on every map line.

``catalog/data/comaps-pins.yaml`` is generated from that index by
``scripts/gen_comaps_pins.py``: every map in the world, so the file says
nothing about which region anybody cares about, and a table from Geofabrik's
region paths -- what ``station set --map-regions`` takes -- to CoMaps' map ids.
The table is made by a rule and a two-line alias list, never by hand (see
:func:`region_table`); a region the rule cannot place is not in it, and the
plan names it rather than guessing.

The version is a date (``260830`` is 2026-08-30). CoMaps' CDN keeps a version
for months, not forever: the pins expire, and ``update --upstream`` says so.
"""

from __future__ import annotations

import base64
import binascii
import re
import urllib.error
import urllib.request
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import quote

import yaml

CDN = "https://cdn-fi-1.comaps.app/maps"
PINS_FILE = Path("data") / "comaps-pins.yaml"
GENERATED_MARK = "GENERATED by scripts/gen_comaps_pins.py"
REGENERATE = (
    "regenerate them with scripts/gen_comaps_pins.py against the commit "
    "catalog/packages/comaps.yaml pins"
)
#: How the plan and the step name the check, every time (D-057's rule that a
#: weaker check is disclosed, never silent).
VERIFIED_BY = (
    "SHA-1 and size from CoMaps' own map index at the pinned commit (the publisher's check)"
)

#: Geofabrik paths the rule in :func:`region_table` cannot place, each
#: reviewed: Geofabrik's ``us`` is CoMaps' "United States of America", and
#: CoMaps files the District of Columbia with Maryland's southern map.
ALIASES: Mapping[str, str] = {
    "north-america/us": "United States of America",
    "north-america/us/district-of-columbia": "US_Maryland_and_DC",
}


class ComapsError(Exception):
    """A CoMaps index, pin file or map that cannot be used, named."""


@dataclass(frozen=True)
class MapPin:
    id: str
    size: int
    sha1: str
    """Base64, as the index writes it."""


@dataclass(frozen=True)
class ComapsPins:
    commit: str
    version: int
    series: str
    maps: Mapping[str, MapPin]
    regions: Mapping[str, tuple[str, ...]]


@dataclass(frozen=True)
class MapFile:
    """One map to fetch: its pin and where it is published."""

    pin: MapPin
    url: str
    version: int

    @property
    def id(self) -> str:
        return self.pin.id

    @property
    def file(self) -> str:
        return f"{self.pin.id}.mwm"


def sha1_hex(value: str) -> str:
    """The index's base64 SHA-1 as hex; refused unless it is 20 bytes."""
    try:
        raw = base64.b64decode(value, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise ComapsError(f"{value!r} is not base64") from exc
    if len(raw) != 20:
        raise ComapsError(f"{value!r} is {len(raw)} bytes, not a 20-byte SHA-1")
    return raw.hex()


def check_map_id(name: str) -> str:
    """*name*, refused unless it can be one path component: it becomes a file
    under the installed data directory and a link name in the operator's
    CoMaps directory."""
    if (
        not name
        or name.startswith(".")
        or any(c in name for c in ("/", "\\", "\0"))
        or any(ord(c) < 32 for c in name)
    ):
        raise ComapsError(f"map id {name!r} cannot be a file name; refusing the index")
    return name


def version_date(version: int) -> date:
    """``260830`` -> 2026-08-30: CoMaps names a map version by its date."""
    text = f"{version:06d}"
    try:
        return date(2000 + int(text[:2]), int(text[2:4]), int(text[4:6]))
    except ValueError as exc:
        raise ComapsError(f"map version {version} is not a YYMMDD date") from exc


def flatten(index: Mapping[str, Any]) -> dict[str, MapPin]:
    """Every leaf of the index -- a node with no ``g`` -- as a pin."""
    maps: dict[str, MapPin] = {}

    def walk(node: Mapping[str, Any]) -> None:
        children = node.get("g")
        if children is None:
            name = str(node.get("id", ""))
            size = node.get("s")
            sha1 = node.get("sha1_base64")
            if not name or not isinstance(size, int) or size <= 0 or not isinstance(sha1, str):
                raise ComapsError(f"index leaf {name or node!r} has no usable size or SHA-1")
            check_map_id(name)
            sha1_hex(sha1)
            pin = MapPin(name, size, sha1)
            # One file may be listed under two groups (Crimea, Jerusalem and
            # Campo de Hielo Sur are, at 72632e4): the same map, kept once.
            # Two different files under one name are refused.
            if name in maps and maps[name] != pin:
                raise ComapsError(f"index names two different maps {name!r}")
            maps[name] = pin
            return
        for child in children:
            walk(child)

    for child in index.get("g") or ():
        walk(child)
    if not maps:
        raise ComapsError("the index has no maps")
    return maps


def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9]", "", text.lower())


def _leaves(node: Mapping[str, Any]) -> tuple[str, ...]:
    if "g" not in node:
        return (str(node["id"]),)
    return tuple(leaf for child in node["g"] for leaf in _leaves(child))


def _find(node: Mapping[str, Any], wanted: str) -> Mapping[str, Any] | None:
    if node.get("id") == wanted:
        return node
    for child in node.get("g") or ():
        found = _find(child, wanted)
        if found is not None:
            return found
    return None


def _match(children: Iterable[Mapping[str, Any]], name: str) -> Mapping[str, Any] | None:
    """The one child whose id, or whose id after its first ``_``, is *name*
    once case and punctuation are dropped. Two matches match nothing."""
    wanted = _norm(name)
    hits = []
    for child in children:
        cid = str(child.get("id", ""))
        spellings = {_norm(cid)}
        if "_" in cid:
            spellings.add(_norm(cid.split("_", 1)[1]))
        if wanted in spellings:
            hits.append(child)
    return hits[0] if len(hits) == 1 else None


def region_table(index: Mapping[str, Any], regions: Iterable[str]) -> dict[str, tuple[str, ...]]:
    """Geofabrik region path -> the CoMaps maps that cover it, sorted.

    The rule: an alias from :data:`ALIASES`; else, when the region's parent is
    in the table, the one child of the parent's CoMaps node that the region's
    last path component names; else, for a continent's child, the one
    top-level node it names. A group's leaves are all its maps. Nothing else:
    a region CoMaps spells differently (Geofabrik's ``bayern``, CoMaps'
    "Free State of Bavaria") is left out, and the plan names it.
    """
    nodes: dict[str, Mapping[str, Any]] = {}
    table: dict[str, tuple[str, ...]] = {}
    for region in sorted(set(regions), key=lambda r: (r.count("/"), r)):
        parts = region.split("/")
        node: Mapping[str, Any] | None = None
        if region in ALIASES:
            node = _find(index, ALIASES[region])
        elif "/".join(parts[:-1]) in nodes:
            node = _match(nodes["/".join(parts[:-1])].get("g") or (), parts[-1])
        elif len(parts) <= 2:
            node = _match(index.get("g") or (), parts[-1])
        if node is None:
            continue
        nodes[region] = node
        table[region] = tuple(sorted(_leaves(node)))
    return table


def parse_pins(text: str, *, known_regions: Iterable[str] | None = None) -> ComapsPins:
    """The pin file, refused by name when it is not what the generator writes."""
    if GENERATED_MARK not in text:
        raise ComapsError("the pin file does not carry the generated-by line")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise ComapsError(f"not YAML: {exc}") from exc
    if not isinstance(data, dict):
        raise ComapsError("not a mapping")
    commit = str(data.get("commit", ""))
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        raise ComapsError(f"commit {commit!r} is not 40 hex characters")
    version = data.get("version")
    if not isinstance(version, int):
        raise ComapsError("version is not a number")
    version_date(version)
    series = str(data.get("map_series", ""))
    if not re.fullmatch(r"\d{4}\.\d{2}\.\d{2}", series):
        raise ComapsError(f"map_series {series!r} is not YYYY.MM.DD")
    maps: dict[str, MapPin] = {}
    for name, row in (data.get("maps") or {}).items():
        size = row.get("size") if isinstance(row, dict) else None
        sha1 = row.get("sha1") if isinstance(row, dict) else None
        if not isinstance(size, int) or size <= 0:
            raise ComapsError(f"map {name!r}: size {size!r} is not a positive number")
        if not isinstance(sha1, str):
            raise ComapsError(f"map {name!r}: no sha1")
        sha1_hex(sha1)
        check_map_id(str(name))
        maps[str(name)] = MapPin(str(name), size, sha1)
    if not {"World", "WorldCoasts"} <= set(maps):
        raise ComapsError("the pins carry no World or WorldCoasts map")
    known = set(known_regions) if known_regions is not None else None
    regions: dict[str, tuple[str, ...]] = {}
    for region, ids in (data.get("regions") or {}).items():
        if known is not None and region not in known:
            raise ComapsError(f"{region!r} is not a region of the carried Geofabrik lists")
        missing = [i for i in ids or () if i not in maps]
        if not ids or missing:
            raise ComapsError(f"region {region!r} names maps with no pin: {missing or ids}")
        regions[str(region)] = tuple(str(i) for i in ids)
    return ComapsPins(commit, version, series, maps, regions)


def load_pins(catalog_root: Path) -> ComapsPins:
    """``<catalog>/data/comaps-pins.yaml``, parsed."""
    path = catalog_root / PINS_FILE
    try:
        return parse_pins(path.read_text())
    except OSError as exc:
        raise ComapsError(f"{path}: {exc.strerror or exc}; {REGENERATE}") from exc
    except ComapsError as exc:
        raise ComapsError(f"{path}: {exc}; {REGENERATE}") from exc


def map_url(pins: ComapsPins, map_id: str) -> str:
    return f"{CDN}/{pins.series}/{pins.version}/{quote(map_id + '.mwm')}"


def resolve_regions(regions: Sequence[str], pins: ComapsPins) -> tuple[list[MapFile], list[str]]:
    """The station's regions as maps, each once, in the order chosen; and the
    regions the table has no row for, named, which install nothing."""
    seen: dict[str, MapFile] = {}
    unmapped: list[str] = []
    for region in regions:
        ids = pins.regions.get(region)
        if ids is None:
            unmapped.append(region)
            continue
        for map_id in ids:
            if map_id not in seen:
                seen[map_id] = MapFile(pins.maps[map_id], map_url(pins, map_id), pins.version)
    return list(seen.values()), unmapped


class CdnProbe:
    """A ``HEAD`` to CoMaps' CDN: status and ``Content-Length``, nothing else.

    Built as :class:`hammunition.geofabrik.UrllibProbe` is: only the HTTP
    handlers, no redirects followed, no ``file:`` URL, and nothing outside
    :data:`CDN` asked. The answer is never trusted: the size must equal the
    pin, because a mirror answers a missing map with 200 and a web page.
    """

    def __init__(self, *, timeout: float = 30.0) -> None:
        self.timeout = timeout
        opener = urllib.request.OpenerDirector()
        opener.add_handler(urllib.request.HTTPHandler())
        opener.add_handler(urllib.request.HTTPSHandler())
        self._opener = opener

    def head(self, url: str) -> tuple[int, int]:
        if not url.startswith(CDN + "/"):
            raise ComapsError(f"refusing {url!r}: only {CDN} is asked about maps")
        request = urllib.request.Request(url, headers={"User-Agent": "hammunition"})
        request.method = "HEAD"
        try:
            response = self._opener.open(request, timeout=self.timeout)
        except (urllib.error.URLError, OSError) as exc:
            raise ComapsError(f"{url} could not be reached: {exc}") from exc
        if response is None:  # pragma: no cover - no handler claimed the scheme
            raise ComapsError(f"no handler would ask {url!r}")
        with response:
            length = response.headers.get("Content-Length")
            return response.status, int(length) if length and length.isdigit() else 0


def published(status: int, size: int, pin: MapPin) -> bool:
    """Whether a ``HEAD`` answer is the pinned file: 200 **and** its size."""
    return status == 200 and size == pin.size


def gone(status: int, size: int, pin: MapPin) -> bool:
    """Whether a ``HEAD`` answer says the pinned file is no longer published:
    404 or 410, or a 200 of another size (a mirror's web page for a missing
    map). Any other answer -- a 503, a 429, a redirect -- is a server that
    did not say, not an expired pin."""
    return status in (404, 410) or (status == 200 and size != pin.size)
