# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Kiwix books: the catalog's allow-list, its pins, and the station's choice.  D-065.

Three files meet here:

* ``catalog/data/kiwix-books.yaml``, **hand-written**: which books the catalog
  offers, and each one's licence line. It has to be hand-written because the
  ZIM does not say: of nine read on 2026-09-29, one carried a ``License``
  metadata entry. A book this list does not name has no known licence to
  print before the confirmation (D-049 rule 2), so choosing it is refused.
* ``catalog/data/kiwix-pins.yaml``, **generated** by
  ``scripts/gen_kiwix_pins.py`` from Kiwix's ``library_zim.xml`` and each
  book's ``.meta4``: the dated file, its exact size and its sha256. Nothing
  Kiwix publishes is signed; the pin freezes what TLS to download.kiwix.org
  delivered on the day it was generated.
* station config's ``reference_books``: the ids the operator chose.

A book's id is Kiwix's own file stem without the date: ``<name>_<flavour>``,
or the bare name for a book published in one flavour
(``ham.stackexchange.com_en_all``). The files are
``<id>_<YYYY-MM>.zim`` under ``https://download.kiwix.org/zim/<category>/``.

Kiwix keeps only the two newest dated files of a book, so a pin dies about
two publications after it is made. A pin that is gone is an error naming the
regeneration, never a quiet move to the newer file: the newer file has a hash
nobody here has measured.
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

__all__ = [
    "BOOK_ID",
    "DOWNLOAD",
    "GENERATED_MARK",
    "Book",
    "BookFile",
    "BookPin",
    "KiwixError",
    "current_file",
    "file_date",
    "load_book_list",
    "load_books",
    "load_pin_file",
    "load_pins",
    "parse_library",
    "parse_meta4",
    "resolve_books",
]

DOWNLOAD = "https://download.kiwix.org/zim"
GENERATED_MARK = "GENERATED by scripts/gen_kiwix_pins.py"
BOOK_ID = re.compile(r"[a-z0-9][a-z0-9._-]*")
_CATEGORY = re.compile(r"[a-z0-9][a-z0-9_-]*")
_SHA256 = re.compile(r"[0-9a-f]{64}")
_DATED = re.compile(r"(?P<id>.+)_(?P<date>\d{4}-\d{2})\.zim")
_METALINK = "{urn:ietf:params:xml:ns:metalink}"
_ATOM = "{http://www.w3.org/2005/Atom}"
LIST_REMEDY = "`hammunition reference books` lists the books the catalog offers"
PINS_REMEDY = "regenerate the pins with scripts/gen_kiwix_pins.py"


class KiwixError(ValueError):
    """A book list, a pin file or a selection that cannot be used as it stands."""


def _xml(text: str, what: str) -> ET.Element:
    """Parse a document from Kiwix, refusing any DTD before the parser sees it.

    The stdlib parser resolves no external entities, and expat caps entity
    expansion, but a library, ``.meta4`` or OPDS answer has no business
    declaring entities at all: one that does is refused, not parsed.
    """
    if re.search(r"<!(?:DOCTYPE|ENTITY)", text, re.IGNORECASE):
        raise KiwixError(f"the {what} declares a DTD or an entity; refused")
    try:
        return ET.fromstring(text)
    except ET.ParseError as exc:
        raise KiwixError(f"the {what} is not XML: {exc}") from exc


@dataclass(frozen=True)
class Book:
    """One entry of the allow-list."""

    id: str
    name: str
    flavour: str | None
    category: str
    title: str
    licence: str
    licence_url: str
    note: str | None = None


@dataclass(frozen=True)
class BookPin:
    """One generated pin: the dated file of a book, measured from its ``.meta4``."""

    id: str
    file: str
    url: str
    size: int
    sha256: str
    published: str
    measured: str


@dataclass(frozen=True)
class BookFile:
    """A chosen book with its pin: what the install fetches and discloses."""

    book: Book
    pin: BookPin


def file_date(file: str) -> str:
    """``ham.stackexchange.com_en_all_2026-08.zim`` -> ``2026-08``."""
    match = _DATED.fullmatch(file)
    if match is None:
        raise KiwixError(f"{file!r} is not a dated Kiwix file name (<id>_YYYY-MM.zim)")
    return match.group("date")


def _str(row: Mapping[str, Any], key: str, where: str) -> str:
    value = row.get(key)
    if not isinstance(value, str) or not value.strip():
        raise KiwixError(f"{where}: `{key}` is missing or empty")
    return value


def load_books(text: str) -> dict[str, Book]:
    """The allow-list, keyed by id in its own order. Refused whole when malformed."""
    data = yaml.safe_load(text) or {}
    rows = data.get("books") if isinstance(data, dict) else None
    if not isinstance(rows, list) or not rows:
        raise KiwixError("the book list has no `books:` entries")
    books: dict[str, Book] = {}
    for index, row in enumerate(rows):
        if not isinstance(row, dict):
            raise KiwixError(f"book entry {index} is not a mapping")
        where = f"book entry {index} ({row.get('id')!r})"
        known = {"id", "name", "flavour", "category", "title", "licence", "licence_url", "note"}
        unknown = sorted(set(row) - known)
        if unknown:
            raise KiwixError(f"{where}: unknown keys {', '.join(unknown)}")
        book_id = _str(row, "id", where)
        name = _str(row, "name", where)
        flavour = row.get("flavour")
        if flavour is not None and (not isinstance(flavour, str) or not BOOK_ID.fullmatch(flavour)):
            raise KiwixError(f"{where}: `flavour` must be a lowercase word or null")
        expected = f"{name}_{flavour}" if flavour else name
        if book_id != expected or not BOOK_ID.fullmatch(book_id):
            raise KiwixError(
                f"{where}: the id must be Kiwix's name_flavour ({expected!r}), the file "
                f"stem without its date"
            )
        category = _str(row, "category", where)
        if not _CATEGORY.fullmatch(category):
            raise KiwixError(f"{where}: `category` {category!r} is not a Kiwix directory name")
        licence_url = _str(row, "licence_url", where)
        if not licence_url.startswith("https://"):
            raise KiwixError(f"{where}: licence_url must be https, got {licence_url!r}")
        note = row.get("note")
        if book_id in books:
            raise KiwixError(f"{where}: the id {book_id!r} is listed twice")
        books[book_id] = Book(
            id=book_id,
            name=name,
            flavour=flavour,
            category=category,
            title=_str(row, "title", where),
            licence=_str(row, "licence", where),
            licence_url=licence_url,
            note=str(note).strip() if note else None,
        )
    return books


def load_pins(text: str) -> dict[str, BookPin]:
    """The generated pin file, keyed by id. Refused whole when malformed."""
    if GENERATED_MARK not in text:
        raise KiwixError("the pin file does not carry the generated-by line")
    data = yaml.safe_load(text) or {}
    rows = data.get("pins") if isinstance(data, dict) else None
    if not isinstance(rows, list):
        raise KiwixError("the pin file has no `pins:` list")
    pins: dict[str, BookPin] = {}
    for index, row in enumerate(rows):
        if not isinstance(row, dict):
            raise KiwixError(f"pin row {index} is not a mapping")
        where = f"pin row {index} ({row.get('id')!r})"
        book_id = _str(row, "id", where)
        file = _str(row, "file", where)
        match = _DATED.fullmatch(file)
        if match is None or match.group("id") != book_id:
            raise KiwixError(f"{where}: file {file!r} is not {book_id}_YYYY-MM.zim")
        url = _str(row, "url", where)
        if not url.startswith(f"{DOWNLOAD}/") or not url.endswith(f"/{file}"):
            raise KiwixError(f"{where}: url must be under {DOWNLOAD}/ and name {file}")
        size = row.get("size")
        if not isinstance(size, int) or isinstance(size, bool) or size <= 0:
            raise KiwixError(f"{where}: size must be a positive number of bytes")
        sha256 = _str(row, "sha256", where)
        if not _SHA256.fullmatch(sha256):
            raise KiwixError(f"{where}: sha256 must be 64 lowercase hex characters")
        if book_id in pins:
            raise KiwixError(f"{where}: {book_id!r} is pinned twice")
        pins[book_id] = BookPin(
            id=book_id,
            file=file,
            url=url,
            size=size,
            sha256=sha256,
            published=str(row.get("published") or ""),
            measured=str(row.get("measured") or ""),
        )
    return pins


BOOKS_FILE = Path("data") / "kiwix-books.yaml"
PINS_FILE = Path("data") / "kiwix-pins.yaml"


def load_book_list(catalog_root: Path) -> dict[str, Book]:
    """The catalog's book list, read from ``<catalog>/data/kiwix-books.yaml``."""
    path = catalog_root / BOOKS_FILE
    try:
        return load_books(path.read_text())
    except OSError as exc:
        raise KiwixError(f"{path}: {exc.strerror or exc}") from exc
    except KiwixError as exc:
        raise KiwixError(f"{path}: {exc}") from exc


def load_pin_file(catalog_root: Path) -> dict[str, BookPin]:
    """The generated pins, read from ``<catalog>/data/kiwix-pins.yaml``."""
    path = catalog_root / PINS_FILE
    try:
        return load_pins(path.read_text())
    except OSError as exc:
        raise KiwixError(f"{path}: {exc.strerror or exc}; {PINS_REMEDY}") from exc
    except KiwixError as exc:
        raise KiwixError(f"{path}: {exc}; {PINS_REMEDY}") from exc


def resolve_books(
    selection: Sequence[str], books: Mapping[str, Book], pins: Mapping[str, BookPin]
) -> list[BookFile]:
    """The chosen ids as pinned files, in the order chosen. Every unknown or
    unpinned id is named together in one error."""
    unknown = [book_id for book_id in selection if book_id not in books]
    unpinned = [book_id for book_id in selection if book_id in books and book_id not in pins]
    problems: list[str] = []
    if unknown:
        problems.append(
            f"not in the catalog's book list: {', '.join(unknown)}. {LIST_REMEDY}; a book "
            f"not on it has no licence the catalog can print, so it is not offered"
        )
    if unpinned:
        problems.append(
            f"in the catalog's book list but not pinned: {', '.join(unpinned)}; {PINS_REMEDY}"
        )
    if problems:
        raise KiwixError("; ".join(problems))
    seen: dict[str, None] = dict.fromkeys(selection)
    return [BookFile(books[book_id], pins[book_id]) for book_id in seen]


def parse_meta4(text: str) -> tuple[str, int, str]:
    """``(file name, size, sha256)`` from a MirrorBrain Metalink 4 document."""
    root = _xml(text, ".meta4")
    files = root.findall(f"{_METALINK}file")
    if len(files) != 1:
        raise KiwixError(f"the .meta4 describes {len(files)} files, not one")
    node = files[0]
    name = node.get("name") or ""
    size_text = (node.findtext(f"{_METALINK}size") or "").strip()
    sha256 = ""
    for digest in node.findall(f"{_METALINK}hash"):
        if digest.get("type") == "sha-256":
            sha256 = (digest.text or "").strip().lower()
    if not _SHA256.fullmatch(sha256):
        raise KiwixError(f"the .meta4 for {name!r} carries no sha-256")
    if not size_text.isdigit() or int(size_text) <= 0:
        raise KiwixError(f"the .meta4 for {name!r} carries no size")
    if _DATED.fullmatch(name) is None:
        raise KiwixError(f"the .meta4 names {name!r}, not a dated .zim")
    return name, int(size_text), sha256


def parse_library(text: str) -> dict[tuple[str, str | None], str]:
    """``(name, flavour) -> .meta4 URL`` for every book in ``library_zim.xml``.

    The library lists one entry per book and flavour (the current file); a
    book with no flavour attribute is keyed with ``None``.
    """
    root = _xml(text, "library")
    out: dict[tuple[str, str | None], str] = {}
    for node in root.iter("book"):
        name = node.get("name")
        url = node.get("url")
        if not name or not url:
            continue
        out[(name, node.get("flavour") or None)] = url
    return out


def current_file(text: str, name: str, flavour: str | None) -> str | None:
    """From an OPDS answer, the file Kiwix currently publishes for this book,
    or None when the answer does not list it."""
    root = _xml(text, "OPDS answer")
    for entry in root.iter(f"{_ATOM}entry"):
        if (entry.findtext(f"{_ATOM}name") or "").strip() != name:
            continue
        if ((entry.findtext(f"{_ATOM}flavour") or "").strip() or None) != flavour:
            continue
        for link in entry.iter(f"{_ATOM}link"):
            href = link.get("href") or ""
            if link.get("type") == "application/x-zim" and href.endswith(".meta4"):
                return href.rsplit("/", 1)[-1].removesuffix(".meta4")
    return None


def total_size(files: Iterable[BookFile]) -> int:
    return sum(f.pin.size for f in files)


#: The hosts the engine asks about books: the origin, its load balancer (the
#: origin answers 301 to it), and the OPDS catalogue `update --upstream` reads.
KIWIX_HOSTS = frozenset({"download.kiwix.org", "lb.download.kiwix.org", "opds.library.kiwix.org"})
_GONE = frozenset({404, 410})


class KiwixProbe:
    """The network, for books: ``HEAD`` a pinned file, ``GET`` a small answer.

    Built from :class:`~urllib.request.OpenerDirector` with only the HTTP(S)
    handlers, as :class:`hammunition.fetch.UrllibTransport` is, so no
    ``file:`` URL is ever served. ``head`` follows a redirect only between
    Kiwix's own hosts: download.kiwix.org answers 301 to its load balancer,
    which answers 302 to a mirror for a file it has and 404 for one it does
    not, and a redirect to a mirror is the answer ("published"), not a hop to
    take. Nothing here is trusted: a book is checked against its pinned
    sha256 when it is fetched, by the fetcher.
    """

    MAX_TEXT = 1024 * 1024

    def __init__(self, *, timeout: float = 30.0) -> None:
        import urllib.request

        self.timeout = timeout
        director = urllib.request.OpenerDirector()
        director.add_handler(urllib.request.HTTPSHandler())
        self._head = director
        text = urllib.request.OpenerDirector()
        for handler in (
            urllib.request.HTTPSHandler(),
            urllib.request.HTTPRedirectHandler(),
            urllib.request.HTTPErrorProcessor(),
            urllib.request.HTTPDefaultErrorHandler(),
        ):
            text.add_handler(handler)
        self._text = text

    @staticmethod
    def _checked(url: str) -> str:
        from urllib.parse import urlsplit

        parts = urlsplit(url)
        if parts.scheme != "https" or parts.hostname not in KIWIX_HOSTS:
            raise KiwixError(f"refusing {url!r}: only Kiwix's own hosts are asked about books")
        return url

    def head(self, url: str) -> int:
        """The status that settles whether *url* is published: 200, or a
        redirect off Kiwix's hosts to a mirror; 404 when it is gone."""
        import urllib.request

        current = self._checked(url)
        for _hop in range(4):
            request = urllib.request.Request(current, headers={"User-Agent": "hammunition"})
            request.method = "HEAD"
            try:
                response = self._head.open(request, timeout=self.timeout)
            except OSError as exc:
                raise KiwixError(f"{url} could not be reached: {exc}") from exc
            if response is None:  # pragma: no cover - no handler claimed the scheme
                raise KiwixError(f"no handler would ask {url!r}")
            with response:
                status: int = response.status
                location = response.headers.get("Location")
            if status in (301, 302, 303, 307, 308) and location:
                try:
                    current = self._checked(location)
                except KiwixError:
                    return 200  # handed to a mirror: the file is published
                continue
            return status
        raise KiwixError(f"{url}: too many redirects between Kiwix's hosts")

    def text(self, url: str) -> str:
        import urllib.error
        import urllib.request

        request = urllib.request.Request(self._checked(url), headers={"User-Agent": "hammunition"})
        try:
            response = self._text.open(request, timeout=self.timeout)
        except urllib.error.HTTPError as exc:
            if exc.code in _GONE:
                raise KiwixGone(url) from exc
            raise KiwixError(f"{url} returned HTTP {exc.code} ({exc.reason})") from exc
        except OSError as exc:
            raise KiwixError(f"{url} could not be fetched: {exc}") from exc
        if response is None:  # pragma: no cover
            raise KiwixError(f"no handler would fetch {url!r}")
        with response:
            self._checked(response.geturl())
            body: bytes = response.read(self.MAX_TEXT + 1)
        if len(body) > self.MAX_TEXT:
            raise KiwixError(f"{url} is larger than {self.MAX_TEXT} bytes; refusing to read it")
        return body.decode("utf-8", errors="replace")


class KiwixGone(KiwixError):
    """The URL answered 404 or 410: Kiwix no longer publishes it."""
