# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Launcher generation — wrappers and desktop entries from manifest data.

M3's last named requirement: 14 units install software an operator then
cannot start — Java jars, run-in-place trees, programs that need a working
directory or a service endpoint argument. AHRL answers with generated shell
scripts and a hand-maintained xdg menu tree; here both are generated from the
manifest's ``launchers`` block, per D-036.

Two artifacts per launcher, both per-user and both unprivileged:

- **A wrapper script** in ``~/.local/bin`` — sets the working directory when
  the manifest declares one, substitutes ``{endpoint:NAME}`` from the
  manifest's ``service_endpoints`` (D-013's repointable-backend rule: the URL
  lives in the catalog, not in the launcher), and runs the exec line. The
  exec line is shell, deliberately: ais-catcher's launcher backgrounds a
  browser against its own web map, and pretending that is an argv would just
  move the shell somewhere less reviewable. The line comes from the catalog —
  reviewed data, the opposite of piped remote content.
- **A desktop entry** in ``~/.local/share/applications`` so the DE's menu
  shows it. ``Categories=`` starts from the freedesktop-registered
  ``HamRadio`` plus a mapping from the manifest's own categories, which is
  D-036's curation seed — the same tags, never a second taxonomy. Every entry
  carries ``X-Hammunition-Package`` so a later uninstall or menu build can
  find its own work.

A launcher whose exec line starts with ``hammunition`` (QMapShack's two)
runs the engine by **absolute path** (issue #145). Plasma starts a menu entry
as a systemd user service, whose PATH has no ``~/.local/bin``, and a bare
``hammunition`` there is "not found", status 127. The path written is
bootstrap's ``~/.local/bin/hammunition`` link when that link runs this
engine, so a checkout that moves is fixed by re-running ``./bootstrap.sh``
(which relinks) rather than by regenerating every launcher; otherwise it is
the running engine's own entry point. ``hammunition doctor`` reads every
generated launcher back and names one whose engine is gone.

The per-DE curated submenu layer (Xfce ``.menu`` files, GNOME app-folders,
COSMIC) sits on top of these entries and is measured before it is built —
D-036 names the three mechanisms and what is still unknown about each.
"""

from __future__ import annotations

import os
import re
import shlex
import shutil
import sys
from dataclasses import dataclass
from functools import partial
from pathlib import Path

from hammunition.backends.base import Action, BackendError
from hammunition.manifest.schema import ENDPOINT_REF, Launcher, PackageManifest

__all__ = [
    "ENGINE",
    "MARKER",
    "EngineLaunchers",
    "calls_engine",
    "desktop_entry",
    "engine_call",
    "engine_path",
    "launcher_steps",
    "resolve_endpoints",
    "survey_engine_launchers",
    "wrapper_body",
    "wrapper_step",
]

#: The engine's own command name, as the catalog writes it in an exec line.
ENGINE = "hammunition"

#: The marker every generated wrapper carries on its second line; uninstall
#: (state/uninstall.py) removes only a file that has it.
MARKER = "# generated by hammunition for "

#: An exec line that runs the engine: ``hammunition ...`` or ``exec hammunition ...``.
_ENGINE_CALL = re.compile(rf"^(\s*(?:exec\s+)?){ENGINE}(?=\s|$)")

#: Catalog category -> additional freedesktop menu categories. Every entry
#: also gets HamRadio (registered in the freedesktop menu spec) except the
#: plainly-not-radio ones. Presentation policy, not install logic — the
#: catalog stays the single source of what a package *is*.
XDG_CATEGORIES: dict[str, str] = {
    "aircraft": "HamRadio;Geography",
    "antenna": "HamRadio;Engineering",
    "antenna-analysers": "HamRadio;Engineering",
    "aprs": "HamRadio;Geography",
    "bluetooth": "Network;Security",
    "broadcast": "HamRadio;Audio",
    "capture-analysis": "Network;Security",
    "cellular": "Network;Security",
    "contest": "HamRadio",
    "cw": "HamRadio;Audio",
    "dashboards": "HamRadio;Science",
    "device-support": "System;HardwareSettings",
    "digital-voice": "HamRadio;Audio",
    "dmr": "HamRadio;Settings",
    "dx-cluster": "HamRadio;Network",
    "echolink-repeaters": "HamRadio;Network",
    "electronics": "Electronics;Engineering",
    "email-clients": "Network;Email",
    "emcomm": "HamRadio;Network",
    "exams": "HamRadio;Education",
    "gps-gnss": "HamRadio;Geography",
    "ism-subghz": "Network;Security",
    "keyboard-modes": "HamRadio;AudioVideo",
    "locators": "HamRadio;Geography",
    "logging": "HamRadio;Database",
    "mesh": "Network",
    "morse-training": "HamRadio;Education",
    "navigation-maps": "Utility;Geography",
    "nbems": "HamRadio;Network",
    "packet-nodes": "HamRadio;Network",
    "packet-terminals": "HamRadio;Network",
    "pagers-decoders": "HamRadio;Audio",
    "programmer": "Electronics;Development",
    "propagation": "HamRadio;Science",
    "radio-programming": "HamRadio;Settings",
    "references": "HamRadio;Education",
    "rf-research": "Network;Security",
    "rfid": "Security",
    "rig-control": "HamRadio;Settings",
    "satellite-decoding": "HamRadio;Science",
    "satellite-tracking": "HamRadio;Science",
    "sdr-hardware": "HamRadio;Settings",
    "sdr-receivers": "HamRadio;AudioVideo",
    "sdr-toolkits": "HamRadio;Science",
    "serial-terminals": "Utility;TerminalEmulator",
    "ships": "HamRadio;Geography",
    "signal-analysis": "HamRadio;Science",
    "soundcard-modems": "HamRadio;Network",
    "spectrum-analysers": "HamRadio;Engineering",
    "sstv-atv": "HamRadio;AudioVideo",
    "time-frequency": "HamRadio;Utility",
    "weak-signal": "HamRadio;AudioVideo",
    "weather-sensors": "HamRadio;Science",
    "wifi": "Network;Security",
    "winlink": "HamRadio;Network;Email",
    "workstation": "Utility",
}


def resolve_endpoints(manifest: PackageManifest, exec_line: str) -> str:
    """Substitute ``{endpoint:NAME}`` with the endpoint's default URL.

    The schema guarantees every reference is declared; an undeclared one here
    means the objects diverged from their manifest and failing loudly beats
    generating a launcher that starts the wrong backend.
    """
    endpoints = {e.name: e.default_url for e in manifest.service_endpoints}

    def substitute(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in endpoints:
            raise BackendError(
                f"{manifest.name}: launcher references endpoint {name!r} which is "
                f"not declared — the manifest and its objects have diverged"
            )
        return endpoints[name]

    return ENDPOINT_REF.sub(substitute, exec_line)


def calls_engine(launcher: Launcher) -> bool:
    """Whether this launcher's exec line runs the engine itself."""
    return _ENGINE_CALL.match(launcher.exec) is not None


def _running_engine() -> Path | None:
    """The ``hammunition`` entry point running now, as an absolute path.

    ``sys.argv[0]`` when it is the entry point (the usual case, and the only
    one that can name the ``~/.local/bin`` link it was reached through); the
    entry point beside the interpreter when run as ``python -m hammunition``;
    the PATH's ``hammunition`` last. Absolute, never resolved: a relative
    ``.venv/bin/hammunition`` means the cwd's, and a link is kept as a link.
    """
    candidates: list[Path] = []
    if sys.argv and sys.argv[0] and Path(sys.argv[0]).name == ENGINE:
        candidates.append(Path(sys.argv[0]).absolute())
    candidates.append(Path(sys.executable).absolute().parent / ENGINE)
    found = shutil.which(ENGINE)
    if found:
        candidates.append(Path(found).absolute())
    for candidate in candidates:
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return candidate
    return None


def engine_path(bin_dir: Path) -> Path:
    """The absolute ``hammunition`` a launcher in ``bin_dir`` should run.

    ``bin_dir/hammunition`` -- bootstrap's link (D-059) -- when it is a link
    that runs this engine, so a moved checkout is mended by ``./bootstrap.sh``
    relinking it; otherwise this engine's own entry point. Never a link to a
    different checkout: the launcher runs the engine that wrote it.
    """
    running = _running_engine()
    if running is None:
        raise BackendError(
            "cannot find the `hammunition` executable that is running, so a launcher "
            "that runs it cannot name it; run ./bootstrap.sh in your checkout and "
            "start hammunition as .venv/bin/hammunition or through ~/.local/bin/hammunition"
        )
    link = bin_dir / ENGINE
    try:
        if link.is_symlink() and link.resolve() == running.resolve():
            return link
    except OSError:
        pass
    return running


def wrapper_body(
    manifest: PackageManifest,
    launcher: Launcher,
    *,
    venv_dir: Path | None = None,
    node_wrapper: Path | None = None,
    engine: Path | None = None,
) -> str:
    lines = ["#!/bin/sh", f"{MARKER}{manifest.name}"]
    if launcher.working_directory:
        lines.append(f"cd {launcher.working_directory!r} || exit 1")
    exec_line = resolve_endpoints(manifest, launcher.exec)
    if "{venv}" in exec_line:
        if venv_dir is None:
            raise BackendError(
                f"{manifest.name}: launcher references {{venv}} but the manifest "
                f"resolved to no venv on this target — the launcher and the "
                f"install method have diverged"
            )
        exec_line = exec_line.replace("{venv}", str(venv_dir))
    if "{node}" in exec_line:
        # The node backend's own wrapper (cd into the tree, bind loopback,
        # exec node): a launcher composes it -- starts it, opens a browser --
        # rather than restating the bind, which is the engine's rule to keep.
        if node_wrapper is None:
            raise BackendError(
                f"{manifest.name}: launcher references {{node}} but the manifest "
                f"resolved to no node build on this target — the launcher and the "
                f"install method have diverged"
            )
        exec_line = exec_line.replace("{node}", str(node_wrapper))
    if _ENGINE_CALL.match(exec_line):
        # Issue #145: by absolute path, because a menu entry started as a
        # systemd user service has no ~/.local/bin on its PATH.
        if engine is None:
            raise BackendError(
                f"{manifest.name}: launcher {launcher.name} runs hammunition but no "
                f"engine path was given -- a bare name fails from the desktop menu"
            )
        exec_line = _ENGINE_CALL.sub(
            lambda m: m.group(1) + shlex.quote(str(engine)), exec_line, count=1
        )
    if exec_line.split()[:1] == [launcher.name]:
        # The wrapper is written to ~/.local/bin under the tool's own name,
        # and Debian's .profile puts that directory first on PATH, so the
        # command line below would resolve to this file again -- measured on
        # the field laptop, where ubertooth-util forked itself until the
        # process limit. Take this directory out of PATH first. Compared
        # both as written and resolved, so a symlinked home matches either way.
        # Shell builtins only: PATH is what is being edited.
        lines += [
            "case $0 in */*) here=${0%/*} ;; *) here=. ;; esac",
            'real=$(cd -- "$here" && pwd -P)',
            "rest=; IFS=:; for dir in $PATH; do",
            '  [ "$dir" = "$here" ] || [ "$dir" = "$real" ] || rest="${rest:+$rest:}$dir"',
            "done; unset IFS",
            "PATH=$rest; export PATH",
        ]
    lines.append(exec_line)
    if launcher.terminal:
        # A terminal launcher holds its window: the tool's output is the
        # point, and a window that closes the instant `hackrf_info` exits
        # shows the operator nothing. Parrot's own tool menu keeps the
        # window; so does this. The schema refuses `exec ...` on a terminal
        # launcher, or these lines would never run. The wrapper then exits
        # with the tool's status, not `read`'s: without a keyboard (the
        # headless GUI smoke lane, 2026-09-12) `read` fails at end-of-input,
        # and a wrapper ending there reported rc=1 for an st-info that had
        # printed "[exit 0]".
        lines += [
            "status=$?",
            "printf '\\n[exit %s] press Enter to close ' \"$status\"",
            "read _",
            'exit "$status"',
        ]
    return "\n".join(lines) + "\n"


def desktop_entry(manifest: PackageManifest, launcher: Launcher, wrapper: Path) -> str:
    categories = sorted(
        {
            part
            for category in manifest.categories
            for part in XDG_CATEGORIES.get(category, "HamRadio").split(";")
        }
        # The catalog's own tags ride along as X- extension categories (the
        # menu spec reserves the prefix for exactly this), so the curated
        # menu tree can include by catalog category without a second
        # taxonomy anywhere (D-036).
        | {f"X-Hammunition-{category}" for category in manifest.categories}
    )
    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        f"Name={launcher.display_name}\n"
        f"Comment={manifest.summary}\n"
        f"Exec={wrapper}\n"
        f"Terminal={'true' if launcher.terminal else 'false'}\n"
        f"Categories={';'.join(categories)};\n"
        f"X-Hammunition-Package={manifest.name}\n"
    )


def write_launcher(path: Path, body: str, mode: int) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    os.chmod(path, mode)
    return f"wrote {path}"


def wrapper_step(
    manifest: PackageManifest,
    launcher: Launcher,
    *,
    bin_dir: Path,
    venv_dir: Path | None = None,
    node_wrapper: Path | None = None,
    engine: Path | None = None,
    verb: str = "Generate",
) -> Action:
    """The wrapper script for one launcher. ``engine`` is resolved from
    ``bin_dir`` (:func:`engine_path`) when the launcher runs hammunition and
    none is given, and the plan names it, so the dry run shows what the
    launcher will run."""
    wrapper = bin_dir / launcher.name
    if engine is None and calls_engine(launcher):
        engine = engine_path(bin_dir)
    body = wrapper_body(
        manifest, launcher, venv_dir=venv_dir, node_wrapper=node_wrapper, engine=engine
    )
    detail = str(wrapper)
    if launcher.working_directory:
        detail += f", runs in {launcher.working_directory}"
    if calls_engine(launcher):
        detail += f", calls {engine}"
    return Action(
        kind="wrapper",
        description=f"{verb} the {launcher.name} launcher for {manifest.name}",
        detail=detail,
        perform=partial(write_launcher, wrapper, body, 0o755),
    )


def launcher_steps(
    manifest: PackageManifest,
    *,
    bin_dir: Path,
    applications_dir: Path,
    venv_dir: Path | None = None,
    node_wrapper: Path | None = None,
    engine: Path | None = None,
) -> list[Action]:
    """Both artifacts for every launcher the manifest declares."""
    steps: list[Action] = []
    for launcher in manifest.launchers:
        wrapper = bin_dir / launcher.name
        if engine is None and calls_engine(launcher):
            engine = engine_path(bin_dir)
        steps.append(
            wrapper_step(
                manifest,
                launcher,
                bin_dir=bin_dir,
                venv_dir=venv_dir,
                node_wrapper=node_wrapper,
                engine=engine,
            )
        )
        entry = applications_dir / f"hammunition-{launcher.name}.desktop"
        steps.append(
            Action(
                kind="desktop-entry",
                description=f"Add {launcher.name} to the desktop menus",
                detail=str(entry),
                perform=partial(
                    write_launcher, entry, desktop_entry(manifest, launcher, wrapper), 0o644
                ),
            )
        )
    return steps


def engine_call(body: str) -> str | None:
    """The ``hammunition`` a wrapper runs, as written in it, or None.

    Read back from the file rather than recomputed from the manifest, so
    ``doctor`` reports what is on disk -- including a launcher written before
    issue #145, which says plain ``hammunition``.
    """
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        try:
            words = shlex.split(stripped)
        except ValueError:
            continue
        if words[:1] == ["exec"]:
            words = words[1:]
        if words and Path(words[0]).name == ENGINE:
            return words[0]
    return None


@dataclass(frozen=True)
class EngineLaunchers:
    """Generated launchers in one ``~/.local/bin`` that run the engine."""

    ok: tuple[str, ...] = ()
    """Launchers whose engine path exists and is executable."""
    bare: tuple[str, ...] = ()
    """Launchers written before issue #145: a bare ``hammunition``."""
    broken: tuple[tuple[str, str], ...] = ()
    """(launcher, engine path) where the engine is gone or not executable."""


def survey_engine_launchers(bin_dir: Path) -> EngineLaunchers:
    """Sort the engine-calling launchers in ``bin_dir`` by whether they work.

    Only files carrying the generated marker are ours; the engine's own link
    and anything else in the directory are not read.
    """
    ok: list[str] = []
    bare: list[str] = []
    broken: list[tuple[str, str]] = []
    try:
        candidates = sorted(bin_dir.iterdir())
    except OSError:
        return EngineLaunchers()
    for path in candidates:
        if path.is_symlink() or not path.is_file():
            continue
        try:
            with path.open(encoding="utf-8", errors="replace") as handle:
                head = handle.read(64 * 1024)
        except OSError:
            continue
        if not any(line.startswith(MARKER) for line in head.splitlines()[:3]):
            continue
        called = engine_call(head)
        if called is None:
            continue
        if "/" not in called:
            bare.append(str(path))
        elif Path(called).is_file() and os.access(called, os.X_OK):
            ok.append(str(path))
        else:
            broken.append((str(path), called))
    return EngineLaunchers(ok=tuple(ok), bare=tuple(bare), broken=tuple(broken))
