# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Launcher generation — wrappers and desktop entries from manifest data.

M3's last named requirement: 14 units install software an operator then
cannot start — Java jars, run-in-place trees, programs that need a working
directory or a service endpoint argument. AHRL answers with generated shell
scripts and a hand-maintained xdg menu tree; here both are generated from the
manifest's ``launchers`` block, per D-036.

Two artifacts per launcher, both per-user and both unprivileged:

- **A wrapper script** in ``~/.local/bin`` — sets the working directory when
  the manifest declares one, substitutes ``{endpoint:NAME}`` from the
  manifest's ``service_endpoints`` (D-013's repointable-backend rule: the URL
  lives in the catalog, not in the launcher), and runs the exec line. The
  exec line is shell, deliberately: ais-catcher's launcher backgrounds a
  browser against its own web map, and pretending that is an argv would just
  move the shell somewhere less reviewable. The line comes from the catalog —
  reviewed data, the opposite of piped remote content.
- **A desktop entry** in ``~/.local/share/applications`` so the DE's menu
  shows it. ``Categories=`` starts from the freedesktop-registered
  ``HamRadio`` plus a mapping from the manifest's own categories, which is
  D-036's curation seed — the same tags, never a second taxonomy. Every entry
  carries ``X-Hammunition-Package`` so a later uninstall or menu build can
  find its own work.

A launcher whose exec line starts with ``hammunition`` (QMapShack's two)
runs the engine by **absolute path** (issue #145). Plasma starts a menu entry
as a systemd user service, whose PATH has no ``~/.local/bin``, and a bare
``hammunition`` there is "not found", status 127. The path written is
bootstrap's ``~/.local/bin/hammunition`` link when that link runs this
engine, so a checkout that moves is fixed by re-running ``./bootstrap.sh``
(which relinks) rather than by regenerating every launcher; otherwise it is
the running engine's own entry point. ``hammunition doctor`` reads every
generated launcher back and names one whose engine is gone.

The per-DE curated submenu layer (Xfce ``.menu`` files, GNOME app-folders,
COSMIC) sits on top of these entries and is measured before it is built —
D-036 names the three mechanisms and what is still unknown about each.
"""

from __future__ import annotations

import os
import re
import shlex
import shutil
import sys
from collections.abc import Callable
from dataclasses import dataclass
from functools import partial
from pathlib import Path

from hammunition.backends.base import Action, BackendError
from hammunition.manifest.schema import ENDPOINT_REF, Launcher, PackageManifest

__all__ = [
    "ENGINE",
    "MARKER",
    "SYSTEM_DIRS",
    "EngineLaunchers",
    "ExecutableLister",
    "calls_engine",
    "desktop_entry",
    "engine_call",
    "engine_path",
    "launcher_steps",
    "resolve_endpoints",
    "search_path_outside",
    "shadowed_binary",
    "shadowing_error",
    "shadowing_launcher_steps",
    "survey_engine_launchers",
    "survey_shadowing_launchers",
    "wrapper_body",
    "wrapper_step",
]

#: The engine's own command name, as the catalog writes it in an exec line.
ENGINE = "hammunition"

#: The marker every generated wrapper carries on its second line; uninstall
#: (state/uninstall.py) removes only a file that has it.
MARKER = "# generated by hammunition for "

#: An exec line that runs the engine: ``hammunition ...`` or ``exec hammunition ...``.
_ENGINE_CALL = re.compile(rf"^(\s*(?:exec\s+)?){ENGINE}(?=\s|$)")

#: Catalog category -> additional freedesktop menu categories. Every entry
#: also gets HamRadio (registered in the freedesktop menu spec) except the
#: plainly-not-radio ones. Presentation policy, not install logic — the
#: catalog stays the single source of what a package *is*.
XDG_CATEGORIES: dict[str, str] = {
    "aircraft": "HamRadio;Geography",
    "antenna": "HamRadio;Engineering",
    "antenna-analysers": "HamRadio;Engineering",
    "aprs": "HamRadio;Geography",
    "bluetooth": "Network;Security",
    "broadcast": "HamRadio;Audio",
    "capture-analysis": "Network;Security",
    "cellular": "Network;Security",
    "contest": "HamRadio",
    "cw": "HamRadio;Audio",
    "dashboards": "HamRadio;Science",
    "device-support": "System;HardwareSettings",
    "digital-voice": "HamRadio;Audio",
    "dmr": "HamRadio;Settings",
    "dx-cluster": "HamRadio;Network",
    "echolink-repeaters": "HamRadio;Network",
    "electronics": "Electronics;Engineering",
    "email-clients": "Network;Email",
    "emcomm": "HamRadio;Network",
    "exams": "HamRadio;Education",
    "gps-gnss": "HamRadio;Geography",
    "ism-subghz": "Network;Security",
    "keyboard-modes": "HamRadio;AudioVideo",
    "locators": "HamRadio;Geography",
    "logging": "HamRadio;Database",
    "mesh": "Network",
    "morse-training": "HamRadio;Education",
    "navigation-maps": "Utility;Geography",
    "nbems": "HamRadio;Network",
    "packet-nodes": "HamRadio;Network",
    "packet-terminals": "HamRadio;Network",
    "pagers-decoders": "HamRadio;Audio",
    "programmer": "Electronics;Development",
    "propagation": "HamRadio;Science",
    "radio-programming": "HamRadio;Settings",
    "references": "HamRadio;Education",
    "rf-research": "Network;Security",
    "rfid": "Security",
    "rig-control": "HamRadio;Settings",
    "satellite-decoding": "HamRadio;Science",
    "satellite-tracking": "HamRadio;Science",
    "sdr-hardware": "HamRadio;Settings",
    "sdr-receivers": "HamRadio;AudioVideo",
    "sdr-toolkits": "HamRadio;Science",
    "serial-terminals": "Utility;TerminalEmulator",
    "ships": "HamRadio;Geography",
    "signal-analysis": "HamRadio;Science",
    "soundcard-modems": "HamRadio;Network",
    "spectrum-analysers": "HamRadio;Engineering",
    "sstv-atv": "HamRadio;AudioVideo",
    "time-frequency": "HamRadio;Utility",
    "weak-signal": "HamRadio;AudioVideo",
    "weather-sensors": "HamRadio;Science",
    "wifi": "Network;Security",
    "winlink": "HamRadio;Network;Email",
    "workstation": "Utility",
}


def resolve_endpoints(manifest: PackageManifest, exec_line: str) -> str:
    """Substitute ``{endpoint:NAME}`` with the endpoint's default URL.

    The schema guarantees every reference is declared; an undeclared one here
    means the objects diverged from their manifest and failing loudly beats
    generating a launcher that starts the wrong backend.
    """
    endpoints = {e.name: e.default_url for e in manifest.service_endpoints}

    def substitute(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in endpoints:
            raise BackendError(
                f"{manifest.name}: launcher references endpoint {name!r} which is "
                f"not declared — the manifest and its objects have diverged"
            )
        return endpoints[name]

    return ENDPOINT_REF.sub(substitute, exec_line)


def calls_engine(launcher: Launcher) -> bool:
    """Whether this launcher's exec line runs the engine itself."""
    return _ENGINE_CALL.match(launcher.exec) is not None


def _running_engine() -> Path | None:
    """The ``hammunition`` entry point running now, as an absolute path.

    ``sys.argv[0]`` when it is the entry point (the usual case, and the only
    one that can name the ``~/.local/bin`` link it was reached through); the
    entry point beside the interpreter when run as ``python -m hammunition``;
    the PATH's ``hammunition`` last. Absolute, never resolved: a relative
    ``.venv/bin/hammunition`` means the cwd's, and a link is kept as a link.
    """
    candidates: list[Path] = []
    if sys.argv and sys.argv[0] and Path(sys.argv[0]).name == ENGINE:
        candidates.append(Path(sys.argv[0]).absolute())
    candidates.append(Path(sys.executable).absolute().parent / ENGINE)
    found = shutil.which(ENGINE)
    if found:
        candidates.append(Path(found).absolute())
    for candidate in candidates:
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return candidate
    return None


def engine_path(bin_dir: Path) -> Path:
    """The absolute ``hammunition`` a launcher in ``bin_dir`` should run.

    ``bin_dir/hammunition`` -- bootstrap's link (D-059) -- when it is a link
    that runs this engine, so a moved checkout is mended by ``./bootstrap.sh``
    relinking it; otherwise this engine's own entry point. Never a link to a
    different checkout: the launcher runs the engine that wrote it.
    """
    running = _running_engine()
    if running is None:
        raise BackendError(
            "cannot find the `hammunition` executable that is running, so a launcher "
            "that runs it cannot name it; run ./bootstrap.sh in your checkout and "
            "start hammunition as .venv/bin/hammunition or through ~/.local/bin/hammunition"
        )
    link = bin_dir / ENGINE
    try:
        if link.is_symlink() and link.resolve() == running.resolve():
            return link
    except OSError:
        pass
    return running


def wrapper_body(
    manifest: PackageManifest,
    launcher: Launcher,
    *,
    venv_dir: Path | None = None,
    node_wrapper: Path | None = None,
    engine: Path | None = None,
) -> str:
    lines = ["#!/bin/sh", f"{MARKER}{manifest.name}"]
    if launcher.working_directory:
        lines.append(f"cd {launcher.working_directory!r} || exit 1")
    exec_line = resolve_endpoints(manifest, launcher.exec)
    if "{venv}" in exec_line:
        if venv_dir is None:
            raise BackendError(
                f"{manifest.name}: launcher references {{venv}} but the manifest "
                f"resolved to no venv on this target — the launcher and the "
                f"install method have diverged"
            )
        exec_line = exec_line.replace("{venv}", str(venv_dir))
    if "{node}" in exec_line:
        # The node backend's own wrapper (cd into the tree, bind loopback,
        # exec node): a launcher composes it -- starts it, opens a browser --
        # rather than restating the bind, which is the engine's rule to keep.
        if node_wrapper is None:
            raise BackendError(
                f"{manifest.name}: launcher references {{node}} but the manifest "
                f"resolved to no node build on this target — the launcher and the "
                f"install method have diverged"
            )
        exec_line = exec_line.replace("{node}", str(node_wrapper))
    if _ENGINE_CALL.match(exec_line):
        # Issue #145: by absolute path, because a menu entry started as a
        # systemd user service has no ~/.local/bin on its PATH.
        if engine is None:
            raise BackendError(
                f"{manifest.name}: launcher {launcher.name} runs hammunition but no "
                f"engine path was given -- a bare name fails from the desktop menu"
            )
        exec_line = _ENGINE_CALL.sub(
            lambda m: m.group(1) + shlex.quote(str(engine)), exec_line, count=1
        )
    lines.append(exec_line)
    if launcher.terminal:
        # A terminal launcher holds its window: the tool's output is the
        # point, and a window that closes the instant `hackrf_info` exits
        # shows the operator nothing. Parrot's own tool menu keeps the
        # window; so does this. The schema refuses `exec ...` on a terminal
        # launcher, or these lines would never run. The wrapper then exits
        # with the tool's status, not `read`'s: without a keyboard (the
        # headless GUI smoke lane, 2026-09-12) `read` fails at end-of-input,
        # and a wrapper ending there reported rc=1 for an st-info that had
        # printed "[exit 0]".
        lines += [
            "status=$?",
            "printf '\\n[exit %s] press Enter to close ' \"$status\"",
            "read _",
            'exit "$status"',
        ]
    return "\n".join(lines) + "\n"


def desktop_entry(manifest: PackageManifest, launcher: Launcher, wrapper: Path) -> str:
    categories = sorted(
        {
            part
            for category in manifest.categories
            for part in XDG_CATEGORIES.get(category, "HamRadio").split(";")
        }
        # The catalog's own tags ride along as X- extension categories (the
        # menu spec reserves the prefix for exactly this), so the curated
        # menu tree can include by catalog category without a second
        # taxonomy anywhere (D-036).
        | {f"X-Hammunition-{category}" for category in manifest.categories}
    )
    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        f"Name={launcher.display_name}\n"
        f"Comment={manifest.summary}\n"
        f"Exec={wrapper}\n"
        f"Terminal={'true' if launcher.terminal else 'false'}\n"
        f"Categories={';'.join(categories)};\n"
        f"X-Hammunition-Package={manifest.name}\n"
    )


def write_launcher(path: Path, body: str, mode: int) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    os.chmod(path, mode)
    return f"wrote {path}"


# ---------------------------------------------------------------------------
# Issue #174: a launcher never shadows a binary on the PATH.
# ---------------------------------------------------------------------------

#: Searched whatever the caller's PATH says: a launcher named like an admin
#: tool in /usr/sbin is still a second program by one name, and a PATH
#: trimmed by sudo or a systemd unit must not make a clash disappear.
SYSTEM_DIRS = ("/usr/local/sbin", "/usr/local/bin", "/usr/sbin", "/usr/bin", "/sbin", "/bin")

ExecutableLister = Callable[[str], list[str]]
"""Given a distribution package, the executables it installed here (empty
when it is not installed). :func:`hammunition.menus.dpkg_executables` is the
real one; the tests inject theirs."""


def _same_dir(entry: str, bin_dir: Path) -> bool:
    if not entry:
        return False
    if os.path.abspath(entry) == os.path.abspath(bin_dir):
        return True
    try:
        return os.path.realpath(entry) == os.path.realpath(bin_dir)
    except OSError:
        return False


def search_path_outside(bin_dir: Path, path: str | None = None) -> str:
    """``PATH`` (the environment's by default) without ``bin_dir``, then the
    standard system directories it does not already name.

    ``bin_dir`` is compared as written and resolved, so a symlinked home
    matches either way: what is in it is the launchers themselves, never the
    thing they would shadow.
    """
    entries = (os.environ.get("PATH", "") if path is None else path).split(os.pathsep)
    kept: list[str] = []
    for entry in (*entries, *SYSTEM_DIRS):
        if entry and entry not in kept and not _same_dir(entry, bin_dir):
            kept.append(entry)
    return os.pathsep.join(kept)


def _which_not_ours(name: str, search_path: str) -> str | None:
    """``shutil.which`` over ``search_path``, passing over a launcher this
    engine generated: another account's or another home's ``~/.local/bin``
    on the PATH holds wrappers, not the binaries they would shadow."""
    for entry in search_path.split(os.pathsep):
        found = shutil.which(name, path=entry) if entry else None
        if found and not _generated(Path(found)):
            return found
    return None


def _apt_packages(manifest: PackageManifest) -> list[str]:
    from hammunition.menus import _packages_of

    return sorted(_packages_of(manifest))


def shadowed_binary(
    manifest: PackageManifest,
    launcher: Launcher,
    *,
    bin_dir: Path,
    search_path: str | None = None,
    executables: ExecutableLister | None = None,
) -> str | None:
    """The binary a launcher by this name would shadow from ``bin_dir``, or None.

    Two measurements: ``shutil.which`` over the PATH with ``bin_dir`` taken
    out (:func:`search_path_outside`), and the file list of every apt
    package the manifest names, for a binary that is the unit's own but not
    on this PATH (``/usr/sbin``, or a package not yet unpacked when the
    search ran). The schema has already refused the name of the command the
    launcher runs and of the manifest's own ``binaries``.
    """
    if executables is None:
        from hammunition.menus import dpkg_executables

        executables = dpkg_executables
    found = _which_not_ours(launcher.name, search_path_outside(bin_dir, search_path))
    if found:
        return found
    for package in _apt_packages(manifest):
        for executable in executables(package):
            if Path(executable).name == launcher.name:
                return executable
    return None


def shadowing_error(manifest: PackageManifest, launcher: Launcher, shadowed: str) -> BackendError:
    return BackendError(
        f"{manifest.name}: refusing to write the launcher {launcher.name!r}: "
        f"{shadowed} already has that name, and ~/.local/bin comes first on PATH, so "
        f"the launcher would run in its place and swallow its arguments (issue #174). "
        f"rename the launcher in the manifest to say what it does "
        f"({launcher.name}-<what>), keeping its title"
    )


def _write_unshadowed(
    manifest: PackageManifest,
    launcher: Launcher,
    path: Path,
    body: str,
    *,
    search_path: str | None,
    executables: ExecutableLister | None,
) -> str:
    """Write the wrapper unless a clash appeared since the plan.

    The plan of a fresh install runs before apt unpacks the package whose
    binary the launcher would shadow; this asks again after it has.
    """
    shadowed = shadowed_binary(
        manifest, launcher, bin_dir=path.parent, search_path=search_path, executables=executables
    )
    if shadowed is not None:
        raise shadowing_error(manifest, launcher, shadowed)
    return write_launcher(path, body, 0o755)


def wrapper_step(
    manifest: PackageManifest,
    launcher: Launcher,
    *,
    bin_dir: Path,
    venv_dir: Path | None = None,
    node_wrapper: Path | None = None,
    engine: Path | None = None,
    verb: str = "Generate",
    search_path: str | None = None,
    executables: ExecutableLister | None = None,
) -> Action:
    """The wrapper script for one launcher. ``engine`` is resolved from
    ``bin_dir`` (:func:`engine_path`) when the launcher runs hammunition and
    none is given, and the plan names it, so the dry run shows what the
    launcher will run.

    Refused, at plan time and again when written, when the launcher's name
    is a binary's already (:func:`shadowed_binary`, issue #174).
    """
    shadowed = shadowed_binary(
        manifest, launcher, bin_dir=bin_dir, search_path=search_path, executables=executables
    )
    if shadowed is not None:
        raise shadowing_error(manifest, launcher, shadowed)
    wrapper = bin_dir / launcher.name
    if engine is None and calls_engine(launcher):
        engine = engine_path(bin_dir)
    body = wrapper_body(
        manifest, launcher, venv_dir=venv_dir, node_wrapper=node_wrapper, engine=engine
    )
    detail = str(wrapper)
    if launcher.working_directory:
        detail += f", runs in {launcher.working_directory}"
    if calls_engine(launcher):
        detail += f", calls {engine}"
    return Action(
        kind="wrapper",
        description=f"{verb} the {launcher.name} launcher for {manifest.name}",
        detail=detail,
        perform=partial(
            _write_unshadowed,
            manifest,
            launcher,
            wrapper,
            body,
            search_path=search_path,
            executables=executables,
        ),
    )


def launcher_steps(
    manifest: PackageManifest,
    *,
    bin_dir: Path,
    applications_dir: Path,
    venv_dir: Path | None = None,
    node_wrapper: Path | None = None,
    engine: Path | None = None,
    search_path: str | None = None,
    executables: ExecutableLister | None = None,
) -> list[Action]:
    """Both artifacts for every launcher the manifest declares."""
    steps: list[Action] = []
    for launcher in manifest.launchers:
        wrapper = bin_dir / launcher.name
        if engine is None and calls_engine(launcher):
            engine = engine_path(bin_dir)
        steps.append(
            wrapper_step(
                manifest,
                launcher,
                bin_dir=bin_dir,
                venv_dir=venv_dir,
                node_wrapper=node_wrapper,
                engine=engine,
                search_path=search_path,
                executables=executables,
            )
        )
        entry = applications_dir / f"hammunition-{launcher.name}.desktop"
        steps.append(
            Action(
                kind="desktop-entry",
                description=f"Add {launcher.name} to the desktop menus",
                detail=str(entry),
                perform=partial(
                    write_launcher, entry, desktop_entry(manifest, launcher, wrapper), 0o644
                ),
            )
        )
    return steps


def _generated(path: Path) -> bool:
    """Whether ``path`` is a wrapper this engine wrote: the marker, near the top."""
    if path.is_symlink() or not path.is_file():
        return False
    try:
        with path.open(encoding="utf-8", errors="replace") as handle:
            head = handle.read(4096)
    except OSError:
        return False
    return any(line.startswith(MARKER) for line in head.splitlines()[:3])


def survey_shadowing_launchers(
    bin_dir: Path, search_path: str | None = None
) -> tuple[tuple[str, str], ...]:
    """(launcher, binary) for every generated launcher in ``bin_dir`` whose
    name a binary elsewhere on the PATH also has (issue #174).

    Read from disk, not the catalog: what ``doctor`` reports and ``menus
    apply`` removes is the file a shell finds today, including one written
    under a name the catalog has since changed. A file without the generated
    marker is never ours to report or remove.
    """
    try:
        candidates = sorted(bin_dir.iterdir())
    except OSError:
        return ()
    outside = search_path_outside(bin_dir, search_path)
    found: list[tuple[str, str]] = []
    for path in candidates:
        if not _generated(path):
            continue
        shadowed = _which_not_ours(path.name, outside)
        if shadowed:
            found.append((str(path), shadowed))
    return tuple(found)


def _remove(path: Path) -> str:
    path.unlink()
    return f"removed {path}"


def shadowing_launcher_steps(
    bin_dir: Path, applications_dir: Path, search_path: str | None = None
) -> list[Action]:
    """Remove every generated launcher that shadows a PATH binary, and its
    desktop entry when that carries our package key.

    ``menus apply`` runs this before it writes the launchers a manifest
    declares, so a launcher renamed in the catalog (``rigctl`` became
    ``rigctl-dummy``) is replaced in one run: the old file goes, the new one
    is written, and both lines are printed.
    """
    steps: list[Action] = []
    for wrapper, shadowed in survey_shadowing_launchers(bin_dir, search_path):
        name = Path(wrapper).name
        steps.append(
            Action(
                kind="wrapper",
                description=(
                    f"Remove the generated {name} launcher: it shadows {shadowed} (issue #174)"
                ),
                detail=f"{wrapper} (shadows {shadowed}; removed)",
                perform=partial(_remove, Path(wrapper)),
            )
        )
        entry = applications_dir / f"hammunition-{name}.desktop"
        try:
            ours = entry.is_file() and "\nX-Hammunition-Package=" in "\n" + entry.read_text()
        except (OSError, UnicodeDecodeError):
            ours = False
        if ours:
            steps.append(
                Action(
                    kind="desktop-entry",
                    description=f"Remove {name}'s menu entry with it",
                    detail=str(entry),
                    perform=partial(_remove, entry),
                )
            )
    return steps


def engine_call(body: str) -> str | None:
    """The ``hammunition`` a wrapper runs, as written in it, or None.

    Read back from the file rather than recomputed from the manifest, so
    ``doctor`` reports what is on disk -- including a launcher written before
    issue #145, which says plain ``hammunition``.
    """
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        try:
            words = shlex.split(stripped)
        except ValueError:
            continue
        if words[:1] == ["exec"]:
            words = words[1:]
        if words and Path(words[0]).name == ENGINE:
            return words[0]
    return None


@dataclass(frozen=True)
class EngineLaunchers:
    """Generated launchers in one ``~/.local/bin`` that run the engine."""

    ok: tuple[str, ...] = ()
    """Launchers whose engine path exists and is executable."""
    bare: tuple[str, ...] = ()
    """Launchers written before issue #145: a bare ``hammunition``."""
    broken: tuple[tuple[str, str], ...] = ()
    """(launcher, engine path) where the engine is gone or not executable."""


def survey_engine_launchers(bin_dir: Path) -> EngineLaunchers:
    """Sort the engine-calling launchers in ``bin_dir`` by whether they work.

    Only files carrying the generated marker are ours; the engine's own link
    and anything else in the directory are not read.
    """
    ok: list[str] = []
    bare: list[str] = []
    broken: list[tuple[str, str]] = []
    try:
        candidates = sorted(bin_dir.iterdir())
    except OSError:
        return EngineLaunchers()
    for path in candidates:
        if path.is_symlink() or not path.is_file():
            continue
        try:
            with path.open(encoding="utf-8", errors="replace") as handle:
                head = handle.read(64 * 1024)
        except OSError:
            continue
        if not any(line.startswith(MARKER) for line in head.splitlines()[:3]):
            continue
        called = engine_call(head)
        if called is None:
            continue
        if "/" not in called:
            bare.append(str(path))
        elif Path(called).is_file() and os.access(called, os.X_OK):
            ok.append(str(path))
        else:
            broken.append((str(path), called))
    return EngineLaunchers(ok=tuple(ok), bare=tuple(bare), broken=tuple(broken))
