# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Launcher generation — wrappers and desktop entries from manifest data.

M3's last named requirement: 14 units install software an operator then
cannot start — Java jars, run-in-place trees, programs that need a working
directory or a service endpoint argument. AHRL answers with generated shell
scripts and a hand-maintained xdg menu tree; here both are generated from the
manifest's ``launchers`` block, per D-036.

Two artifacts per launcher, both per-user and both unprivileged:

- **A wrapper script** in ``~/.local/bin`` — sets the working directory when
  the manifest declares one, substitutes ``{endpoint:NAME}`` from the
  manifest's ``service_endpoints`` (D-013's repointable-backend rule: the URL
  lives in the catalog, not in the launcher), and runs the exec line. The
  exec line is shell, deliberately: ais-catcher's launcher backgrounds a
  browser against its own web map, and pretending that is an argv would just
  move the shell somewhere less reviewable. The line comes from the catalog —
  reviewed data, the opposite of piped remote content.
- **A desktop entry** in ``~/.local/share/applications`` so the DE's menu
  shows it. ``Categories=`` starts from the freedesktop-registered
  ``HamRadio`` plus a mapping from the manifest's own categories, which is
  D-036's curation seed — the same tags, never a second taxonomy. Every entry
  carries ``X-Hammunition-Package`` so a later uninstall or menu build can
  find its own work.

The per-DE curated submenu layer (Xfce ``.menu`` files, GNOME app-folders,
COSMIC) sits on top of these entries and is measured before it is built —
D-036 names the three mechanisms and what is still unknown about each.
"""

from __future__ import annotations

import os
import re
from functools import partial
from pathlib import Path

from hammunition.backends.base import Action, BackendError
from hammunition.manifest.schema import ENDPOINT_REF, Launcher, PackageManifest

__all__ = ["desktop_entry", "launcher_steps", "resolve_endpoints", "wrapper_body"]

#: Catalog category -> additional freedesktop menu categories. Every entry
#: also gets HamRadio (registered in the freedesktop menu spec) except the
#: plainly-not-radio ones. Presentation policy, not install logic — the
#: catalog stays the single source of what a package *is*.
XDG_CATEGORIES: dict[str, str] = {
    "antenna": "HamRadio;Engineering",
    "contest": "HamRadio",
    "cw": "HamRadio;Education",
    "digital-modes": "HamRadio;AudioVideo",
    "dmr": "HamRadio;Audio",
    "electronics": "Electronics;Engineering",
    "emcomm": "HamRadio;Network",
    "hf-propagation": "HamRadio;Science",
    "listening": "HamRadio;Audio",
    "logging": "HamRadio;Database",
    "mesh": "Network",
    "nbems": "HamRadio;Network",
    "packet": "HamRadio;Network",
    "programmer": "Electronics;Development",
    "radio-programming": "HamRadio;Settings",
    "rf-research": "Network;Security",
    "rf-security": "Network;Security",
    "rfid": "Security",
    "rig-control": "HamRadio;Settings",
    "satellite": "HamRadio;Science",
    "sdr": "HamRadio;AudioVideo",
    "station": "HamRadio",
    "timing": "HamRadio;Utility",
    "tracking": "HamRadio;Geography",
    "training": "HamRadio;Education",
    "workstation": "Utility",
}


def resolve_endpoints(manifest: PackageManifest, exec_line: str) -> str:
    """Substitute ``{endpoint:NAME}`` with the endpoint's default URL.

    The schema guarantees every reference is declared; an undeclared one here
    means the objects diverged from their manifest and failing loudly beats
    generating a launcher that starts the wrong backend.
    """
    endpoints = {e.name: e.default_url for e in manifest.service_endpoints}

    def substitute(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in endpoints:
            raise BackendError(
                f"{manifest.name}: launcher references endpoint {name!r} which is "
                f"not declared — the manifest and its objects have diverged"
            )
        return endpoints[name]

    return ENDPOINT_REF.sub(substitute, exec_line)


def wrapper_body(manifest: PackageManifest, launcher: Launcher) -> str:
    lines = ["#!/bin/sh", f"# generated by hammunition for {manifest.name}"]
    if launcher.working_directory:
        lines.append(f"cd {launcher.working_directory!r} || exit 1")
    lines.append(resolve_endpoints(manifest, launcher.exec))
    return "\n".join(lines) + "\n"


def desktop_entry(manifest: PackageManifest, launcher: Launcher, wrapper: Path) -> str:
    categories = sorted(
        {
            part
            for category in manifest.categories
            for part in XDG_CATEGORIES.get(category, "HamRadio").split(";")
        }
    )
    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        f"Name={launcher.name}\n"
        f"Comment={manifest.summary}\n"
        f"Exec={wrapper}\n"
        f"Terminal={'true' if launcher.terminal else 'false'}\n"
        f"Categories={';'.join(categories)};\n"
        f"X-Hammunition-Package={manifest.name}\n"
    )


def write_launcher(path: Path, body: str, mode: int) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    os.chmod(path, mode)
    return f"wrote {path}"


def launcher_steps(
    manifest: PackageManifest,
    *,
    bin_dir: Path,
    applications_dir: Path,
) -> list[Action]:
    """Both artifacts for every launcher the manifest declares."""
    steps: list[Action] = []
    for launcher in manifest.launchers:
        wrapper = bin_dir / launcher.name
        steps.append(
            Action(
                kind="wrapper",
                description=f"Generate the {launcher.name} launcher for {manifest.name}",
                detail=f"{wrapper}"
                + (f", runs in {launcher.working_directory}" if launcher.working_directory else ""),
                perform=partial(write_launcher, wrapper, wrapper_body(manifest, launcher), 0o755),
            )
        )
        entry = applications_dir / f"hammunition-{launcher.name}.desktop"
        steps.append(
            Action(
                kind="desktop-entry",
                description=f"Add {launcher.name} to the desktop menus",
                detail=str(entry),
                perform=partial(
                    write_launcher, entry, desktop_entry(manifest, launcher, wrapper), 0o644
                ),
            )
        )
    return steps
