# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Curated desktop menus, generated from the catalog's own categories. D-036.

Two of the three measured mechanisms (the D-036 addendum has the
measurements; COSMIC waits for a Pop!_OS machine to exist):

- **The freedesktop menu spec** — Xfce and every menu-spec DE. A merged
  ``.menu`` file in the user's ``menus`` config builds a "Ham Radio" tree
  with one submenu per catalog category, each including by the
  ``X-Hammunition-<category>`` marker the launcher generator writes into
  every desktop entry. One taxonomy: the tree is rendered from
  ``catalog/categories.yaml``, the same vocabulary the manifests use.
- **GNOME app-folders** — GNOME Shell renders no nested menus; its folders
  live in gsettings. One "Ham Radio" folder declaring
  ``categories=['HamRadio']`` populates itself from the same entries with
  no app list to maintain. Applied as commands, because dconf needs the
  operator's session bus: run ``hammunition menus apply`` in a desktop
  session, and over SSH it fails loudly instead of pretending.

Everything here is per-user and unprivileged — the property both measured
mechanisms share and the launcher artifacts already have.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from functools import partial
from pathlib import Path
from xml.sax.saxutils import escape

from hammunition.backends.base import Action, Command

__all__ = [
    "Category",
    "MenuPaths",
    "gnome_commands",
    "menu_steps",
    "render_directory",
    "render_menu",
]

MENU_NAME = "Ham Radio"
GNOME_FOLDER = "HamRadio"


@dataclass(frozen=True)
class Category:
    """One entry of the catalog vocabulary, as the menu needs it."""

    name: str
    summary: str


@dataclass(frozen=True)
class MenuPaths:
    """Where the per-user artifacts land."""

    menus_dir: Path
    """``~/.config/menus/<prefix>applications-merged`` — the merge point."""

    directories_dir: Path
    """``~/.local/share/desktop-directories`` — the .directory entries."""


def render_menu(categories: list[Category]) -> str:
    """The merged ``.menu`` XML: one tree, one submenu per category."""
    submenus = "\n".join(
        f"""    <Menu>
      <Name>hammunition-{escape(c.name)}</Name>
      <Directory>hammunition-{escape(c.name)}.directory</Directory>
      <Include><Category>X-Hammunition-{escape(c.name)}</Category></Include>
    </Menu>"""
        for c in categories
    )
    return f"""<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
 "http://www.freedesktop.org/standards/menu-spec/menu-1.0.dtd">
<!-- generated by hammunition (D-036); regenerate with `hammunition menus apply` -->
<Menu>
  <Name>Applications</Name>
  <Menu>
    <Name>{MENU_NAME}</Name>
    <Directory>hammunition-hamradio.directory</Directory>
{submenus}
  </Menu>
</Menu>
"""


def render_directory(name: str, comment: str) -> str:
    return f"[Desktop Entry]\nType=Directory\nName={name}\nComment={comment}\nIcon=folder\n"


def _write(path: Path, body: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    os.chmod(path, 0o644)
    return f"wrote {path}"


def menu_steps(categories: list[Category], paths: MenuPaths, *, menu_prefix: str) -> list[Action]:
    """The file half — inert data any menu-spec DE picks up on next login.

    ``menu_prefix`` is the DE's ``$XDG_MENU_PREFIX`` (``xfce-`` on Xfce,
    empty on most others); the merged file must match the root menu's name
    or nothing merges, which is a silent nothing — hence it is a parameter,
    not a guess.
    """
    steps = [
        Action(
            kind="menu",
            description=f"Write the {MENU_NAME} menu tree ({len(categories)} categories)",
            detail=str(paths.menus_dir / f"{menu_prefix}applications-merged" / "hammunition.menu"),
            perform=partial(
                _write,
                paths.menus_dir / f"{menu_prefix}applications-merged" / "hammunition.menu",
                render_menu(categories),
            ),
        ),
        Action(
            kind="menu",
            description=f"Name the top-level {MENU_NAME} directory entry",
            detail=str(paths.directories_dir / "hammunition-hamradio.directory"),
            perform=partial(
                _write,
                paths.directories_dir / "hammunition-hamradio.directory",
                render_directory(MENU_NAME, "Amateur radio, SDR and RF tools from Hammunition"),
            ),
        ),
    ]
    for category in categories:
        target = paths.directories_dir / f"hammunition-{category.name}.directory"
        steps.append(
            Action(
                kind="menu",
                description=f"Name the {category.name} submenu",
                detail=str(target),
                perform=partial(
                    _write,
                    target,
                    render_directory(category.name.replace("-", " ").title(), category.summary),
                ),
            )
        )
    return steps


def gnome_commands() -> list[Command]:
    """The GNOME half — an app-folder populated by category, via gsettings.

    Needs the operator's session bus (dconf), so these are Commands the
    runner executes as the user: they succeed in a desktop session and fail
    loudly over bare SSH, which is the honest behaviour. Existing folders in
    ``folder-children`` are preserved by the read-modify-write script being
    avoided entirely: dconf list mutation without a shell means gsettings'
    own idempotent behaviour — setting the same folder twice is harmless,
    and the folder list append is done by the small python -c below, the
    one place argv cannot express "append to a list setting".
    """
    folder_path = f"/org/gnome/desktop/app-folders/folders/{GNOME_FOLDER}/"
    return [
        Command(
            argv=(
                "python3",
                "-c",
                (
                    "import subprocess, ast\n"
                    "current = subprocess.run(['gsettings','get',"
                    "'org.gnome.desktop.app-folders','folder-children'],"
                    "capture_output=True,text=True,check=True).stdout.strip()\n"
                    "value = ast.literal_eval(current.removeprefix('@as '))\n"
                    f"name = {GNOME_FOLDER!r}\n"
                    "if name not in value:\n"
                    "    value.append(name)\n"
                    "    subprocess.run(['gsettings','set',"
                    "'org.gnome.desktop.app-folders','folder-children',str(value)],check=True)\n"
                    "print('folder-children:', value)\n"
                ),
            ),
            description=f"Register the {GNOME_FOLDER} app-folder with GNOME (append, never replace)",
        ),
        Command(
            argv=(
                "gsettings",
                "set",
                f"org.gnome.desktop.app-folders.folder:{folder_path}",
                "name",
                MENU_NAME,
            ),
            description="Name the folder",
        ),
        Command(
            argv=(
                "gsettings",
                "set",
                f"org.gnome.desktop.app-folders.folder:{folder_path}",
                "categories",
                "['HamRadio']",
            ),
            description="Populate it by category — no app list to maintain",
        ),
    ]
