# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Device catalog tests.  D-020.

The invariant worth testing is the one about evidence. A wrong VID:PID produces
a udev rule that silently never matches, and an operator cannot tell that from a
bad cable — so the schema refuses an identifier with no provenance, and refuses
a device that has neither a confirmed identifier nor an honest statement of what
is unknown.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest
from pydantic import ValidationError

from hammunition.manifest.hardware import (
    CONTRADICTS_CONFIRMED,
    DeviceClass,
    DeviceManifest,
    HardwareDocumentation,
    UdevBinding,
    UsbId,
)
from hammunition.manifest.load import CatalogError, load_catalog, load_hardware
from hammunition.manifest.schema import ManifestError

HARDWARE = Path(__file__).resolve().parent.parent / "catalog" / "hardware"

#: A generation-date line at the start of a line, under any leading markup the
#: generators use: `**Generated:** ...`, `Generated 2026-.. from ...`,
#: `<!-- Generated by ... -->`, `# Generated: ...`.
GENERATED_LINE = re.compile(r"^[\s<!\-#*]*Generated\b")

DOCS = HardwareDocumentation(
    what_it_is="A software defined radio receiver used for wideband reception.",
    what_you_can_do_with_it="Receive and decode signals across a wide frequency range.",
    setup_steps="Plug it in, join plugdev, then log out and back in again.",
)


def device(**overrides: object) -> DeviceManifest:
    data: dict[str, object] = {
        "name": "example",
        "summary": "An example device",
        "vendor": "Example Ltd",
        "documentation": DOCS,
    }
    data.update(overrides)
    return DeviceManifest.model_validate(data)


CONFIRMED = UsbId(
    vendor="1d50",
    product="6089",
    description="HackRF One",
    evidence="Debian 13 /lib/udev/rules.d/60-libhackrf0.rules",
)


# ---------------------------------------------------------------------------
# No guessing
# ---------------------------------------------------------------------------


def test_a_device_may_not_be_silent_about_unknown_identifiers() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        device()


def test_stating_the_gap_is_enough() -> None:
    d = device(
        identification_gap="Not verified against hardware; run lsusb and record it.",
        gap_closure="maintainer_hardware",
    )
    assert d.usb_ids == []


def test_a_gap_must_say_who_can_close_it() -> None:
    """A gap nobody can close is a different work item from one lsusb settles.

    Every gap in the catalog once ended in "run lsusb and record it", including
    two devices no one on the project owns. Prose could not carry the
    difference; the field has to.
    """
    with pytest.raises((ManifestError, ValidationError)):
        device(identification_gap="No identifier confirmed against real hardware.")


def test_closure_without_a_gap_is_meaningless() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        device(usb_ids=[CONFIRMED], gap_closure="unverified_by_maintainer")


def test_closure_is_a_closed_set() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        device(
            identification_gap="No identifier confirmed against real hardware.",
            gap_closure="ask_around",
        )


def test_inheriting_a_class_is_enough() -> None:
    assert device(device_class="badgelife").device_class == "badgelife"


def test_usb_id_requires_evidence() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        UsbId(vendor="1d50", product="6089", description="HackRF One", evidence="")


def test_usb_id_rejects_malformed_hex() -> None:
    for vendor, product in (("1D50", "6089"), ("1d5", "6089"), ("1d50", "60890")):
        with pytest.raises((ManifestError, ValidationError)):
            UsbId(
                vendor=vendor,
                product=product,
                description="x",
                evidence="a udev rule shipped by Debian",
            )


def test_confirmed_may_not_contradict_its_own_evidence() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        UsbId(
            vendor="303a",
            product="1001",
            description="ESP32-S3 native USB",
            evidence="unconfirmed; not verified against hardware",
            confirmed=True,
        )


def test_supported_status_requires_a_confirmed_identifier() -> None:
    """D-018: do not claim what has not been tested."""
    with pytest.raises((ManifestError, ValidationError)):
        device(status="supported", identification_gap="Nobody has attached one.")


def test_supported_status_is_allowed_with_evidence() -> None:
    assert device(status="supported", usb_ids=[CONFIRMED]).status == "supported"


# ---------------------------------------------------------------------------
# Persistent naming
# ---------------------------------------------------------------------------


def test_multiple_ids_may_not_share_an_unsuffixed_symlink() -> None:
    """Two attached devices would race for the same /dev name."""
    second = UsbId(
        vendor="1d50",
        product="604b",
        description="HackRF Jawbreaker",
        evidence="Debian 13 /lib/udev/rules.d/60-libhackrf0.rules",
    )
    with pytest.raises((ManifestError, ValidationError)):
        device(
            usb_ids=[CONFIRMED, second],
            udev=UdevBinding(symlink="hackrf", serial_suffix=False),
        )


def test_udev_mode_must_be_octal() -> None:
    for mode in ("660", "0999", "rw-rw----"):
        with pytest.raises((ManifestError, ValidationError)):
            UdevBinding(symlink="thing", mode=mode)


# ---------------------------------------------------------------------------
# The real catalog
# ---------------------------------------------------------------------------


def test_hardware_catalog_loads() -> None:
    classes, devices = load_hardware(HARDWARE)
    assert "badgelife" in classes
    assert {"hackrf-one", "rtl-sdr", "clip-boy", "proxmark3"} <= set(devices)


def test_every_class_reference_resolves() -> None:
    classes, devices = load_hardware(HARDWARE)
    for device_entry in devices.values():
        if device_entry.device_class:
            assert device_entry.device_class in classes


def test_dangling_class_reference_fails_loudly(tmp_path: Path) -> None:
    (tmp_path / "orphan.yaml").write_text(
        "kind: device\n"
        "name: orphan\n"
        "summary: references a class that is not there\n"
        "vendor: nobody\n"
        "device_class: does-not-exist\n"
        "documentation:\n"
        "  what_it_is: A device entry used only to exercise validation here.\n"
        "  what_you_can_do_with_it: Nothing; it exists to be rejected by the loader.\n"
        "  setup_steps: There are none, because this device does not exist.\n"
    )
    with pytest.raises(CatalogError) as excinfo:
        load_hardware(tmp_path)
    assert "does-not-exist" in str(excinfo.value)


def test_unconfirmed_identifiers_are_visibly_unconfirmed() -> None:
    """An identifier taken from documentation must not read as one from hardware.

    This test has now been pointed at three different worked examples and lost
    two of them, which is the healthy direction. It first named badgelife's
    Espressif 303a:1001; two captures on 2026-08-26 confirmed that. It then
    named 1a86:55d4, which D-030 moved out of `usb_ids` entirely — a class may
    no longer carry an unconfirmed identifier at all, so the example survives in
    `rejected_ids` where it can generate nothing.

    What is left is the property rather than any one example, checked across
    every device: an unconfirmed identifier must read as unconfirmed. There is
    no assertion that any exist. An empty catalog-wide list is the goal state,
    not a reason to keep something around to satisfy a test.
    """
    classes, devices = load_hardware(HARDWARE)
    entries: list[UsbId] = []
    for holder in (*classes.values(), *devices.values()):
        entries += [i for i in holder.usb_ids if not i.confirmed]
    for usb in entries:
        assert CONTRADICTS_CONFIRMED.search(usb.evidence), (
            f"{usb} is unconfirmed but its evidence does not say so, so a reader "
            f"cannot tell it apart from one captured against hardware"
        )


def test_the_espressif_identifier_is_confirmed_by_three_captures() -> None:
    """Three unrelated products, one identifier -- the empirical basis for D-028.

    Clip-Boy, Minino and the ESP32-S3 inside a Free-WiLi 2 all report 303a:1001
    with the product string "USB JTAG/serial debug unit". Not an argument from an
    esptool constant any more; three observations of three different boards.
    """
    classes, devices = load_hardware(HARDWARE)
    holders = [
        classes["badgelife"],
        devices["clip-boy"],
        devices["minino"],
        devices["free-wili-2"],
    ]
    for holder in holders:
        usb = next((i for i in holder.usb_ids if str(i) == "303a:1001"), None)
        assert usb is not None, f"{holder.name} should carry 303a:1001"
        assert usb.confirmed, f"{holder.name}: captured against hardware"
        assert usb.ambiguity is not None, (
            f"{holder.name}: the same pair on three unrelated products is ambiguous"
        )


def test_shared_identifier_claims_are_mutual() -> None:
    """`also_used_by` is hand-maintained, so it drifts unless something checks.

    If clip-boy says the pair is shared with minino, minino must say the same. A
    one-sided claim means somebody added a device and updated one file, and the
    reader of the other file is told the identifier is theirs alone.
    """
    classes, devices = load_hardware(HARDWARE)
    holders = {e.name: e.usb_ids for e in (*classes.values(), *devices.values())}
    for name, usb_ids in holders.items():
        for usb in usb_ids:
            if usb.ambiguity is None:
                continue
            for other in usb.ambiguity.also_used_by:
                if other not in holders:
                    continue  # free prose, e.g. "every ESP32-S3 board"
                theirs = next((i for i in holders[other] if str(i) == str(usb)), None)
                assert theirs is not None, (
                    f"{name} says {other} shares {usb}, but {other} does not carry it"
                )
                assert theirs.ambiguity is not None, (
                    f"{name} says {other} shares {usb}, but {other} does not declare it shared"
                )


def test_devices_without_confirmed_ids_are_not_marked_supported() -> None:
    _, devices = load_hardware(HARDWARE)
    for name, entry in devices.items():
        if entry.status == "supported":
            assert any(i.confirmed for i in entry.usb_ids), (
                f"{name} claims support with no confirmed USB identifier"
            )


def test_the_maintainers_kit_is_represented() -> None:
    """Every device named in CLAUDE.md's hardware context has an entry."""
    _, devices = load_hardware(HARDWARE)
    for name in (
        "hackrf-one",
        "catsniffer-v3",
        "free-wili-2",
        "minino",
        "clip-boy",
        "proxmark3",
        "meshtastic",
        "uconsole",
        "krakensdr",
    ):
        assert name in devices, f"{name} is in the maintainer's kit but has no entry"


def test_every_catalogued_gap_declares_its_closure() -> None:
    """The generated gap report groups by closure, so an unset one hides a device."""
    _, devices = load_hardware(HARDWARE)
    for name, entry in devices.items():
        assert bool(entry.identification_gap) == bool(entry.gap_closure), name


def test_devices_the_maintainer_does_not_own_do_not_ask_for_an_lsusb() -> None:
    """LimeSDR and PlutoSDR are not on the bench; the entries must not imply they are.

    Both once told the reader to attach hardware that does not exist here, which
    reads as a task for the maintainer and is a task for a contributor.
    """
    _, devices = load_hardware(HARDWARE)
    for name in ("limesdr", "plutosdr"):
        assert devices[name].gap_closure == "unverified_by_maintainer", name


def test_every_package_a_device_names_has_a_manifest() -> None:
    """The profile cross-check's blind spot, found by looking for it.

    `load_profiles` catches a profile naming an undefined package. Nothing
    caught a *device* doing it, and 21 were dangling -- the SoapySDR modules,
    the vendor host tools, the Meshtastic clients. A device entry saying
    "these packages make it useful" is the same kind of promise a profile makes.
    """
    packages = load_catalog(HARDWARE.parent / "packages")
    classes, devices = load_hardware(HARDWARE)
    for entry in (*classes.values(), *devices.values()):
        referenced = set(entry.packages)
        for firmware in entry.firmware:
            referenced |= set(firmware.packages)
        missing = sorted(referenced - set(packages))
        assert not missing, f"{entry.name} names packages with no manifest: {missing}"


# ---------------------------------------------------------------------------
# Two axes: is it supported, and has anyone here run it
# ---------------------------------------------------------------------------


VERIFICATION = {
    "date": "2026-08-26",
    "by": "someone",
    "distro": "parrot rolling",
    "what_was_tested": "Enumerated, udev rule matched, rtl_test found the tuner.",
}


def test_supported_and_verified_are_independent() -> None:
    """usrp is the case: identifiers from Debian's own rule, nobody here owns one."""
    _, devices = load_hardware(HARDWARE)
    usrp = devices["usrp"]
    assert usrp.status == "supported"
    assert usrp.maintainer_verified is None


def test_a_verification_needs_evidence_not_a_boolean() -> None:
    """A bare true would be the same defect one level down."""
    with pytest.raises((ManifestError, ValidationError)):
        device(
            usb_ids=[CONFIRMED],
            maintainer_verified={**VERIFICATION, "what_was_tested": "works"},
        )


def test_verified_may_not_also_be_unverified_by_maintainer() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        device(
            identification_gap="No identifier confirmed against real hardware.",
            gap_closure="unverified_by_maintainer",
            maintainer_verified=VERIFICATION,
        )


def test_planned_hardware_cannot_have_been_run() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        device(usb_ids=[CONFIRMED], status="planned", maintainer_verified=VERIFICATION)


def test_a_verification_is_accepted_with_evidence() -> None:
    entry = device(usb_ids=[CONFIRMED], status="supported", maintainer_verified=VERIFICATION)
    assert entry.maintainer_verified is not None
    assert entry.maintainer_verified.distro == "parrot rolling"


def test_no_device_claims_verification_it_does_not_have() -> None:
    """The claim this project is most likely to make carelessly, so it is asserted."""
    _, devices = load_hardware(HARDWARE)
    for name, entry in devices.items():
        if entry.maintainer_verified is not None:
            assert entry.status != "planned", name
            assert entry.gap_closure != "unverified_by_maintainer", name


# ---------------------------------------------------------------------------
# D-028 — an identifier that names a chip may not name a /dev node
# ---------------------------------------------------------------------------


CP2102 = UsbId(
    vendor="10c4",
    product="ea60",
    description="Silicon Labs CP2102 UART bridge",
    evidence="Debian 13 usb.ids and modules.alias",
    ambiguity={  # type: ignore[arg-type]
        "basis": "kernel_generic_driver",
        "evidence": "Debian 13 modules.alias binds 10c4:ea60 to cp210x, a generic bridge driver.",
    },
)


def test_a_symlink_on_a_bridge_chip_is_refused() -> None:
    """The failure this exists for: /dev/marauder on every CP2102 adapter.

    A rig-control cable, a GPS puck and a Meshtastic node all use CP2102s. A
    rule matching the chip claims whichever of them enumerates, and the operator
    sees a symlink pointing at the wrong device with no error anywhere.
    """
    with pytest.raises((ManifestError, ValidationError)):
        device(
            usb_ids=[CP2102],
            udev={"symlink": "marauder"},
        )


def test_a_product_match_makes_it_safe() -> None:
    entry = device(
        usb_ids=[CP2102.model_copy(update={"product_string": "ESP32 Marauder"})],
        udev={"symlink": "marauder", "match_product": "ESP32 Marauder"},
    )
    assert entry.udev is not None
    assert entry.udev.match_product == "ESP32 Marauder"


def test_a_product_match_nobody_has_read_is_refused() -> None:
    """The mirror image of a guessed VID:PID, and just as silent.

    `hackrf-one` shipped `match_product: HackRF One` on the strength of nothing
    — the maintainer owns a Pro, not a One. A product string that is one
    character out produces a rule that never matches, which looks exactly like
    a bad cable. So the string has to be recorded on the identifier it was read
    from, with the capture or the upstream source in its evidence.
    """
    with pytest.raises((ManifestError, ValidationError)):
        device(
            usb_ids=[CP2102],
            udev={"symlink": "marauder", "match_product": "ESP32 Marauder"},
        )


def test_a_serial_match_makes_it_safe() -> None:
    entry = device(
        usb_ids=[CP2102],
        udev={"symlink": "rig-991a", "match_serial": "A50285BI"},
    )
    assert entry.udev is not None


def test_an_unambiguous_identifier_needs_no_extra_match() -> None:
    """pn533_usb is a device driver, not a bridge driver. The nfc symlink stands."""
    entry = device(usb_ids=[CONFIRMED], udev={"symlink": "hackrf"})
    assert entry.udev is not None


def test_the_rule_applies_to_classes_too() -> None:
    """badgelife is where this actually bit, and a class is not exempt."""
    with pytest.raises((ManifestError, ValidationError)):
        DeviceClass.model_validate(
            {
                "kind": "class",
                "name": "badges",
                "summary": "Conference badges of every kind",
                "usb_ids": [CP2102.model_dump()],
                "udev": {"symlink": "badge"},
                "documentation": DOCS.model_dump(),
            }
        )


def test_badgelife_emits_no_symlink() -> None:
    """Regression. Every identifier it carries is a bridge chip."""
    classes, _ = load_hardware(HARDWARE)
    badgelife = classes["badgelife"]
    assert badgelife.udev is None, (
        "badgelife pins a symlink to bridge-chip identifiers; a CP2102 rig cable would claim it"
    )
    assert all(i.ambiguity for i in badgelife.usb_ids), (
        "every identifier in badgelife is a bridge chip and must say so"
    )


def test_no_catalogued_symlink_rests_on_an_ambiguous_identifier() -> None:
    """The property, asserted across the whole catalog rather than per entry."""
    classes, devices = load_hardware(HARDWARE)
    for entry in (*classes.values(), *devices.values()):
        udev = entry.udev
        if udev and not (udev.match_product or udev.match_serial):
            offenders = [str(i) for i in entry.usb_ids if i.ambiguity]
            assert not offenders, f"{entry.name}: /dev/{udev.symlink} rests on {offenders}"


def test_an_identifier_on_the_ambiguity_list_must_say_so(tmp_path: Path) -> None:
    """The list is only load-bearing if something checks against it.

    An unmarked identifier passes the symlink check silently, because that check
    keys off the `ambiguity` block. So the loader cross-checks the generated
    list, and this asserts the loader actually does it rather than trusting it.
    """
    (tmp_path / "devices").mkdir()
    (tmp_path / "ambiguous-ids.yaml").write_text(
        "kind: ambiguity-list\n"
        "identifiers:\n"
        '  - id: "10c4:ea60"\n'
        "    basis: kernel_generic_driver\n"
    )
    (tmp_path / "devices" / "thing.yaml").write_text(
        "kind: device\n"
        "name: thing\n"
        "summary: A thing with a bridge chip\n"
        "vendor: Example\n"
        "usb_ids:\n"
        '  - vendor: "10c4"\n'
        '    product: "ea60"\n'
        "    description: A CP2102 bridge\n"
        "    evidence: Debian 13 usb.ids and modules.alias\n"
        "documentation:\n"
        "  what_it_is: A device used for testing this loader behaviour.\n"
        "  what_you_can_do_with_it: Nothing at all, it is a fixture.\n"
        "  setup_steps: Plug it in, join plugdev, log out and back in again.\n"
    )
    with pytest.raises(CatalogError) as caught:
        load_hardware(tmp_path)
    assert "names a chip" in str(caught.value)


def test_the_real_catalog_marks_every_ambiguous_identifier() -> None:
    """Regression for badgelife, asserted as a property of the whole catalog."""
    load_hardware(HARDWARE)  # raises if any identifier is on the list unmarked


def test_evidence_recording_its_own_history_is_not_a_contradiction() -> None:
    """The naive substring check rejected exactly the prose a capture should write.

    "Previously carried as unconfirmed" is history, and a check that punishes
    the most informative sentence in an entry teaches people to write less.
    """
    usb = UsbId(
        vendor="303a",
        product="1001",
        description="ESP32-S3 native USB",
        evidence=(
            "Confirmed by capture on two devices 2026-08-26. Previously carried "
            "as unconfirmed on the strength of an esptool constant."
        ),
        confirmed=True,
    )
    assert usb.confirmed


@pytest.mark.parametrize(
    "evidence",
    [
        "This pair is unconfirmed and was read from a forum post somewhere.",
        "Widely reported but not confirmed against any hardware we have here.",
        "Taken from vendor documentation; unconfirmed here and worth checking.",
        "Plausible for this board but not verified against real hardware yet.",
    ],
)
def test_evidence_that_really_does_contradict_is_still_caught(evidence: str) -> None:
    with pytest.raises((ManifestError, ValidationError)):
        UsbId(
            vendor="303a",
            product="1001",
            description="ESP32-S3 native USB",
            evidence=evidence,
            confirmed=True,
        )


def test_a_capture_makes_a_device_verified_without_making_it_run() -> None:
    """D-027 under real data: four devices enumerated, none exercised."""
    _, devices = load_hardware(HARDWARE)
    verified = {n: d for n, d in devices.items() if d.maintainer_verified}
    assert verified, "no device records a maintainer verification"
    for name, entry in verified.items():
        assert entry.maintainer_verified is not None
        assert entry.gap_closure != "unverified_by_maintainer", name


def test_devices_sharing_an_identifier_both_declare_it() -> None:
    """hackrf-one and hackrf-pro share 1d50:6089; neither may claim it alone."""
    _, devices = load_hardware(HARDWARE)
    for name in ("hackrf-one", "hackrf-pro"):
        entry = devices[name]
        shared = [i for i in entry.usb_ids if str(i) == "1d50:6089"]
        assert shared, f"{name} should carry 1d50:6089"
        assert shared[0].ambiguity is not None, f"{name} must declare the pair shared"
        assert entry.udev is not None and entry.udev.match_product, (
            f"{name} pins a symlink to a shared identifier and needs match_product"
        )


# ---------------------------------------------------------------------------
# Evidence flows upward: a class carries only what a device confirmed.  D-030
# ---------------------------------------------------------------------------


def test_a_class_refuses_an_unconfirmed_identifier() -> None:
    """A guess in a class is a guess with a distribution mechanism.

    Twice `badgelife` handed a device identifiers that could not match it: the
    CatSniffer v3 turned out to be a bare RP2040, and the C5 Wardriver a CH343
    bridge rather than the native ESP32 USB the class predicted. Both misses
    came from the class predicting downward.
    """
    with pytest.raises((ManifestError, ValidationError)):
        DeviceClass.model_validate(
            {
                "kind": "class",
                "name": "badges",
                "summary": "Conference badges of every kind",
                "usb_ids": [
                    {
                        "vendor": "1a86",
                        "product": "55d4",
                        "description": "WCH CH9102 UART bridge",
                        "evidence": "Widely reported for the CH9102F; no capture anywhere.",
                        "confirmed": False,
                    }
                ],
                "documentation": DOCS.model_dump(),
            }
        )


def test_a_rejected_identifier_keeps_the_lesson_without_the_rule() -> None:
    cls = DeviceClass.model_validate(
        {
            "kind": "class",
            "name": "badges",
            "summary": "Conference badges of every kind",
            "usb_ids": [CP2102.model_dump()],
            "rejected_ids": [
                {
                    "vendor": "1a86",
                    "product": "55d4",
                    "description": "WCH CH9102 UART bridge",
                    "assumed_to_be": "What a CH343-family board would present.",
                    "why_rejected": (
                        "A C5 Wardriver was captured on 2026-08-26 and presented "
                        "1a86:55d3. One digit out."
                    ),
                }
            ],
            "documentation": DOCS.model_dump(),
        }
    )
    assert [str(i) for i in cls.usb_ids] == ["10c4:ea60"]
    assert [str(i) for i in cls.rejected_ids] == ["1a86:55d4"]


def test_no_catalogued_class_carries_an_unconfirmed_identifier() -> None:
    classes, _ = load_hardware(HARDWARE)
    for cls in classes.values():
        assert all(i.confirmed for i in cls.usb_ids), cls.name


def test_the_ch9102_lesson_survives_in_badgelife() -> None:
    """Kept as the worked example, where it cannot generate or propagate a rule."""
    classes, _ = load_hardware(HARDWARE)
    rejected = {str(i) for i in classes["badgelife"].rejected_ids}
    assert "1a86:55d4" in rejected


# ---------------------------------------------------------------------------
# Composite devices are a named shape, not a paragraph
# ---------------------------------------------------------------------------


def test_composite_requires_more_than_one_identifier() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        device(usb_ids=[CONFIRMED], composite=True)


def test_composite_requires_every_interface_to_say_what_it_is() -> None:
    """The point of declaring composite is answering 'which one is the probe'."""
    with pytest.raises((ManifestError, ValidationError)):
        device(
            usb_ids=[CONFIRMED, CONFIRMED.model_copy(update={"product": "604b"})],
            composite=True,
        )


def test_a_mapped_composite_is_accepted() -> None:
    entry = device(
        usb_ids=[
            CONFIRMED.model_copy(update={"node_kind": "libusb"}),
            CONFIRMED.model_copy(update={"product": "604b", "node_kind": "serial"}),
        ],
        composite=True,
    )
    assert entry.composite


def test_free_wili_is_the_composite_in_the_catalog() -> None:
    _, devices = load_hardware(HARDWARE)
    fw = devices["free-wili-2"]
    assert fw.composite
    assert len(fw.usb_ids) == 6
    assert all(i.node_kind is not None for i in fw.usb_ids)


# ---------------------------------------------------------------------------
# What /dev/serial/by-id/ does and does not settle
# ---------------------------------------------------------------------------


def test_only_serial_interfaces_reach_by_id() -> None:
    assert CONFIRMED.model_copy(update={"node_kind": "serial"}).by_id_reachable
    assert not CONFIRMED.model_copy(update={"node_kind": "libusb"}).by_id_reachable
    assert not CONFIRMED.model_copy(update={"node_kind": "storage"}).by_id_reachable


def test_a_serial_device_with_no_serial_collides_in_by_id_too() -> None:
    """The Proxmark3 case, and the reason the symlink plan was not simply retired.

    by-id composes its path from manufacturer, product and serial. A device
    supplying no serial collides there exactly as a naive symlink would, so
    neither mechanism separates two of them and only by-path — which is
    topology, and moves when the cable moves — does.
    """
    pm = UsbId(
        vendor="2d2d",
        product="504d",
        description="Proxmark3 in normal operating mode",
        evidence="lsusb 2026-08-26: manufacturer=proxmark.org, no product string, no serial.",
        node_kind="serial",
        reports_serial=False,
    )
    assert pm.by_id_reachable
    assert pm.by_id_distinguishes_units is False


def test_the_proxmark_is_still_the_catalogs_counter_example() -> None:
    _, devices = load_hardware(HARDWARE)
    pm = devices["proxmark3"].usb_ids[0]
    assert pm.node_kind == "serial"
    assert pm.reports_serial is False
    assert devices["proxmark3"].udev is None


def test_ports_are_named_completely_or_not_at_all() -> None:
    """A partial map reads as a complete one."""
    with pytest.raises((ManifestError, ValidationError)):
        UsbId(
            vendor="093c",
            product="2059",
            description="Free-WiLi 2 main interface",
            evidence="lsusb against real hardware 2026-08-26",
            node_kind="serial",
            ports=4,
            port_roles=["console"],
        )


def test_only_serial_interfaces_multiplex_ports() -> None:
    with pytest.raises((ManifestError, ValidationError)):
        UsbId(
            vendor="093c",
            product="205f",
            description="Mass storage interface",
            evidence="lsusb against real hardware 2026-08-26",
            node_kind="storage",
            ports=3,
        )


def test_every_symlink_in_the_catalog_is_outside_by_ids_reach() -> None:
    """The accounting's headline, asserted rather than left to the generator.

    Not a design rule — a device that by-id already names could still earn a
    symlink for an operator-chosen role name. It is a finding: every symlink
    written so far is on a libusb device systemd's serial rule never sees, so
    the two mechanisms have not overlapped once. If that ever stops being true,
    the entry that broke it owes a reason beyond stability.
    """
    classes, devices = load_hardware(HARDWARE)
    for dev in devices.values():
        if dev.udev is None:
            continue
        ids = list(dev.usb_ids)
        if dev.device_class:
            ids += list(classes[dev.device_class].usb_ids)
        assert not any(i.by_id_reachable for i in ids if i.confirmed), dev.name


# ---------------------------------------------------------------------------
# The README's numbers are catalog data, so they are checked like catalog data
# ---------------------------------------------------------------------------


def test_the_readme_hardware_counts_match_the_catalog() -> None:
    """A hand-typed count is a claim, and this project tests its claims.

    The supported/run-here pair is on the front page because it is a stronger
    credibility signal than anything we could assert in prose — which makes it
    exactly the number that must not drift. CLAUDE.md already says a doc
    duplicating manifest data by hand is a defect; this is the cheapest way to
    keep one honest short of generating the README.
    """
    classes, devices = load_hardware(HARDWARE)
    confirmed = {
        (i.vendor, i.product)
        for holder in (*classes.values(), *devices.values())
        for i in holder.usb_ids
        if i.confirmed
    }
    readme = (HARDWARE.parent.parent / "README.md").read_text()
    expected = [
        f"{len(devices)} devices, {len(classes)} classes, "
        f"{len(confirmed)} confirmed USB identifiers",
        f"**{sum(1 for d in devices.values() if d.status == 'supported')}** / "
        f"**{sum(1 for d in devices.values() if d.maintainer_verified)}**",
    ]
    for claim in expected:
        assert claim in readme, f"README no longer says {claim!r}"


# ---------------------------------------------------------------------------
# The contribution ask is generated data too
# ---------------------------------------------------------------------------


def test_the_lora_issue_form_states_the_generated_numbers() -> None:
    """An ask that misstates its own scope wastes the contributor's time.

    The LoRa form tells people which boards are worth capturing and which are
    provably not. Both halves come from `docs/reference/lora-inventory.md`, and
    a form quoting a stale count would send somebody to plug in a board whose
    answer we already have three times over. So the numbers are read out of the
    generated document rather than trusted to match it.
    """
    import re

    root = HARDWARE.parent.parent
    inventory = (root / "docs" / "reference" / "lora-inventory.md").read_text()
    form = (root / ".github" / "ISSUE_TEMPLATE" / "lora-product-string.yml").read_text()

    boards = re.search(r"\*\*Board definitions read:\*\* (\d+)", inventory)
    ids = re.search(r"\*\*Distinct USB identifiers:\*\* (\d+)", inventory)
    askable = re.search(r"\*\*(\d+) of the (\d+) board definitions", inventory)
    assert boards and ids and askable, "lora-inventory.md no longer states its counts"

    assert f"{boards.group(1)} board" in form
    assert f"{ids.group(1)} distinct" in form
    assert f"{askable.group(1)} of the {askable.group(2)} boards" in form
    # The exclusion is the part most likely to rot back into a blanket ask.
    assert "303a:1001" in form
    assert askable.group(2) == boards.group(1)


# ---------------------------------------------------------------------------
# Citations of distribution rules are checked against the sweep.  D-031
# ---------------------------------------------------------------------------


def test_every_rule_citation_is_supported_by_the_sweep() -> None:
    """The gap that let `dfu-util disables 0483:df11` ship.

    The commit-claims hook catches a message describing work a commit does not
    contain. Nothing caught reading a sweep row and believing it — a conclusion
    drawn from a column, with the file never opened. This is that check, and it
    runs in the suite rather than only in CI so it can be falsified locally.

    Skipped without the probe rather than passed: the sweep output is gitignored
    measurement, so a fresh clone has none, and reporting "ok" there would be
    the same defect one level up.
    """
    import subprocess

    root = HARDWARE.parent.parent
    if not (root / "reference" / "probes" / "udev-debian-13.tsv").is_file():
        pytest.skip("no udev sweep output; run scripts/run-udev-sweep.sh")
    result = subprocess.run(
        [sys.executable, str(root / "scripts" / "check_rule_citations.py")],
        capture_output=True,
        text=True,
        cwd=root,
        check=False,
    )
    assert result.returncode == 0, result.stderr


def test_the_programmer_class_is_still_generated() -> None:
    """`Never hand-edit a generated file` (CLAUDE.md), enforced rather than asked.

    This is the first *device* file in the catalog produced by a script, and the
    risk that comes with that is somebody fixing one of 180 entries in place and
    losing it at the next regeneration. Re-running the generator must be a
    no-op; if it is not, either the file was edited or the sweep moved and the
    file is stale. Both are worth failing for.

    Skipped without the probe, which a fresh clone does not have — the sweep
    output is gitignored measurement.
    """
    import subprocess

    root = HARDWARE.parent.parent
    if not (root / "reference" / "probes" / "udev-debian-13.tsv").is_file():
        pytest.skip("no udev sweep output; run scripts/run-udev-sweep.sh")
    target = HARDWARE / "classes" / "programmer.yaml"
    before = target.read_text()
    result = subprocess.run(
        [sys.executable, str(root / "scripts" / "gen_programmer_class.py")],
        capture_output=True,
        text=True,
        cwd=root,
        check=False,
    )
    after = target.read_text()
    if before != after:
        target.write_text(before)
    assert result.returncode == 0, result.stderr

    def without_date(text: str) -> list[str]:
        """The date line changes daily and says nothing about content.

        Uses the shared pattern rather than a second literal: the other copy of
        this helper had drifted into matching nothing at all, and two
        hand-written variants of the same filter is how that happened.
        """
        return [ln for ln in text.splitlines() if not GENERATED_LINE.match(ln)]

    assert without_date(before) == without_date(after), (
        "catalog/hardware/classes/programmer.yaml differs from what the generator "
        "produces. Either it was hand-edited, or the sweep has moved and it is stale."
    )


@pytest.mark.parametrize(
    "script, output",
    [
        ("gen_hardware_gaps.py", "docs/reference/hardware-gaps.md"),
        ("gen_device_naming.py", "docs/reference/device-naming.md"),
    ],
)
def test_catalog_derived_reports_are_current(script: str, output: str) -> None:
    """A generated report that lags the catalog is a stale claim with a byline.

    hardware-gaps.md sat at "Devices in catalog: 21" while the catalog held 23
    -- nobody re-ran the generator when devices were added, nothing checked,
    and the README repeated the lagging number as fact. The programmer class
    already has this test; these two generators read nothing but the catalog,
    so unlike that one there is no probe to skip on: the check runs
    everywhere, and regeneration must be a no-op modulo the date line.
    """
    import subprocess

    root = HARDWARE.parent.parent
    target = root / output
    before = target.read_text()
    result = subprocess.run(
        [sys.executable, str(root / "scripts" / script)],
        capture_output=True,
        text=True,
        cwd=root,
        check=False,
    )
    after = target.read_text()
    if before != after:
        target.write_text(before)
    assert result.returncode == 0, result.stderr

    def without_date(text: str) -> list[str]:
        """Drop the generation-date line, whatever markup it wears.

        This was `ln.lstrip("<!-# ").startswith("Generated")`, which strips
        `<`, `!`, `-`, `#` and spaces but **not** `*` — and hardware-gaps.md
        writes the line as `**Generated:** <date>`. The filter therefore never
        matched, and the assertion passed only on days when both dates agreed.
        It went red the first time a job was slow enough to cross UTC midnight:
        the emulated arm64 container takes four minutes, regenerated on
        2026-08-29, and compared against a file stamped 2026-08-28.

        A filter that silently matches nothing is the exact shape CLAUDE.md
        names — a check quietly passing on the input it exists to handle — so
        the pattern is anchored and the two shapes in use are asserted below.
        """
        return [ln for ln in text.splitlines() if not GENERATED_LINE.match(ln)]

    assert GENERATED_LINE.match("**Generated:** 2026-08-29  "), "hardware-gaps.md's shape"
    assert GENERATED_LINE.match("Generated 2026-08-29 from `catalog/hardware/`."), (
        "device-naming.md's shape"
    )
    assert not GENERATED_LINE.match("| device | Generated | x |"), "must not eat content"

    assert without_date(before) == without_date(after), (
        f"{output} differs from what {script} produces. Either it was "
        f"hand-edited, or the catalog moved and the report is stale."
    )


# ---------------------------------------------------------------------------
# serial_suffix needs evidence, and "nobody checked" is a state (issue #9)
# ---------------------------------------------------------------------------


def _id(**overrides: object) -> UsbId:
    base: dict[str, object] = {
        "vendor": "1d50",
        "product": "6002",
        "description": "An example device",
        "evidence": "Debian 13 /lib/udev/rules.d/40-example.rules",
        "confirmed": True,
        "node_kind": "libusb",
    }
    base.update(overrides)
    return UsbId(**base)  # type: ignore[arg-type]


def _device(**overrides: object) -> DeviceManifest:
    overrides.setdefault("usb_ids", [_id()])
    return device(**overrides)


def test_serial_suffix_without_evidence_is_refused() -> None:
    """The cited udev rules attest *identifiers*, not descriptor strings. An
    identifier in a rule is not evidence the device fills in iSerial, and a
    suffix with nothing to append produces a broken symlink — the proxmark3
    failure, which used to be armed by default for every device."""
    with pytest.raises((ManifestError, ValidationError), match="reports_serial"):
        _device(udev={"symlink": "example", "serial_suffix": True, "group": "plugdev"})


def test_serial_suffix_with_a_capture_behind_it_is_accepted() -> None:
    device = _device(
        usb_ids=[_id(reports_serial=True, evidence="lsusb against real hardware 2026-08-28")],
        udev={"symlink": "example", "serial_suffix": True, "group": "plugdev"},
    )
    assert device.udev is not None
    assert device.udev.serial_suffix is True


def test_nobody_checked_is_a_representable_state() -> None:
    """The third state is the point. `true` and `false` are both claims; leaving
    it unset says nobody has plugged one in, which is the truth for every device
    in this catalog that is not owned."""
    device = _device(udev={"symlink": "example", "group": "plugdev"})
    assert device.udev is not None
    assert device.udev.serial_suffix is None


def test_the_catalog_claims_a_suffix_only_where_a_capture_backs_it() -> None:
    """The real catalog, not a fixture. Three devices and one class claimed a
    suffix on the strength of a Debian rule that attests no such thing."""
    classes, devices = load_hardware(HARDWARE)
    for name, entry in [*devices.items(), *classes.items()]:
        if entry.udev is None or entry.udev.serial_suffix is not True:
            continue
        assert any(i.reports_serial is True for i in entry.usb_ids if i.confirmed), (
            f"{name} claims serial_suffix with no confirmed reports_serial evidence"
        )
