# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""The Copernicus tile list and pins are generated; nothing here reaches the network.

Every download, HEAD and text fetch is injected. Synthetic regions
(``atlantis/*``) with outlines near 0/0 only.
"""

from __future__ import annotations

import functools
import hashlib
import importlib.util
import sys
from collections.abc import Iterable
from datetime import date
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATOR = REPO_ROOT / "scripts" / "gen_copernicus_pins.py"

A = "Copernicus_DSM_COG_10_N00_00_E000_00_DEM"
B = "Copernicus_DSM_COG_10_N00_00_E001_00_DEM"
C = "Copernicus_DSM_COG_10_N01_00_E000_00_DEM"
BUCKET = "https://copernicus-dem-30m.s3.amazonaws.com"
BODY = b"elevation" * 100
MD5 = hashlib.md5(BODY, usedforsecurity=False).hexdigest()
#: oceania touches (0,0) and (0,1); lemuria touches (0,0) and (1,0).
POLYS = {
    "https://download.geofabrik.de/atlantis/oceania.poly": "o\n1\n 0.2 0.2\n 1.8 0.2\n 1.8 0.8\n 0.2 0.8\nEND\nEND\n",
    "https://download.geofabrik.de/atlantis/lemuria.poly": "l\n1\n 0.2 0.2\n 0.8 0.2\n 0.8 1.8\n 0.2 1.8\nEND\nEND\n",
}
REGIONS = ("atlantis/oceania", "atlantis/lemuria")


@functools.cache
def _gen() -> Any:
    spec = importlib.util.spec_from_file_location("gen_copernicus_pins", GENERATOR)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _url(name: str) -> str:
    return f"{BUCKET}/{name}/{name}.tif"


class Fake:
    def __init__(self, *, listed: Iterable[str] = (A, B, C), etag: str = MD5) -> None:
        self.texts = {**POLYS, f"{BUCKET}/tileList.txt": "\r\n".join(listed) + "\r\n"}
        self.etag = etag
        self.streamed: list[str] = []

    def text(self, url: str) -> str:
        return self.texts[url]

    def stream(self, url: str) -> tuple[int | None, str | None, Iterable[bytes]]:
        self.streamed.append(url)
        return len(BODY), f'"{self.etag}"', [BODY[:400], BODY[400:]]

    def head(self, url: str) -> tuple[int, int | None, str | None]:
        return 200, len(BODY), f'"{self.etag}"'


def _run(tmp_path: Path, fake: Fake, *argv: str) -> int:
    code: int = _gen().main(
        list(argv),
        text=fake.text,
        stream=fake.stream,
        head=fake.head,
        today=date(2026, 9, 28),
        list_path=tmp_path / "tiles.txt",
        pins_path=tmp_path / "pins.yaml",
        regions=REGIONS,
    )
    return code


def test_refresh_list_writes_the_bucket_s_names_sorted_with_the_header(tmp_path: Path) -> None:
    assert _run(tmp_path, Fake(listed=(C, A, B)), "--refresh-list") == 0
    text = (tmp_path / "tiles.txt").read_text()
    assert "SPDX-License-Identifier: CC0-1.0" in text
    assert "GENERATED by scripts/gen_copernicus_pins.py" in text
    assert text.splitlines()[-3:] == [A, B, C]


def test_pins_follow_the_fixed_order_and_a_run_continues_where_the_last_stopped(
    tmp_path: Path,
) -> None:
    fake = Fake()
    _run(tmp_path, fake, "--refresh-list")
    assert _run(tmp_path, fake, "--max-tiles", "2") == 0
    # oceania first (its tiles sorted: A, B), then lemuria's new one (C).
    assert fake.streamed == [_url(A), _url(B)]
    assert _run(tmp_path, fake, "--max-tiles", "5") == 0
    assert fake.streamed == [_url(A), _url(B), _url(C)]
    pins = _gen().parse_pins((tmp_path / "pins.yaml").read_text(), frozenset({A, B, C}))
    assert [row["tile"] for row in pins] == [A, B, C]
    assert pins[0]["sha256"] == hashlib.sha256(BODY).hexdigest()
    assert pins[0]["md5"] == MD5
    assert pins[0]["measured"] == "2026-09-28"


def test_there_is_no_way_to_pin_one_region_first() -> None:
    with pytest.raises(SystemExit):
        _gen().main(["--region", "atlantis/oceania"])


def test_a_download_whose_md5_is_not_its_etag_is_never_pinned(tmp_path: Path) -> None:
    fake = Fake()
    _run(tmp_path, fake, "--refresh-list")
    fake.etag = "f" * 32
    with pytest.raises(SystemExit, match="is not its ETag"):
        _run(tmp_path, fake, "--max-tiles", "1")
    assert not (tmp_path / "pins.yaml").exists()


def test_check_offline_reads_the_shape_only(tmp_path: Path) -> None:
    fake = Fake()
    _run(tmp_path, fake, "--refresh-list")
    _run(tmp_path, fake, "--max-tiles", "1")
    before = (tmp_path / "pins.yaml").read_text()

    def no_network(url: str) -> str:
        raise AssertionError(f"--offline asked {url}")

    code = _gen().main(
        ["--check", "--offline"],
        text=no_network,
        list_path=tmp_path / "tiles.txt",
        pins_path=tmp_path / "pins.yaml",
    )
    assert code == 0
    assert (tmp_path / "pins.yaml").read_text() == before


def test_check_names_a_changed_tile_and_a_changed_list(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    fake = Fake()
    _run(tmp_path, fake, "--refresh-list")
    _run(tmp_path, fake, "--max-tiles", "1")
    assert _run(tmp_path, fake, "--check") == 0
    fake.etag = "f" * 32
    fake.texts[f"{BUCKET}/tileList.txt"] = f"{A}\r\n{B}\r\n"
    assert _run(tmp_path, fake, "--check") == 1
    out = capsys.readouterr().out
    assert "1 removed" in out and A in out


def test_a_pin_naming_a_tile_not_in_the_list_is_refused(tmp_path: Path) -> None:
    text = (
        "# GENERATED by scripts/gen_copernicus_pins.py\n"
        f"pins:\n- tile: {C}\n  size: 1\n  sha256: {'a' * 64}\n  md5: {'b' * 32}\n"
    )
    with pytest.raises(SystemExit, match="names no listed tile"):
        _gen().parse_pins(text, frozenset({A}))


def test_the_committed_files_are_well_formed() -> None:
    assert _gen().main(["--check", "--offline"]) == 0
