# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""scripts/gen_geofabrik_countries.py: the region -> country table, from a
kept copy of Geofabrik's index. No network: the index here is a fixture."""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
from types import ModuleType

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

INDEX = """{"features": [
 {"properties": {"id": "north-america", "urls": {"pbf":
  "https://download.geofabrik.de/north-america-latest.osm.pbf"}}},
 {"properties": {"id": "us/vermont", "parent": "north-america", "iso3166-2": ["US-VT"],
  "urls": {"pbf": "https://download.geofabrik.de/north-america/us/vermont-latest.osm.pbf"}}}
]}"""


def _script() -> ModuleType:
    spec = importlib.util.spec_from_file_location(
        "gen_geofabrik_countries", REPO_ROOT / "scripts" / "gen_geofabrik_countries.py"
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_table_is_rendered_from_the_index_with_its_measured_date() -> None:
    text = _script().render(INDEX, "2026-01-02")
    assert "GENERATED by scripts/gen_geofabrik_countries.py" in text
    data = yaml.safe_load(text)
    assert data["measured"] == "2026-01-02"
    assert data["regions"] == {"north-america/us/vermont": ["US"]}


def test_the_measured_date_is_the_index_file_s_not_today_s(tmp_path: Path) -> None:
    index = tmp_path / "index.json"
    index.write_text(INDEX)
    os.utime(index, (0, 86400 * 365 + 43200))
    assert _script().measured(index) == "1971-01-01"


def test_a_missing_index_is_an_error_naming_the_file_and_the_flag(tmp_path: Path) -> None:
    with pytest.raises(SystemExit) as raised:
        _script().read_index(tmp_path / "absent.json")
    assert "absent.json" in str(raised.value)
    assert "--fetch" in str(raised.value)


def test_check_on_a_stale_table_fails_and_writes_nothing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    module = _script()
    index = tmp_path / "index.json"
    index.write_text(INDEX)
    out = tmp_path / "out.yaml"
    out.write_text("stale\n")
    monkeypatch.setattr(module, "INDEX", index)
    monkeypatch.setattr(module, "OUT", out)
    monkeypatch.setattr(module, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(module, "read_index", lambda: index.read_text())
    monkeypatch.setattr(module, "measured", lambda: "2026-01-02")
    assert module.main(["--check"]) == 1
    assert out.read_text() == "stale\n"
    assert module.main([]) == 0
    assert module.main(["--check"]) == 0
    assert "up to date" in capsys.readouterr().out


def test_check_compares_the_regions_only_not_the_measured_date(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Review M-4: `measured` is the index file's mtime, so a fresh fetch in
    the weekly job always moves it. Only the regions mapping is compared."""
    module = _script()
    out = tmp_path / "out.yaml"
    out.write_text(module.render(INDEX, "2020-01-01"))
    monkeypatch.setattr(module, "OUT", out)
    monkeypatch.setattr(module, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(module, "read_index", lambda: INDEX)
    monkeypatch.setattr(module, "measured", lambda: "2026-09-28")
    assert module.main(["--check"]) == 0
    moved = INDEX.replace("US-VT", "CA-QC")
    monkeypatch.setattr(module, "read_index", lambda: moved)
    assert module.main(["--check"]) == 1
    assert "2020-01-01" in out.read_text()


def test_the_weekly_job_can_fetch_then_check(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    module = _script()
    out = tmp_path / "out.yaml"
    out.write_text(module.render(INDEX, "2020-01-01"))
    fetched: list[bool] = []
    monkeypatch.setattr(module, "OUT", out)
    monkeypatch.setattr(module, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(module, "fetch", lambda: fetched.append(True))
    monkeypatch.setattr(module, "read_index", lambda: INDEX)
    monkeypatch.setattr(module, "measured", lambda: "2026-09-28")
    assert module.main(["--fetch", "--check"]) == 0
    assert fetched == [True]


def test_every_pinned_region_has_a_country_row() -> None:
    """Review M-4, offline: a pinned region with no row would convert with no
    border merged, silently degrading address search to Unknown."""
    from hammunition.geofabrik import load_countries, load_pins

    data = REPO_ROOT / "catalog" / "data"
    table = load_countries(data / "geofabrik-countries.yaml")
    pinned = {region for region, _ in load_pins(data / "geofabrik-pins.yaml")}
    assert pinned, "the pin list is empty"
    assert sorted(pinned - set(table)) == []


def test_the_weekly_ci_job_checks_the_country_table() -> None:
    workflow = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text()
    assert "scripts/gen_geofabrik_countries.py --fetch --check" in workflow
