# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""The US Topo index generator (D-068), on synthetic inputs; no network."""

from __future__ import annotations

import functools
import importlib.util
import io
import sys
import zipfile
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATOR = REPO_ROOT / "scripts" / "gen_ustopo_index.py"
PREFIX = "StagedProducts/Maps/USTopo/GeoTIFF/"
MD5 = "0123456789abcdef0123456789abcdef"
MD6 = "fedcba9876543210fedcba9876543210"

CSV = (
    "map_name,westbc,eastbc,northbc,southbc,original_product\n"
    "Alpha,0.00000000,0.12500000,0.12500000,0.00000000,ZZ_Alpha_20240101_TM_geo.pdf\n"
    "Beta,0.12500000,0.25000000,0.12500000,0.00000000,ZZ_Beta_20260606_TM_geo.pdf\n"
    "Gamma,0.25000000,0.37500000,0.12500000,0.00000000,ZZ_Gamma_20240101_TM_geo.pdf\n"
    "Delta,-0.12500000,0.00000000,0.12500000,0.00000000,ZY_Delta_20230303_TM_geo.pdf\n"
)
LISTING = [
    (PREFIX, 0, "d41d8cd98f00b204e9800998ecf8427e"),
    (f"{PREFIX}ZZ/ZZ_Alpha_20200101_TM_geo.tif", 10, f'"{MD6}"'),
    (f"{PREFIX}ZZ/ZZ_Alpha_20240101_TM_geo.tif", 11, f'"{MD5}"'),
    # Beta's current edition (2026) is a PDF only; 2024 is its newest GeoTIFF.
    (f"{PREFIX}ZZ/ZZ_Beta_20220202_TM_geo.tif", 20, f'"{MD5}-2"'),
    (f"{PREFIX}ZZ/ZZ_Beta_20240404_TM_geo.tif", 21, f'"{MD6}-2"'),
    # Gamma has no GeoTIFF at all; Delta sits in another state's folder.
    (f"{PREFIX}ZZ/ZY_Delta_20230303_TM_geo.tif", 30, f'"{MD5}"'),
]


@functools.cache
def _gen() -> Any:
    spec = importlib.util.spec_from_file_location("gen_ustopo_index", GENERATOR)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _built() -> Any:
    gen = _gen()
    return gen.build(CSV, gen.parse_listing(LISTING))


def test_the_current_edition_is_used_where_the_bucket_has_it() -> None:
    quads = {q.path: q for q in _built().quads}
    alpha = quads["ZZ/ZZ_Alpha_20240101"]
    assert (alpha.size, alpha.etag) == (11, MD5)
    assert "ZZ/ZZ_Alpha_20200101" not in quads


def test_a_pdf_only_current_edition_falls_back_to_the_newest_geotiff() -> None:
    built = _built()
    beta = [q for q in built.quads if q.name.startswith("ZZ_Beta")]
    assert [(q.path, q.etag) for q in beta] == [("ZZ/ZZ_Beta_20240404", f"{MD6}-2")]
    assert (built.current, built.older, built.missing) == (2, 1, 1)


def test_a_quad_with_no_geotiff_is_left_out_and_counted() -> None:
    assert not [q for q in _built().quads if "Gamma" in q.name]


def test_a_quad_filed_in_another_folder_keeps_its_folder() -> None:
    assert "ZZ/ZY_Delta_20230303" in {q.path for q in _built().quads}


def test_rendering_is_sorted_and_reads_back_well_formed() -> None:
    gen = _gen()
    text = gen.render(_built(), "2026-09-29")
    rows = [line for line in text.splitlines() if line and not line.startswith("#")]
    assert [r.split()[-1] for r in rows] == sorted(r.split()[-1] for r in rows)
    assert rows[0] == f"0 -0.125 0.125 0 30 {MD5} ZZ/ZY_Delta_20230303"
    checked = gen.check_shape(text)
    assert len(checked.quads) == 3
    assert "last updated 2026-09-29" in text


@pytest.mark.parametrize(
    ("edit", "message"),
    [
        (lambda t: t.replace("# GENERATED by", "# made by"), "generated"),
        (lambda t: t + f"1 1 1.125 1.125 5 {MD5} ZZ/ZZ_Zeta_20240101\n", "edited by hand"),
        (lambda t: "\n".join(reversed(t.splitlines())), "not sorted"),
        (lambda t: t.replace("# quads:", "# sheets:"), "quads:"),
        (
            lambda t: t.replace("left out, no GeoTIFF at all: 1", "left out, no GeoTIFF at all: 5"),
            "row count",
        ),
    ],
)
def test_a_hand_edited_index_is_refused(edit: Any, message: str) -> None:
    gen = _gen()
    text = gen.render(_built(), "2026-09-29")
    with pytest.raises(gen.GeneratorError, match=message):
        gen.check_shape(edit(text))


def test_the_online_check_fails_on_what_breaks_an_install_only() -> None:
    gen = _gen()
    quads = _built().quads
    live = [
        (f"{PREFIX}ZZ/ZZ_Alpha_20240101_TM_geo.tif", 11, f'"{MD6}"'),  # ETag changed
        (f"{PREFIX}ZZ/ZZ_Beta_20240404_TM_geo.tif", 21, f'"{MD6}-2"'),
        (f"{PREFIX}ZZ/ZZ_Beta_20260606_TM_geo.tif", 22, f'"{MD5}"'),  # a newer edition
        # Delta is gone.
    ]
    editions = gen.parse_listing(live)
    problems = gen.check_online(quads, editions)
    assert len(problems) == 2
    assert any("ZZ/ZZ_Alpha_20240101" in p and "ETag" in p for p in problems)
    assert any("ZZ/ZY_Delta_20230303: no longer in the bucket" in p for p in problems)
    assert gen.newer_editions(quads, editions) == 1


def test_the_listing_follows_every_page() -> None:
    gen = _gen()
    ns = "http://s3.amazonaws.com/doc/2006-03-01/"

    def page(keys: list[str], token: str | None) -> bytes:
        items = "".join(
            f"<Contents><Key>{k}</Key><Size>7</Size><ETag>&quot;{MD5}&quot;</ETag></Contents>"
            for k in keys
        )
        more = (
            f"<IsTruncated>true</IsTruncated><NextContinuationToken>{token}</NextContinuationToken>"
            if token
            else "<IsTruncated>false</IsTruncated>"
        )
        return f'<ListBucketResult xmlns="{ns}">{items}{more}</ListBucketResult>'.encode()

    asked: list[str] = []

    def get(url: str) -> bytes:
        asked.append(url)
        if "continuation-token" in url:
            return page(["b"], None)
        return page(["a"], "t1")

    assert list(gen.list_bucket(get)) == [("a", 7, f'"{MD5}"'), ("b", 7, f'"{MD5}"')]
    assert len(asked) == 2
    assert all(u.startswith("https://prd-tnm.s3.amazonaws.com/?") for u in asked)


def test_the_zip_gives_the_csv_and_the_publishers_date() -> None:
    gen = _gen()
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("ustopo_current.csv", CSV)
        archive.writestr("ustopo_current.txt", "Total Files  | 4\nLast Updated | 2026-09-29\n")
    text, updated = gen.read_zip(buffer.getvalue())
    assert text == CSV
    assert updated == "2026-09-29"
    with pytest.raises(gen.GeneratorError):
        gen.read_zip(b"not a zip")


def test_only_the_bucket_is_asked() -> None:
    with pytest.raises(_gen().GeneratorError, match="only https://prd-tnm"):
        _gen()._get("https://example.invalid/ustopo_current.zip")
