# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Kiwix books: the allow-list, the pin file and the station's selection.  D-065.

The allow-list is the curation step: a book the catalog does not list has no
known licence to print, so choosing it is refused by name. The pin file is
generated from Kiwix's own ``.meta4`` files; these tests read hand-made
fragments of both and the ham.stackexchange ``.meta4`` as the spike fetched
it, trimmed.
"""

from __future__ import annotations

import pytest

from hammunition.kiwix import (
    Book,
    BookPin,
    KiwixError,
    current_file,
    file_date,
    load_books,
    load_pins,
    parse_library,
    parse_meta4,
    resolve_books,
)

BOOKS = """
books:
  - id: ham.stackexchange.com_en_all
    name: ham.stackexchange.com_en_all
    flavour: null
    category: stack_exchange
    title: Amateur Radio Stack Exchange
    licence: CC BY-SA
    licence_url: https://stackoverflow.com/help/licensing
  - id: wikipedia_en_medicine_nopic
    name: wikipedia_en_medicine
    flavour: nopic
    category: wikipedia
    title: WikiMed, no pictures
    licence: CC BY-SA 4.0 (text; media individually licensed)
    licence_url: https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use
    note: The medical subset of English Wikipedia.
"""

SHA = "71480bd280ffaede3084fa2c9f47f87c3178f8ce8d67cdb19fb66a8025a7b93e"

PINS = f"""
# GENERATED by scripts/gen_kiwix_pins.py. Do not edit by hand.
pins:
  - id: ham.stackexchange.com_en_all
    file: ham.stackexchange.com_en_all_2026-08.zim
    url: https://download.kiwix.org/zim/stack_exchange/ham.stackexchange.com_en_all_2026-08.zim
    size: 75931239
    sha256: {SHA}
    published: "2026-08-02"
    measured: "2026-09-29"
"""

META4 = f"""<?xml version="1.0" encoding="UTF-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
  <generator>MirrorBrain/2.19.0</generator>
  <file name="ham.stackexchange.com_en_all_2026-08.zim">
    <size>75931239</size>
    <hash type="md5">2d481b559e37a98c4c8ec861e0d99723</hash>
    <hash type="sha-1">b2158483b150962243f1c6c297f80ea3cf8908ae</hash>
    <hash type="sha-256">{SHA}</hash>
    <pieces length="4194304" type="sha-1"><hash>1f8e6c78f22741da3000ff5974e06088cc6720f1</hash></pieces>
    <url location="de" priority="1">https://mirror.example/zim/stack_exchange/ham.stackexchange.com_en_all_2026-08.zim</url>
  </file>
</metalink>
"""

LIBRARY = """<?xml version="1.0" encoding="UTF-8" ?>
<library version="20110515">
  <book id="a" name="ham.stackexchange.com_en_all" date="2026-08-02" size="74152"
    url="https://lb.download.kiwix.org/zim/stack_exchange/ham.stackexchange.com_en_all_2026-08.zim.meta4" />
  <book id="b" name="wikipedia_en_medicine" flavour="nopic" date="2026-04-11" size="1"
    url="https://lb.download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nopic_2026-04.zim.meta4" />
  <book id="c" name="wikipedia_en_medicine" flavour="maxi" date="2026-04-11" size="1"
    url="https://lb.download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_maxi_2026-04.zim.meta4" />
</library>
"""

OPDS = """<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <entry>
    <name>wikipedia_en_medicine</name>
    <flavour>maxi</flavour>
    <link rel="http://opds-spec.org/acquisition/open-access" type="application/x-zim"
      href="https://lb.download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_maxi_2026-10.zim.meta4" />
  </entry>
  <entry>
    <name>wikipedia_en_medicine</name>
    <flavour>nopic</flavour>
    <link rel="http://opds-spec.org/acquisition/open-access" type="application/x-zim"
      href="https://lb.download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nopic_2026-10.zim.meta4" />
  </entry>
</feed>
"""


def test_the_allow_list_loads_with_each_books_licence() -> None:
    books = load_books(BOOKS)
    assert list(books) == ["ham.stackexchange.com_en_all", "wikipedia_en_medicine_nopic"]
    med = books["wikipedia_en_medicine_nopic"]
    assert med.licence == "CC BY-SA 4.0 (text; media individually licensed)"
    assert med.flavour == "nopic" and med.category == "wikipedia"
    assert books["ham.stackexchange.com_en_all"].flavour is None


@pytest.mark.parametrize(
    ("change", "message"),
    [
        (("id: wikipedia_en_medicine_nopic", "id: wikimed"), "name_flavour"),
        (("https://stackoverflow.com/help/licensing", "http://x.example/"), "https"),
        (("category: wikipedia", "category: ../etc"), "category"),
    ],
)
def test_a_malformed_allow_list_is_refused_by_name(change: tuple[str, str], message: str) -> None:
    with pytest.raises(KiwixError, match=message):
        load_books(BOOKS.replace(*change))


def test_a_book_listed_twice_is_refused() -> None:
    entry = BOOKS.split("  - id: wikipedia_en_medicine_nopic")[0].split("books:\n")[1]
    with pytest.raises(KiwixError, match="twice"):
        load_books(BOOKS + entry)


def test_pins_load_and_a_malformed_row_is_refused() -> None:
    pins = load_pins(PINS)
    pin = pins["ham.stackexchange.com_en_all"]
    assert pin.size == 75931239 and pin.sha256 == SHA
    assert file_date(pin.file) == "2026-08"
    with pytest.raises(KiwixError, match="sha256"):
        load_pins(PINS.replace(SHA, "abc"))
    with pytest.raises(KiwixError, match="file"):
        load_pins(PINS.replace("en_all_2026-08.zim\n", "en_all.zim\n", 1))
    with pytest.raises(KiwixError, match=r"download\.kiwix\.org"):
        load_pins(PINS.replace("https://download.kiwix.org", "https://evil.example"))
    with pytest.raises(KiwixError, match="generated"):
        load_pins(PINS.replace("GENERATED", "written"))


def test_a_chosen_book_resolves_to_its_pin_and_licence() -> None:
    [chosen] = resolve_books(("ham.stackexchange.com_en_all",), load_books(BOOKS), load_pins(PINS))
    assert chosen.book.licence == "CC BY-SA"
    assert chosen.pin.file == "ham.stackexchange.com_en_all_2026-08.zim"


def test_a_book_outside_the_allow_list_is_refused_naming_the_list() -> None:
    with pytest.raises(KiwixError, match="hammunition reference books"):
        resolve_books(("wikipedia_en_simple_all_nopic",), load_books(BOOKS), load_pins(PINS))


def test_an_allowed_book_with_no_pin_is_refused_naming_the_generator() -> None:
    with pytest.raises(KiwixError, match=r"scripts/gen_kiwix_pins\.py"):
        resolve_books(("wikipedia_en_medicine_nopic",), load_books(BOOKS), load_pins(PINS))


def test_the_meta4_gives_file_size_and_sha256() -> None:
    assert parse_meta4(META4) == ("ham.stackexchange.com_en_all_2026-08.zim", 75931239, SHA)


def test_a_meta4_with_no_sha256_is_refused() -> None:
    with pytest.raises(KiwixError, match="sha-256"):
        parse_meta4(META4.replace(f'<hash type="sha-256">{SHA}</hash>', ""))


def test_the_library_maps_name_and_flavour_to_the_meta4() -> None:
    library = parse_library(LIBRARY)
    assert library[("wikipedia_en_medicine", "nopic")].endswith("medicine_nopic_2026-04.zim.meta4")
    assert ("ham.stackexchange.com_en_all", None) in library


def test_the_opds_answer_names_the_current_file_of_the_right_flavour() -> None:
    assert current_file(OPDS, "wikipedia_en_medicine", "nopic") == (
        "wikipedia_en_medicine_nopic_2026-10.zim"
    )
    assert current_file(OPDS, "wikipedia_en_medicine", "mini") is None


def test_dataclasses_are_what_the_other_modules_read() -> None:
    book = load_books(BOOKS)["ham.stackexchange.com_en_all"]
    assert isinstance(book, Book)
    assert isinstance(load_pins(PINS)["ham.stackexchange.com_en_all"], BookPin)


def test_a_document_declaring_entities_is_refused_before_parsing() -> None:
    hostile = '<?xml version="1.0"?><!DOCTYPE x [<!ENTITY a "aaaa">]><library/>'
    with pytest.raises(KiwixError, match="DTD"):
        parse_library(hostile)
