# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""The Kiwix pin file is generated; nothing here reaches the network.  D-065.

The library index and every ``.meta4`` are injected. Two books: one with a
flavour, one without, as the real allow-list has both.
"""

from __future__ import annotations

import functools
import importlib.util
import sys
from datetime import date
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATOR = REPO_ROOT / "scripts" / "gen_kiwix_pins.py"

BOOKS = """\
books:
  - id: ham.stackexchange.com_en_all
    name: ham.stackexchange.com_en_all
    flavour: null
    category: stack_exchange
    title: Amateur Radio Stack Exchange
    licence: CC BY-SA
    licence_url: https://stackoverflow.com/help/licensing
  - id: wikipedia_en_medicine_nopic
    name: wikipedia_en_medicine
    flavour: nopic
    category: wikipedia
    title: WikiMed, no pictures
    licence: CC BY-SA 4.0 (text; media individually licensed)
    licence_url: https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use
"""

LB = "https://lb.download.kiwix.org/zim"
HAM = "ham.stackexchange.com_en_all_2026-08.zim"
MED = "wikipedia_en_medicine_nopic_2026-04.zim"
LIBRARY = f"""<?xml version="1.0" encoding="UTF-8" ?>
<library version="20110515">
  <book id="a" name="ham.stackexchange.com_en_all" date="2026-08-02" url="{LB}/stack_exchange/{HAM}.meta4" />
  <book id="b" name="wikipedia_en_medicine" flavour="nopic" date="2026-04-11" url="{LB}/wikipedia/{MED}.meta4" />
  <book id="c" name="wikipedia_en_medicine" flavour="maxi" date="2026-04-11" url="{LB}/wikipedia/x_2026-04.zim.meta4" />
</library>
"""


def meta4(file: str, size: int, sha: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<metalink xmlns="urn:ietf:params:xml:ns:metalink">'
        f'<file name="{file}"><size>{size}</size>'
        f'<hash type="sha-256">{sha}</hash></file></metalink>'
    )


SHA_HAM = "a" * 64
SHA_MED = "b" * 64
ANSWERS = {
    "https://download.kiwix.org/library/library_zim.xml": LIBRARY,
    f"{LB}/stack_exchange/{HAM}.meta4": meta4(HAM, 75931239, SHA_HAM),
    f"{LB}/wikipedia/{MED}.meta4": meta4(MED, 862376216, SHA_MED),
    f"https://download.kiwix.org/zim/stack_exchange/{HAM}.meta4": meta4(HAM, 75931239, SHA_HAM),
    f"https://download.kiwix.org/zim/wikipedia/{MED}.meta4": meta4(MED, 862376216, SHA_MED),
}


@functools.cache
def _gen() -> Any:
    spec = importlib.util.spec_from_file_location("gen_kiwix_pins", GENERATOR)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _fake(answers: dict[str, str], asked: list[str] | None = None) -> Any:
    gen = _gen()

    def text(url: str) -> str:
        if asked is not None:
            asked.append(url)
        if url not in answers:
            raise gen.Gone(url)
        return answers[url]

    return text


def _run(tmp_path: Path, *argv: str, answers: dict[str, str] | None = None) -> int:
    books = tmp_path / "kiwix-books.yaml"
    if not books.exists():
        books.write_text(BOOKS)
    result: int = _gen().main(
        list(argv),
        text=_fake(ANSWERS if answers is None else answers),
        today=date(2026, 9, 29),
        books_path=books,
        pins_path=tmp_path / "kiwix-pins.yaml",
    )
    return result


def test_generation_pins_every_allowed_book_from_its_meta4(tmp_path: Path) -> None:
    assert _run(tmp_path) == 0
    text = (tmp_path / "kiwix-pins.yaml").read_text()
    assert "GENERATED by scripts/gen_kiwix_pins.py" in text
    sys.path.insert(0, str(REPO_ROOT / "src"))
    from hammunition.kiwix import load_pins

    pins = load_pins(text)
    assert list(pins) == ["ham.stackexchange.com_en_all", "wikipedia_en_medicine_nopic"]
    ham = pins["ham.stackexchange.com_en_all"]
    assert ham.url == f"https://download.kiwix.org/zim/stack_exchange/{HAM}"
    assert (ham.size, ham.sha256, ham.published, ham.measured) == (
        75931239,
        SHA_HAM,
        "2026-08",
        "2026-09-29",
    )


def test_a_book_the_library_does_not_list_refuses_naming_it(tmp_path: Path) -> None:
    answers = dict(ANSWERS)
    answers["https://download.kiwix.org/library/library_zim.xml"] = LIBRARY.replace(
        'name="ham.stackexchange.com_en_all"', 'name="gone"'
    )
    with pytest.raises(SystemExit, match=r"ham\.stackexchange\.com_en_all"):
        _run(tmp_path, answers=answers)
    assert not (tmp_path / "kiwix-pins.yaml").exists()


def test_a_book_filed_under_another_category_refuses(tmp_path: Path) -> None:
    (tmp_path / "kiwix-books.yaml").write_text(
        BOOKS.replace("category: stack_exchange", "category: other")
    )
    with pytest.raises(SystemExit, match="category"):
        _run(tmp_path)


def test_the_offline_check_passes_on_a_generated_file_and_writes_nothing(tmp_path: Path) -> None:
    assert _run(tmp_path) == 0
    pins = tmp_path / "kiwix-pins.yaml"
    before = pins.stat().st_mtime_ns
    assert _run(tmp_path, "--check", "--offline", answers={}) == 0
    assert pins.stat().st_mtime_ns == before


def test_the_offline_check_names_an_allowed_book_with_no_pin(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert _run(tmp_path) == 0
    (tmp_path / "kiwix-books.yaml").write_text(
        BOOKS
        + """\
  - id: wikem_en_all_nopic
    name: wikem_en_all
    flavour: nopic
    category: other
    title: WikEM
    licence: CC BY-SA 4.0
    licence_url: https://wikem.org/wiki/WikEM:Copyrights
"""
    )
    assert _run(tmp_path, "--check", "--offline", answers={}) == 1
    assert "wikem_en_all_nopic" in capsys.readouterr().out


def test_the_online_check_reports_current(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert _run(tmp_path) == 0
    capsys.readouterr()
    assert _run(tmp_path, "--check") == 0
    assert "up to date" in capsys.readouterr().out


def test_the_online_check_names_a_pin_kiwix_has_dropped(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert _run(tmp_path) == 0
    answers = {
        k: v for k, v in ANSWERS.items() if not k.startswith("https://download.kiwix.org/zim/wiki")
    }
    capsys.readouterr()
    assert _run(tmp_path, "--check", answers=answers) == 1
    out = capsys.readouterr().out
    assert MED in out and "gen_kiwix_pins.py" in out and "two" in out


def test_the_online_check_names_a_pin_whose_hash_moved(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert _run(tmp_path) == 0
    answers = dict(ANSWERS)
    answers[f"https://download.kiwix.org/zim/wikipedia/{MED}.meta4"] = meta4(MED, 1, "c" * 64)
    capsys.readouterr()
    assert _run(tmp_path, "--check", answers=answers) == 1
    assert "wikipedia_en_medicine_nopic" in capsys.readouterr().out


def test_the_real_fetcher_refuses_other_hosts() -> None:
    with pytest.raises(SystemExit, match="refusing"):
        _gen().real_text("https://evil.example/library_zim.xml")


def test_the_real_fetcher_refuses_a_redirect_off_kiwix_before_following_it() -> None:
    import urllib.request

    gen = _gen()
    assert any(isinstance(h, gen.KiwixOnlyRedirects) for h in gen._opener().handlers)
    request = urllib.request.Request("https://download.kiwix.org/library/library_zim.xml")
    with pytest.raises(SystemExit, match="refusing"):
        gen.KiwixOnlyRedirects().redirect_request(
            request, None, 302, "Found", {}, "https://evil.example/x"
        )
