# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Adding a third-party apt repository against a pinned key.  D-040.

Two files, one repository, both disclosed in the plan and both removed by
``uninstall``:

* ``/etc/apt/keyrings/<name>.gpg`` — the signing key from the manifest's
  ``key_url``, kept only after its computed fingerprint matched the one the
  manifest pins. A fingerprint is computed over OpenPGP packets, so the
  packets are what is written: a publisher's armored ``.asc`` is dearmored
  (CRC checked) *before* the check and a binary ``.gpg`` is untouched, and
  either way the bytes on disk are exactly the bytes the fingerprint was
  taken from, in the binary form every distribution's own ``Signed-By``
  instructions use.
* ``/etc/apt/sources.list.d/<name>.sources`` — a deb822 source whose
  ``Signed-By`` names that keyring and nothing wider, so the key is
  trusted for this repository only and never archive-wide.

The order of steps is the security property. The key is fetched and
checked as a ``fetch`` action, which the executor runs before anything
touches the machine; the two ``install`` commands come after; then
``apt-get update`` and a simulate over the whole apt step, so a repository
that does not carry what it promised refuses before the apt step rather
than partway through it.

What the plan-time check reads is the file system, never apt: a
repository is *ours* when both files exist with the content this engine
would write, *foreign* when a file of the same name exists with anything
else, and *absent* otherwise. A foreign file is a refusal -- overwriting
someone else's source under our name would silently change what their
machine trusts.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from enum import StrEnum
from functools import partial
from pathlib import Path

from hammunition.backends.base import Action, BackendError, Command
from hammunition.fetch import Transport, UrllibTransport
from hammunition.manifest.schema import AptRepo
from hammunition.openpgp import (
    KeyFileError,
    binary_form,
    normalize_fingerprint,
    primary_fingerprints,
)
from hammunition.paths import artifact_cache_dir

__all__ = ["AptRepoBackend", "RepoFiles", "RepoState", "render_sources"]

DEFAULT_SOURCES_DIR = Path("/etc/apt/sources.list.d")
DEFAULT_KEYRINGS_DIR = Path("/etc/apt/keyrings")

#: A key file is a few kilobytes. Anything approaching a megabyte is not one.
MAX_KEY_BYTES = 1024 * 1024
_CHUNK = 64 * 1024

MARKER = "generated by hammunition"


class RepoState(StrEnum):
    absent = "absent"
    ours = "ours"
    foreign = "foreign"


@dataclass(frozen=True)
class RepoFiles:
    """Where one repository's two files live."""

    sources: Path
    keyring: Path


def render_sources(repo: AptRepo, keyring: Path, *, unit: str) -> str:
    """The deb822 source, with a comment saying who wrote it and how to undo it.

    deb822 permits ``#`` comment lines, and the marker is what lets an
    uninstall read the file back and know it is looking at its own work
    before removing it.
    """
    return (
        f"# {MARKER} for {unit}. Remove with `hammunition uninstall {unit}`, or\n"
        f"# delete this file and {keyring}, then run apt-get update.\n"
        f"Types: deb\n"
        f"URIs: {repo.uri}\n"
        f"Suites: {' '.join(repo.suites)}\n"
        f"Components: {' '.join(repo.components)}\n"
        f"Signed-By: {keyring}\n"
    )


class AptRepoBackend:
    """Plans and performs the addition of manifest-declared repositories."""

    def __init__(
        self,
        *,
        cache_dir: Path | None = None,
        staging_dir: Path | None = None,
        sources_dir: Path = DEFAULT_SOURCES_DIR,
        keyrings_dir: Path = DEFAULT_KEYRINGS_DIR,
        transport: Transport | None = None,
        owner: str | None = None,
    ) -> None:
        self.cache_dir = cache_dir if cache_dir is not None else artifact_cache_dir(owner)
        self.staging_dir = staging_dir if staging_dir is not None else self.cache_dir / "apt-repos"
        self.sources_dir = sources_dir
        self.keyrings_dir = keyrings_dir
        self.transport: Transport = transport if transport is not None else UrllibTransport()

    # -- where things go, pure --------------------------------------------

    def files_for(self, repo: AptRepo) -> RepoFiles:
        return RepoFiles(
            sources=self.sources_dir / f"{repo.name}.sources",
            keyring=self.keyrings_dir / f"{repo.name}.gpg",
        )

    def cached_key(self, repo: AptRepo) -> Path:
        """Where the verified key sits before it is installed. Named by the
        fingerprint it was verified against, so a manifest that re-pins a key
        never reuses an old file."""
        return self.cache_dir / f"{normalize_fingerprint(repo.key_fingerprint)}-{repo.name}.gpg"

    def staged_sources(self, repo: AptRepo) -> Path:
        return self.staging_dir / f"{repo.name}.sources"

    # -- plan-time ----------------------------------------------------------

    def state(self, repo: AptRepo, *, unit: str) -> RepoState:
        """What the file system says about this repository, without apt."""
        files = self.files_for(repo)
        sources_exists = files.sources.exists()
        keyring_exists = files.keyring.exists()
        if not sources_exists and not keyring_exists:
            return RepoState.absent
        if not (sources_exists and keyring_exists):
            return RepoState.foreign
        if files.sources.read_text() != render_sources(repo, files.keyring, unit=unit):
            return RepoState.foreign
        try:
            found = primary_fingerprints(files.keyring.read_bytes())
        except (KeyFileError, OSError):
            return RepoState.foreign
        if found != (normalize_fingerprint(repo.key_fingerprint),):
            return RepoState.foreign
        return RepoState.ours

    # -- execution ----------------------------------------------------------

    def steps(self, repo: AptRepo, *, unit: str) -> list[Action | Command]:
        files = self.files_for(repo)
        cached = self.cached_key(repo)
        staged = self.staged_sources(repo)
        return [
            Action(
                kind="fetch",
                description=(
                    f"Fetch the {repo.name} signing key and check its fingerprint "
                    f"against the one the catalog pins"
                ),
                detail=f"{repo.key_url} -> {cached} (must be {repo.key_fingerprint})",
                perform=partial(self._fetch_key, repo, cached),
            ),
            Action(
                kind="stage-apt-source",
                description=f"Render the {repo.name} source file for {unit} into a staging file",
                detail=f"staged at {staged}; installed by the commands that follow",
                perform=partial(self._stage_sources, repo, staged, files.keyring, unit),
            ),
            Command(
                argv=("install", "-D", "-m", "0644", str(cached), str(files.keyring)),
                description=f"Install the verified {repo.name} key where Signed-By will find it",
                requires_root=True,
            ),
            Command(
                argv=("install", "-D", "-m", "0644", str(staged), str(files.sources)),
                description=f"Add the {repo.name} repository, trusted through that key only",
                requires_root=True,
            ),
        ]

    def _fetch_key(self, repo: AptRepo, destination: Path) -> str:
        expected = normalize_fingerprint(repo.key_fingerprint)
        if destination.exists():
            try:
                if primary_fingerprints(destination.read_bytes()) == (expected,):
                    return f"cached key at {destination} still carries {expected}"
            except KeyFileError:
                pass
            destination.unlink()
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        temporary = destination.with_name(destination.name + f".part.{os.getpid()}")
        try:
            try:
                data = binary_form(self._download(repo.key_url))
                found = primary_fingerprints(data)
            except KeyFileError as exc:
                raise BackendError(
                    f"{repo.key_url} is not a key file this engine can identify: {exc}. "
                    f"Nothing was installed."
                ) from exc
            if found != (expected,):
                raise BackendError(
                    f"{repo.key_url} does not carry the key the catalog pins for {repo.name}.\n"
                    f"  expected primary fingerprint: {expected}\n"
                    f"  file carries:                 {', '.join(found)}\n"
                    f"The key has been discarded. Either the publisher rotated their "
                    f"key, the file holds more keys than the one disclosed, or this is "
                    f"not their key -- and a repository is never added against a key "
                    f"other than the one the operator was shown (D-040)."
                )
            temporary.write_bytes(data)
            os.replace(temporary, destination)
        finally:
            temporary.unlink(missing_ok=True)
        return f"fetched and kept {len(data)} bytes of key; primary fingerprint {expected} matches"

    def _download(self, url: str) -> bytes:
        chunks: list[bytes] = []
        size = 0
        with self.transport.open(url) as stream:
            while True:
                chunk = stream.read(_CHUNK)
                if not chunk:
                    break
                size += len(chunk)
                if size > MAX_KEY_BYTES:
                    raise BackendError(
                        f"{url} exceeds {MAX_KEY_BYTES} bytes, which no signing key does; abandoned"
                    )
                chunks.append(chunk)
        return b"".join(chunks)

    def _stage_sources(self, repo: AptRepo, staged: Path, keyring: Path, unit: str) -> str:
        staged.parent.mkdir(parents=True, exist_ok=True)
        staged.write_text(render_sources(repo, keyring, unit=unit))
        staged.chmod(0o600)
        return f"staged {staged}"
