#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Check that requirements/*.txt still match pyproject.toml.

The three hash-pinned lock files (OpenSSF Scorecard: PinnedDependencies) are
generated by ``uv pip compile``; this is the check that they were regenerated
when ``pyproject.toml`` moved. Offline and stdlib plus ``packaging``:

* every requirement ``pyproject.toml`` declares for the lock (the runtime
  dependencies, plus the ``dev`` or ``docs`` extra) has a pinned entry whose
  version satisfies its specifier -- an exact pin like ``ruff==0.16.5`` must
  match exactly;
* every pinned entry carries at least one ``--hash=sha256:`` line, because
  ``pip install --require-hashes`` refuses the whole file otherwise;
* the header's recorded command names the right extra.

With ``--recompile`` and ``uv`` on PATH it also regenerates each lock into a
scratch file and fails if the result differs (the strict form; needs the
network).

Usage:
    scripts/check_locks.py --check
    scripts/check_locks.py --check --recompile
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCKS: dict[str, str | None] = {"runtime": None, "dev": "dev", "docs": "docs"}
FIX = "run: scripts/refresh-locks.sh"

_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==(\S+?)(?:\s*;.*)?\s*\\?$")


def declared(extra: str | None) -> list[Requirement]:
    project = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text())["project"]
    reqs = [Requirement(r) for r in project["dependencies"]]
    if extra is not None:
        reqs += [Requirement(r) for r in project["optional-dependencies"][extra]]
    return reqs


def parse_lock(text: str) -> tuple[dict[str, set[str]], dict[str, int]]:
    """name -> versions pinned (a universal lock may pin one per marker), name -> hash lines."""
    versions: dict[str, set[str]] = {}
    hashes: dict[str, int] = {}
    current: str | None = None
    for line in text.splitlines():
        m = _PIN.match(line)
        if m:
            current = canonicalize_name(m.group(1))
            versions.setdefault(current, set()).add(m.group(2))
            hashes.setdefault(current, 0)
        elif current is not None and line.strip().startswith("--hash=sha256:"):
            hashes[current] += 1
    return versions, hashes


def check_one(name: str, extra: str | None) -> list[str]:
    path = REPO_ROOT / "requirements" / f"{name}.txt"
    if not path.exists():
        return [f"{path.relative_to(REPO_ROOT)} is missing; {FIX}"]
    text = path.read_text()
    problems: list[str] = []
    expect = f"--extra {extra} " if extra else ""
    if f"uv pip compile pyproject.toml {expect}--generate-hashes" not in text:
        problems.append(
            f"requirements/{name}.txt: header command does not name extra {extra!r}; {FIX}"
        )
    versions, hashes = parse_lock(text)
    for pkg, count in hashes.items():
        if count == 0:
            problems.append(f"requirements/{name}.txt: {pkg} has no hash; {FIX}")
    for req in declared(extra):
        key = canonicalize_name(req.name)
        pinned = versions.get(key)
        if not pinned:
            problems.append(
                f"requirements/{name}.txt: {req.name} is declared in pyproject.toml but not locked; {FIX}"
            )
        elif not any(req.specifier.contains(v, prereleases=True) for v in pinned):
            problems.append(
                f"requirements/{name}.txt: {req.name} locked at {sorted(pinned)} "
                f"but pyproject.toml wants {req.specifier}; {FIX}"
            )
    return problems


def _body(p: Path) -> list[str]:
    return [x for x in p.read_text().splitlines() if not x.startswith("#")]


def recompile(name: str, extra: str | None) -> list[str]:
    uv = shutil.which("uv")
    if uv is None:
        return ["--recompile needs uv on PATH"]
    lock = REPO_ROOT / "requirements" / f"{name}.txt"
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / f"{name}.txt"
        cmd = [uv, "pip", "compile", "pyproject.toml"]
        if extra:
            cmd += ["--extra", extra]
        cmd += [
            "--generate-hashes",
            "--python-version",
            "3.11",
            "--universal",
            "-q",
            "-o",
            str(out),
        ]
        subprocess.run(cmd, cwd=REPO_ROOT, check=True)
        # The header embeds the output path; compare the body only.
        if _body(out) != _body(lock):
            return [f"requirements/{name}.txt differs from a fresh compile; {FIX}"]
    return []


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument(
        "--check", action="store_true", help="verify (the only mode; accepted for symmetry)"
    )
    ap.add_argument("--recompile", action="store_true", help="also regenerate with uv and compare")
    args = ap.parse_args(argv)
    problems: list[str] = []
    for name, extra in LOCKS.items():
        problems += check_one(name, extra)
        if args.recompile:
            problems += recompile(name, extra)
    for p in problems:
        print(p, file=sys.stderr)
    if not problems:
        print("locks current")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
