#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/reference/schema.md from the manifest schema itself.

CLAUDE.md names this as the gap in reference/: "the authority is
src/hammunition/manifest/schema.py, whose fields and validators are
documented in place." A hand-written schema doc would be exactly the
duplicated-by-hand data CLAUDE.md calls a defect — it would drift the first
time a field changed. So this walks the pydantic models and renders their
real field names, types, requiredness and ``description=`` text. The class
docstrings carry the prose the field list cannot.

What a generator cannot render — a validator's cross-field logic, the *why*
behind a refusal — lives in the class docstring, which is why those
docstrings are treated as part of the reference and printed verbatim.

Usage:
    scripts/gen_schema_reference.py            # regenerate
    scripts/gen_schema_reference.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import sys
import textwrap
import types
import typing
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from pydantic import BaseModel  # noqa: E402
from pydantic_core import PydanticUndefined  # noqa: E402

from hammunition.manifest import schema  # noqa: E402

OUT = REPO_ROOT / "docs" / "reference" / "schema.md"
HEADER = "<!-- Generated by scripts/gen_schema_reference.py. Do not edit by hand -->"

#: The order the reference walks the models — the shape an author meets a
#: manifest in: the top-level object, then the install backends it dispatches
#: to, then the supporting blocks, then profiles. Names not listed are
#: appended (so a new model shows up rather than vanishing), which the no-op
#: test turns into a failure that names the omission.
ORDER = [
    "PackageManifest",
    "Selector",
    "InstallBlock",
    "AptInstall",
    "SourceInstall",
    "GitInstall",
    "BinaryInstall",
    "VenvInstall",
    "RemoteArtifact",
    "Patch",
    "PinReview",
    "Binary",
    "Launcher",
    "ServiceEndpoint",
    "SystemModification",
    "ConfigFile",
    "AptRepo",
    "ToolkitRisk",
    "UpdateBlock",
    "UpdateProbe",
    "Documentation",
    "ProfileManifest",
    "ProfileDocumentation",
    "SuggestionGroup",
    "ConsentGate",
]


def _type_name(annotation: object) -> str:
    """A short, readable rendering of a field's annotation."""
    origin = typing.get_origin(annotation)
    if origin is None:
        if isinstance(annotation, type):
            return annotation.__name__
        return str(annotation).replace("typing.", "")
    args = typing.get_args(annotation)
    if origin is typing.Union or origin is types.UnionType:
        return " | ".join(_type_name(a) for a in args if a is not type(None)) + (
            " | None" if type(None) in args else ""
        )
    base = getattr(origin, "__name__", str(origin))
    if args:
        return f"{base}[{', '.join(_type_name(a) for a in args)}]"
    return base


def _model_classes() -> dict[str, type[BaseModel]]:
    found: dict[str, type[BaseModel]] = {}
    for name in dir(schema):
        obj = getattr(schema, name)
        if (
            isinstance(obj, type)
            and issubclass(obj, BaseModel)
            and obj is not BaseModel
            and obj.__module__ == schema.__name__
            and obj.__name__ != "Strict"
        ):
            found[name] = obj
    return found


def render_model(name: str, model: type[BaseModel]) -> str:
    lines = [f"### `{name}`", ""]
    doc = textwrap.dedent(model.__doc__ or "").strip()
    if doc:
        lines += [doc, ""]
    fields = model.model_fields
    if not fields:
        return "\n".join(lines) + "\n"
    lines += ["| Field | Type | Required | Description |", "|---|---|---|---|"]
    for field_name, info in fields.items():
        required = "**yes**" if info.is_required() else "no"
        if not info.is_required() and info.default is not PydanticUndefined and info.default not in (None, [], {}):
            required = f"no (default `{info.default}`)"
        type_str = _type_name(info.annotation).replace("|", "\\|")
        desc = (info.description or "").replace("\n", " ").replace("|", "\\|").strip()
        lines.append(f"| `{field_name}` | `{type_str}` | {required} | {desc} |")
    lines.append("")
    return "\n".join(lines)


def render() -> str:
    models = _model_classes()
    ordered = ORDER + sorted(n for n in models if n not in ORDER)
    body = [
        HEADER,
        "",
        "# Manifest schema reference",
        "",
        "Generated from `src/hammunition/manifest/schema.py` — the authority. "
        "This page cannot drift from it, because it is rendered from the model "
        "definitions themselves: field names, types, whether each is required, "
        "and the `description=` text the schema carries in place. The prose "
        "above each table is the model's own docstring, which is where the "
        "cross-field validators and the reasoning behind a refusal are "
        "explained — a table cannot render a validator, so those are treated as "
        "part of the reference and kept current in the source.",
        "",
        "A manifest is **strict**: an unknown field is an error, not ignored. "
        "That is deliberate — a typo'd field name that silently did nothing is "
        "the bug this catches at load time (D-016).",
        "",
        "---",
        "",
    ]
    for name in ordered:
        if name in models:
            body.append(render_model(name, models[name]))
    return "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    content = render()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print("docs/reference/schema.md is out of date; run scripts/gen_schema_reference.py")
            return 1
        print("docs/reference/schema.md is up to date")
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
