#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the Copernicus GLO-30 tile list and sha256 pins.  D-061.

Two files under ``catalog/data/``:

* ``copernicus-glo30-tiles.txt`` -- every tile the bucket's ``tileList.txt``
  names (about 26,000; ocean squares, and land the publisher does not
  release, are absent), so the plan knows which squares have no published
  tile with no network. ``--refresh-list`` rewrites it.
* ``copernicus-glo30-pins.yaml`` -- a sha256 Hammunition measured for each
  pinned tile, with its size and the MD5 its ETag carried. Each pin costs one
  39 MB download, so the file grows run by run: ``--max-tiles N`` measures
  the next N tiles not yet pinned and keeps every existing row.

**The order is fixed and is nobody's.** The tiles are those the outlines of
``gen_geofabrik_pins.REGIONS`` touch (the 50 US states and DC), taken region
by region in that list's order, each region's tiles sorted, each tile once.
A run pins the first tiles of that order that have no pin yet, so the pin
file is always a prefix of it, whoever ran the generator. There is no
``--region``: pinning one region's tiles first would publish, in a commit,
which region the person running it cared about.

``--check`` downloads nothing. It checks both files' shape (the generated
line, every pinned tile in the list, rows sorted), then -- unless
``--offline`` -- fetches the bucket's list and diffs it against the carried
one, and ``HEAD``s every pinned tile, exiting 1 naming each one whose size or
ETag no longer matches its pin. The weekly CI job runs it; the test suite
runs ``--check --offline``, since it blocks the network.

    scripts/gen_copernicus_pins.py --refresh-list      # about 1.1 MB
    scripts/gen_copernicus_pins.py --max-tiles 0       # the pin file, nothing measured
    scripts/gen_copernicus_pins.py --max-tiles 50      # about 2 GB
    scripts/gen_copernicus_pins.py --check [--offline]
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import os
import re
import sys
import urllib.error
import urllib.request
from collections.abc import Callable, Iterable, Iterator, Sequence
from datetime import date
from pathlib import Path
from types import ModuleType
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.copernicus import (  # noqa: E402
    BUCKET,
    CopernicusError,
    parse_poly,
    parse_tile_list,
    select,
    squares_touching,
    tile_url,
)

DATA = REPO_ROOT / "catalog" / "data"
LIST = DATA / "copernicus-glo30-tiles.txt"
PINS = DATA / "copernicus-glo30-pins.yaml"
LIST_URL = f"{BUCKET}/tileList.txt"
GEOFABRIK = "https://download.geofabrik.de"
GENERATED_MARK = "GENERATED by scripts/gen_copernicus_pins.py"
SHA256 = re.compile(r"[0-9a-f]{64}")
MD5 = re.compile(r"[0-9a-f]{32}")
TIMEOUT = 60.0
CHUNK = 1024 * 1024

LICENCE_HEADER = """\
# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: CC0-1.0
"""

LIST_HEADER = f"""{LICENCE_HEADER}
# {GENERATED_MARK} --refresh-list. Do not edit by hand.
#
# Every Copernicus GLO-30 tile that exists, one name per line, from
# {LIST_URL}. A square whose tile is not listed
# has no published tile (sea, or land Copernicus does not release; this list
# cannot say which): the plan counts it and never asks the network about it.
"""

PINS_HEADER = f"""{LICENCE_HEADER}
# {GENERATED_MARK}. Do not edit by hand.
#
# sha256 pins for Copernicus GLO-30 elevation tiles, each streamed, hashed and
# discarded on its `measured` date; `md5` is the ETag it carried then. A tile
# with a row here is verified by this sha256 ("sha256, pinned by
# Hammunition"); any other by its object MD5 ("MD5 from the publisher's object
# metadata; not pinned by Hammunition"), and the plan says which.
#
# The rows are always a prefix of one fixed order -- the tiles the 50 US
# states and DC touch, state by state -- so they say nothing about who ran it.
#
# Grow:  scripts/gen_copernicus_pins.py --max-tiles N (39 MB a tile)
# Check: scripts/gen_copernicus_pins.py --check (HEAD only)
"""

#: ``text(url)`` returns a small body; ``stream(url)`` returns the declared
#: Content-Length, the ETag and the body in chunks; ``head(url)`` returns
#: (status, Content-Length, ETag).
Text = Callable[[str], str]
Stream = Callable[[str], tuple[int | None, str | None, Iterable[bytes]]]
Head = Callable[[str], tuple[int, int | None, str | None]]


def _geofabrik_regions() -> tuple[str, ...]:
    spec = importlib.util.spec_from_file_location(
        "gen_geofabrik_pins", REPO_ROOT / "scripts" / "gen_geofabrik_pins.py"
    )
    assert spec is not None and spec.loader is not None
    module: ModuleType = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    regions: tuple[str, ...] = module.REGIONS
    return regions


def render_list(names: Iterable[str]) -> str:
    return LIST_HEADER + "".join(f"{name}\n" for name in sorted(set(names)))


def order(regions: Sequence[str], tile_list: frozenset[str], text: Text) -> list[str]:
    """The fixed order: each region's tiles, sorted, in *regions*' order, once."""
    seen: dict[str, None] = {}
    for region in regions:
        outer, holes = parse_poly(text(f"{GEOFABRIK}/{region}.poly"))
        tiles, _sea = select(squares_touching(outer, holes), tile_list)
        for name in tiles:
            seen.setdefault(name, None)
    return list(seen)


def _etag(value: str | None) -> str | None:
    match = MD5.fullmatch((value or "").strip().strip('"'))
    return match.group(0) if match else None


def measure(url: str, stream: Stream) -> tuple[int, str, str]:
    """(size, sha256, md5) of *url*, checked against its Content-Length and
    its ETag: a truncated or changed download is never pinned."""
    declared, etag, chunks = stream(url)
    sha, md5, size = hashlib.sha256(), hashlib.md5(usedforsecurity=False), 0
    for chunk in chunks:
        sha.update(chunk)
        md5.update(chunk)
        size += len(chunk)
    if declared is None or size != declared or size == 0:
        raise SystemExit(f"{url}: received {size} bytes, declared {declared}; nothing pinned")
    if _etag(etag) != md5.hexdigest():
        raise SystemExit(
            f"{url}: the body's MD5 {md5.hexdigest()} is not its ETag {etag!r}; nothing pinned"
        )
    return size, sha.hexdigest(), md5.hexdigest()


def render_pins(rows: Sequence[dict[str, Any]], ordering: Sequence[str]) -> str:
    rank = {name: index for index, name in enumerate(ordering)}
    ordered = sorted(rows, key=lambda r: rank.get(r["tile"], len(rank)))
    return f"{PINS_HEADER}\n" + yaml.safe_dump(
        {"pins": ordered}, sort_keys=False, default_flow_style=False
    )


def parse_pins(text: str, tile_list: frozenset[str]) -> list[dict[str, Any]]:
    """The rows of a pin file, refused by name when malformed."""
    if GENERATED_MARK not in text:
        raise SystemExit("the pin file does not carry the generated-by line")
    rows = (yaml.safe_load(text) or {}).get("pins")
    if not isinstance(rows, list):
        raise SystemExit("the pin file has no `pins:` list")
    for row in rows:
        if not isinstance(row, dict) or str(row.get("tile")) not in tile_list:
            raise SystemExit(f"pin row names no listed tile: {row!r}")
        if not isinstance(row.get("size"), int) or row["size"] <= 0:
            raise SystemExit(f"pin row has a malformed size: {row!r}")
        if not SHA256.fullmatch(str(row.get("sha256"))):
            raise SystemExit(f"pin row has a malformed sha256: {row!r}")
        if not MD5.fullmatch(str(row.get("md5"))):
            raise SystemExit(f"pin row has a malformed md5: {row!r}")
    names = [row["tile"] for row in rows]
    if len(set(names)) != len(names):
        raise SystemExit("the pin file names a tile twice")
    return rows


def check_online(
    rows: Sequence[dict[str, Any]], tile_list: frozenset[str], text: Text, head: Head
) -> list[str]:
    problems: list[str] = []
    published = parse_tile_list(text(LIST_URL))
    if published != tile_list:
        problems.append(
            f"the carried list differs from {LIST_URL}: {len(published - tile_list)} added, "
            f"{len(tile_list - published)} removed; run --refresh-list"
        )
    for row in rows:
        url = tile_url(row["tile"])
        status, length, etag = head(url)
        if status != 200:
            problems.append(f"{url}: answered HTTP {status}, not 200")
        elif length != row["size"] or _etag(etag) != row["md5"]:
            problems.append(
                f"{url}: Content-Length {length} and ETag {etag!r}, pinned {row['size']} "
                f"and {row['md5']}"
            )
    return problems


# -- the network, used only when nothing is injected --------------------------


def _opener() -> urllib.request.OpenerDirector:
    director = urllib.request.OpenerDirector()
    for handler in (
        urllib.request.HTTPSHandler(),
        urllib.request.HTTPErrorProcessor(),
        urllib.request.HTTPDefaultErrorHandler(),
    ):
        director.add_handler(handler)
    return director


def _request(url: str, method: str = "GET") -> urllib.request.Request:
    if not url.startswith((BUCKET + "/", GEOFABRIK + "/")):
        raise SystemExit(f"refusing {url!r}")
    return urllib.request.Request(url, method=method, headers={"User-Agent": "hammunition"})


def real_text(url: str) -> str:
    with _opener().open(_request(url), timeout=TIMEOUT) as response:
        body: bytes = response.read(8 * 1024 * 1024)
    return body.decode("utf-8", errors="replace")


def real_stream(url: str) -> tuple[int | None, str | None, Iterator[bytes]]:
    response = _opener().open(_request(url), timeout=TIMEOUT)
    length = response.headers.get("Content-Length")

    def chunks() -> Iterator[bytes]:
        with response:
            while chunk := response.read(CHUNK):
                yield chunk

    declared = int(length) if length is not None else None
    return declared, response.headers.get("ETag"), chunks()


def real_head(url: str) -> tuple[int, int | None, str | None]:
    try:
        with _opener().open(_request(url, "HEAD"), timeout=TIMEOUT) as response:
            length = response.headers.get("Content-Length")
            return (
                response.status,
                int(length) if length is not None else None,
                response.headers.get("ETag"),
            )
    except urllib.error.HTTPError as exc:
        return exc.code, None, None


def _write(path: Path, text: str) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(text)
    os.replace(temporary, path)


def main(
    argv: Sequence[str] | None = None,
    *,
    text: Text | None = None,
    stream: Stream | None = None,
    head: Head | None = None,
    today: date | None = None,
    list_path: Path = LIST,
    pins_path: Path = PINS,
    regions: Sequence[str] | None = None,
) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n", 1)[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="check both files; write nothing")
    mode.add_argument("--refresh-list", action="store_true", help="rewrite the tile list")
    mode.add_argument("--max-tiles", type=int, metavar="N", help="pin the next N tiles")
    parser.add_argument(
        "--offline", action="store_true", help="with --check: the shape only, no network"
    )
    args = parser.parse_args(argv)
    get_text = text or real_text

    if args.refresh_list:
        names = parse_tile_list(get_text(LIST_URL))
        if not names:
            raise SystemExit(f"{LIST_URL} named no tiles; nothing written")
        _write(list_path, render_list(names))
        print(f"wrote {list_path.name}: {len(names)} tiles")
        return 0

    try:
        tile_list = parse_tile_list(list_path.read_text())
    except (OSError, CopernicusError) as exc:
        raise SystemExit(f"{list_path}: {exc}; run --refresh-list") from exc
    if GENERATED_MARK not in list_path.read_text():
        raise SystemExit(f"{list_path} does not carry the generated-by line")
    rows = parse_pins(pins_path.read_text(), tile_list) if pins_path.exists() else []

    if args.check:
        if args.offline:
            print(f"{pins_path.name} and {list_path.name} are well formed: {len(rows)} pin(s)")
            return 0
        problems = check_online(rows, tile_list, get_text, head or real_head)
        if problems:
            print(f"{len(problems)} problem(s):")
            for problem in problems:
                print(f"  {problem}")
            return 1
        print(f"{pins_path.name} and {list_path.name} are up to date: {len(rows)} pin(s) probed")
        return 0

    if args.max_tiles is None or args.max_tiles < 0:
        parser.error("say how many tiles to pin with --max-tiles N, or use --check")
    if args.max_tiles == 0:
        # Rewrites the file as it stands: how the empty pin file is first made.
        _write(pins_path, render_pins(rows, [row["tile"] for row in rows]))
        print(f"wrote {pins_path.name}: {len(rows)} pin(s), nothing measured")
        return 0
    ordering = order(regions or _geofabrik_regions(), tile_list, get_text)
    pinned = {row["tile"] for row in rows}
    todo = [name for name in ordering if name not in pinned][: args.max_tiles]
    measured = (today or date.today()).isoformat()
    for name in todo:
        print(f"measuring {name}", file=sys.stderr, flush=True)
        size, sha, md5 = measure(tile_url(name), stream or real_stream)
        rows.append({"tile": name, "size": size, "sha256": sha, "md5": md5, "measured": measured})
        _write(pins_path, render_pins(rows, ordering))  # a long run keeps what it measured
    _write(pins_path, render_pins(rows, ordering))
    print(f"wrote {pins_path.name}: {len(rows)} pin(s) of {len(ordering)} tiles in the order")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
