#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/reference/lora-inventory.md from the LoRa firmware sweep.

Meshtastic and MeshCore build with PlatformIO, so every supported board ships a
`boards/*.json` naming the USB identifiers its flasher looks for. That is the
same class of asset as the Debian Blend task lists and the archive's udev rules:
curated, machine-readable, maintained by the people who ship the software.

It is also the only way this catalog's `meshtastic` entry can be closed. The
maintainer's boards were lost in a flood, and "Meshtastic" was never one device
to begin with — it is firmware that runs on a hundred of them. Upstream
publishes what all hundred present, and none of them has to be on a desk.

Input: `reference/probes/lora-identifiers.tsv` from `scripts/lora-sweep.sh`.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

import yaml  # noqa: E402

PROBE = REPO_ROOT / "reference" / "probes" / "lora-identifiers.tsv"
AMBIGUITY = REPO_ROOT / "catalog" / "hardware" / "ambiguous-ids.yaml"
OUT = REPO_ROOT / "docs" / "reference" / "lora-inventory.md"

FIELDS = ("project", "board_file", "board_name", "vendor", "product", "source")


def ambiguous_ids() -> set[str]:
    if not AMBIGUITY.is_file():
        return set()
    data = yaml.safe_load(AMBIGUITY.read_text()) or {}
    return {str(e["id"]) for e in data.get("identifiers") or []}


def main() -> int:
    if not PROBE.is_file():
        print("no LoRa sweep output; run scripts/lora-sweep.sh", file=sys.stderr)
        return 1

    rows = [
        dict(zip(FIELDS, line.split("\t"), strict=True))
        for line in PROBE.read_text(errors="replace").splitlines()
        if len(line.split("\t")) == len(FIELDS)
    ]
    if not rows:
        print(f"{PROBE} has no parseable rows", file=sys.stderr)
        return 1

    boards: dict[str, set[str]] = defaultdict(set)
    projects: dict[str, set[str]] = defaultdict(set)
    for row in rows:
        if row["source"] != "platformio":
            continue
        pair = f"{row['vendor']}:{row['product']}"
        board = row["board_name"] or row["board_file"]
        boards[pair].add(f"{row['project']}:{board}")
        projects[row["project"]].add(board)

    udev_pairs = {f"{r['vendor']}:{r['product']}" for r in rows if r["source"] == "udev"}
    total_boards = sum(len(v) for v in projects.values())
    shared = {p: b for p, b in boards.items() if len(b) > 1}
    flagged = ambiguous_ids()

    ranked = sorted(boards.items(), key=lambda kv: -len(kv[1]))
    top_share = sum(len(b) for _, b in ranked[:6])

    lines = [
        "# LoRa mesh hardware identifiers",
        "",
        "Generated by `scripts/gen_lora_inventory.py` from the sweep in",
        "`scripts/lora-sweep.sh`. Do not edit by hand — regenerate.",
        "",
        f"**Generated:** {date.today().isoformat()}  ",
        f"**Board definitions read:** {total_boards} across {', '.join(sorted(projects))}  ",
        f"**Distinct USB identifiers:** {len(boards)}  ",
        f"**Identifiers claimed by more than one board:** {len(shared)}  ",
        f"**Already flagged ambiguous:** {len(set(boards) & flagged)} of {len(boards)}",
        "",
        "## Why this source exists",
        "",
        "Meshtastic and MeshCore build with PlatformIO, so every supported board "
        "ships a `boards/*.json` naming the identifiers its flasher looks for. "
        "Curated, machine-readable, and maintained by the people who ship the "
        "firmware — the same reasons Debian's udev rules were worth mining.",
        "",
        "It is also the only way this catalog's `meshtastic` entry can be "
        "closed. The maintainer's boards were lost in a flood, and *Meshtastic "
        "was never one device* — it is firmware that runs on a hundred. Upstream "
        "publishes what all hundred present, and none has to be on a desk.",
        "",
        "## The finding",
        "",
        f"**{total_boards} board definitions. {len(boards)} identifiers. The top "
        f"six cover {top_share} of them.**",
        "",
        "That is the D-028 argument arriving from a third independent direction, "
        "and in its most extreme form yet. The Debian sweep found bridge chips "
        "shared by unrelated products; this finds an entire product category "
        "built on a handful of modules, where the identifier tells you which "
        "*module* a board uses and nothing whatever about which board it is.",
        "",
        "| Identifier | Boards | Flagged | Examples |",
        "|---|---:|:---:|---|",
    ]
    for pair, board_set in ranked[:15]:
        mark = "yes" if pair in flagged else "**no**"
        examples = ", ".join(sorted(board_set)[:3])
        lines.append(f"| `{pair}` | {len(board_set)} | {mark} | {examples} |")

    lines += [
        "",
        f"{len(boards) - len(shared)} identifiers are claimed by exactly one "
        "board definition. Those are the ones a udev rule could safely name — "
        "and being single-use in *this* dataset is not proof of being "
        "single-use in the world, which is why they are not promoted to safe "
        "on that basis alone.",
        "",
        "## What this does not settle",
        "",
        "**A board definition is what the flasher matches, not necessarily what "
        "the board reports.** These identifiers come from firmware build "
        "metadata; a running board's descriptor may carry a manufacturer or "
        "product string the JSON never mentions, and that string is exactly what "
        "would make a safe symlink possible. Only a capture shows it.",
        "",
        "So this closes the *identifier* question for a hundred boards and "
        "leaves the *distinguishability* question open for all of them. The "
        f"{len(udev_pairs)} identifiers taken from udev rules shipped alongside "
        "the firmware are on the same footing.",
        "",
        "**Nothing here is `maintainer_verified`.** D-027 keeps that separate: "
        "upstream metadata is good evidence that an identifier is correct and no "
        "evidence at all that anyone here has run the hardware.",
        "",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}: {total_boards} boards, {len(boards)} identifiers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
