#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/reference/console-coverage.md: every CLI verb against the console.

The verbs are read from the argparse tree (``cli.main.build_parser``), the way
``gen_json_reference.py`` reads the documents, never listed here. Each is looked
up in ``hammunition.console.coverage``: covered by a screen, uncovered with the
issue that will add it, or exempt with a reason. A verb in none of the three is
an error naming it, so a new verb cannot ship unclassified (#323).

Usage:
    scripts/gen_console_coverage.py            # regenerate
    scripts/gen_console_coverage.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.cli.main import build_parser  # noqa: E402
from hammunition.console.coverage import COVERED, EXEMPT, UNCOVERED, Verb  # noqa: E402

OUT = REPO_ROOT / "docs" / "reference" / "console-coverage.md"
HEADER = "<!-- Generated by scripts/gen_console_coverage.py. Do not edit by hand -->"


def cli_verbs(parser: argparse.ArgumentParser | None = None) -> list[Verb]:
    """Every runnable verb, in the order the parser declares them. A group whose
    subcommand is optional (`time`, `services`) is a verb of its own as well."""
    found: list[Verb] = []

    def walk(p: argparse.ArgumentParser, path: Verb) -> None:
        subs = [a for a in p._actions if isinstance(a, argparse._SubParsersAction)]
        if not subs:
            found.append(path)
            return
        if path and not subs[0].required:
            found.append(path)
        for name, child in subs[0].choices.items():
            walk(child, (*path, name))

    walk(parser or build_parser(), ())
    return found


def unclassified(verbs: list[Verb]) -> list[Verb]:
    return [v for v in verbs if v not in COVERED and v not in UNCOVERED and v not in EXEMPT]


def render() -> str:
    verbs = cli_verbs()
    missing = unclassified(verbs)
    if missing:
        names = ", ".join("`hammunition " + " ".join(v) + "`" for v in missing)
        raise SystemExit(
            f"gen_console_coverage: {names} is in the CLI and in none of COVERED, UNCOVERED "
            "or EXEMPT in src/hammunition/console/coverage.py"
        )
    known = set(verbs)
    stale = [v for v in (*COVERED, *UNCOVERED, *EXEMPT) if v not in known]
    if stale:
        raise SystemExit(
            "gen_console_coverage: classified but not in the CLI: "
            + ", ".join(" ".join(v) for v in stale)
        )
    lines = [
        HEADER,
        "",
        "# Console coverage",
        "",
        "The console is meant to configure and administer all of Hammunition (#323). "
        "This page is the count: every verb the CLI declares, read from its argparse tree, "
        "against the console screen that offers it. A verb with no screen names the issue "
        "that will add one. `tests/console/test_coverage.py` fails when the CLI gains a verb "
        "nobody classified, when a screen listed here does not mention its verb, and when "
        "the uncovered list grows.",
        "",
        f"**{len(COVERED)} covered, {len(UNCOVERED)} not yet, {len(EXEMPT)} exempt, "
        f"{len(verbs)} verbs in all.**",
        "",
        "Covered here means a screen reads the verb's `--json` document or runs it in a "
        "pane after showing the exact command; the console holds no install logic and never "
        "answers a consent gate (D-021, D-059). It says nothing about how well the screen "
        "was exercised on hardware.",
        "",
        "| Verb | Console path |",
        "|---|---|",
    ]
    for v in verbs:
        name = "`hammunition " + " ".join(v) + "`"
        if v in COVERED:
            cell = f"{COVERED[v][0]} (`src/hammunition/console/{COVERED[v][1]}`)"
        elif v in UNCOVERED:
            issue, screen = UNCOVERED[v]
            cell = f"no console path yet: {screen}, {issue}"
        else:
            cell = f"not offered: {EXEMPT[v]}"
        lines.append(f"| {name} | {cell} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the page is out of date")
    args = ap.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(REPO_ROOT)} is stale: run scripts/gen_console_coverage.py")
            return 1
        print(f"{OUT.relative_to(REPO_ROOT)} is up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
