#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the USGS 3DEP 1/3-arc-second tile list.  D-068, amended 2026-10-01.

``catalog/data/usgs-3dep-tiles.txt`` names every current 3DEP 1/3" tile,
one per line:

    USGS_13_<nYYwXXX> <size> <etag>

so the plan can choose a region's tiles, print their sizes and check each
download against its publisher's ETag with no network. One input: a listing
of the ``prd-tnm`` bucket's ``StagedProducts/Elevation/13/TIFF/current/``
prefix. Only each folder's own tile, ``<t>/USGS_13_<t>.tif``, is carried;
the metadata, thumbnails and any dated copy beside it are not. The header
records the newest object's ``LastModified`` date (D-031: an input's date,
never the day this ran).

    scripts/gen_3dep_tiles.py --fetch                  # a listing, nothing downloaded
    scripts/gen_3dep_tiles.py --fetch --listing L      # from a saved listing
    scripts/gen_3dep_tiles.py --save-listing L
    scripts/gen_3dep_tiles.py --check [--offline]

``--check --offline`` checks the file's shape; plain ``--check`` also lists
the bucket and exits 1 naming each carried tile that is gone or whose size
or ETag changed. A new tile is counted, not failed. The weekly pin-review
job runs ``--check``; the test suite runs ``--check --offline``.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from collections.abc import Callable, Iterable, Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.copernicus import CopernicusError  # noqa: E402
from hammunition.usgs3dep import BUCKET, PREFIX, TileRow, parse_tile_list  # noqa: E402

LIST = REPO_ROOT / "catalog" / "data" / "usgs-3dep-tiles.txt"
GENERATED_MARK = "GENERATED by scripts/gen_3dep_tiles.py"
TIMEOUT = 60.0
S3 = "{http://s3.amazonaws.com/doc/2006-03-01/}"
_OBJECT = re.compile(rf"{re.escape(PREFIX)}([ns]\d{{2}}[ew]\d{{3}})/USGS_13_\1\.tif")
_COUNT = re.compile(r"# tiles: (\d+), newest object (\d{4}-\d{2}-\d{2})")

HEADER = """\
# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: CC0-1.0

# {mark} --fetch. Do not edit by hand.
#
# Every current USGS 3DEP 1/3-arc-second elevation tile (public domain), from
# a listing of the prd-tnm bucket's {prefix} prefix, one per line: the tile's
# name (by its north-west corner), its size in bytes and its S3 ETag. Each
# download is checked against this ETag, re-asked with a HEAD at plan time
# ("MD5 from the publisher's object metadata; not pinned by Hammunition").
#
# tiles: {count}, newest object {newest}
#
# Regenerate: scripts/gen_3dep_tiles.py --fetch
# Check:      scripts/gen_3dep_tiles.py --check (a listing, no download)
"""


class GeneratorError(Exception):
    """An input could not be read, or the carried file is not what it claims."""


@dataclass(frozen=True)
class Built:
    rows: tuple[TileRow, ...]
    newest: str


Entry = tuple[str, int, str, str]
"""(key, size, etag, last-modified) of one object in a listing."""


def build(entries: Iterable[Entry]) -> Built:
    rows: dict[str, TileRow] = {}
    newest = ""
    for key, size, etag, modified in entries:
        match = _OBJECT.fullmatch(key)
        if match is None:
            continue
        name = f"USGS_13_{match.group(1)}"
        rows[name] = TileRow(name, size, etag.strip().strip('"'))
        newest = max(newest, modified[:10])
    return Built(tuple(rows[name] for name in sorted(rows)), newest)


def render(built: Built) -> str:
    body = "".join(f"{r.name} {r.size} {r.etag}\n" for r in built.rows)
    return (
        HEADER.format(
            mark=GENERATED_MARK, prefix=PREFIX, count=len(built.rows), newest=built.newest
        )
        + body
    )


def check_shape(text: str) -> Built:
    if GENERATED_MARK not in text:
        raise GeneratorError(f"{LIST} lacks the line saying it is generated")
    count = _COUNT.search(text)
    if count is None:
        raise GeneratorError(f"{LIST} has no `# tiles:` header line")
    try:
        rows = parse_tile_list(text)
    except CopernicusError as exc:
        raise GeneratorError(f"{LIST}: {exc}") from exc
    names = [line.split()[0] for line in text.splitlines() if line.startswith("USGS_13_")]
    if names != sorted(names):
        raise GeneratorError(f"{LIST}: the rows are not sorted; regenerate it")
    if int(count.group(1)) != len(rows):
        raise GeneratorError(
            f"{LIST}: the header counts {count.group(1)} tiles and the file has "
            f"{len(rows)}; it was edited by hand. Regenerate it"
        )
    return Built(tuple(rows[n] for n in sorted(rows)), count.group(2))


def check_online(carried: Sequence[TileRow], live: Sequence[TileRow]) -> list[str]:
    """What breaks an install: a carried tile that is gone, or whose size or ETag changed."""
    found = {r.name: r for r in live}
    problems: list[str] = []
    for row in carried:
        now = found.get(row.name)
        if now is None:
            problems.append(f"{row.name}: no longer in the bucket")
        elif (now.size, now.etag) != (row.size, row.etag):
            problems.append(
                f"{row.name}: the bucket has {now.size} bytes, ETag {now.etag}; the list "
                f"has {row.size}, {row.etag}"
            )
    return problems


def _opener() -> urllib.request.OpenerDirector:
    """HTTP(S) only, no redirect handler: the bucket answers directly."""
    opener = urllib.request.OpenerDirector()
    opener.add_handler(urllib.request.HTTPHandler())
    opener.add_handler(urllib.request.HTTPSHandler())
    return opener


def _get(url: str) -> bytes:
    if not url.startswith(BUCKET + "/"):
        raise GeneratorError(f"refusing {url!r}: only {BUCKET} is asked")
    request = urllib.request.Request(url, headers={"User-Agent": "hammunition"})
    try:
        response = _opener().open(request, timeout=TIMEOUT)
    except (urllib.error.URLError, OSError) as exc:
        raise GeneratorError(f"{url} could not be reached: {exc}") from exc
    if response is None:  # pragma: no cover - no handler claimed the scheme
        raise GeneratorError(f"no handler would ask {url!r}")
    with response:
        if response.status != 200:
            raise GeneratorError(f"{url} answered HTTP {response.status}")
        body: bytes = response.read()
        return body


def list_bucket(get: Callable[[str], bytes] = _get) -> Iterator[Entry]:
    token: str | None = None
    while True:
        query = {"list-type": "2", "prefix": PREFIX}
        if token:
            query["continuation-token"] = token
        root = ET.fromstring(get(f"{BUCKET}/?{urllib.parse.urlencode(query)}"))
        for item in root.findall(f"{S3}Contents"):
            fields = [item.find(f"{S3}{n}") for n in ("Key", "Size", "ETag", "LastModified")]
            if any(f is None for f in fields):
                raise GeneratorError("a listing entry lacks its Key, Size, ETag or LastModified")
            key, size, etag, modified = (f.text or "" for f in fields if f is not None)
            yield key, int(size or "0"), etag, modified
        truncated = root.find(f"{S3}IsTruncated")
        if truncated is None or truncated.text != "true":
            return
        following = root.find(f"{S3}NextContinuationToken")
        if following is None or not following.text:
            raise GeneratorError("a truncated listing page has no continuation token")
        token = following.text


def read_listing(path: Path) -> list[Entry]:
    entries: list[Entry] = []
    for number, line in enumerate(path.read_text().splitlines(), 1):
        parts = line.split("\t")
        if len(parts) != 4 or not parts[1].isdigit():
            raise GeneratorError(f"{path}: line {number} is not key, size, etag, modified")
        entries.append((parts[0], int(parts[1]), parts[2], parts[3]))
    return entries


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--fetch", action="store_true", help="regenerate the list")
    mode.add_argument("--check", action="store_true", help="check the carried list")
    mode.add_argument("--save-listing", type=Path, metavar="FILE", help="save a bucket listing")
    parser.add_argument("--offline", action="store_true", help="with --check: shape only")
    parser.add_argument("--listing", type=Path, help="with --fetch: a saved listing")
    args = parser.parse_args(argv)
    try:
        if args.save_listing:
            entries = list(list_bucket())
            args.save_listing.write_text("".join("\t".join(map(str, e)) + "\n" for e in entries))
            print(f"saved {len(entries)} objects to {args.save_listing}")
            return 0
        if args.fetch:
            entries = read_listing(args.listing) if args.listing else list(list_bucket())
            built = build(entries)
            LIST.write_text(render(built))
            print(f"wrote {LIST.relative_to(REPO_ROOT)}: {len(built.rows)} tiles")
            return 0
        carried = check_shape(LIST.read_text())
        print(f"{LIST.relative_to(REPO_ROOT)} is well formed: {len(carried.rows)} tiles")
        if args.offline:
            return 0
        live = build(list_bucket()).rows
        added = len({r.name for r in live} - {r.name for r in carried.rows})
        if added:
            print(f"{added} tile(s) are new in the bucket; --fetch picks them up")
        problems = check_online(carried.rows, live)
        if problems:
            print(f"{len(problems)} carried tile(s) no longer match the bucket:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            print("Regenerate: scripts/gen_3dep_tiles.py --fetch", file=sys.stderr)
            return 1
        print("every carried tile is in the bucket with its size and ETag")
        return 0
    except (GeneratorError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
