#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/applications.md: every application, grouped by activity.

The package reference (`docs/packages/index.md`) lists the catalog by tag. This
page lists it the way the desktop menu is laid out (D-050, D-055): the
vocabulary's eight activity groups in a newcomer's reading order, one section
per tag, and for each application whether a profile installs it or it is
installed by name only. Both come from `catalog/categories.yaml`, the
manifests and the profiles, so the page cannot drift from them.

Usage:
    scripts/gen_application_directory.py            # write the page
    scripts/gen_application_directory.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.manifest.load import load_catalog, load_profiles  # noqa: E402
from hammunition.manifest.schema import PackageManifest, Status  # noqa: E402
from hammunition.menus import load_vocabulary  # noqa: E402

OUT = REPO_ROOT / "docs" / "applications.md"

HEADER = """\
<!-- Generated by scripts/gen_application_directory.py. Do not edit by hand -->

# Applications by activity

Every application the catalog carries, laid out the way the desktop menu is: one
chapter per activity, one section per thing a person looks for. **{count}
applications.** A program with several tags is listed under each.

Each entry links to its page, which says what it does and why you would want it,
what to configure first, known problems, how it installs and where to get help.
After the dash: **in `profile`** means `hammunition install PROFILE` brings it
in; **by name only** means no profile includes it, so
`hammunition install NAME` is how you ask for it. *(retired)* marks a unit the
catalog keeps for the record. The [package reference](packages/index.md) lists
the same applications by bare tag, and the [profiles](profiles/index.md) say
what each bundle is for. For the five activities with a hub page, GPS and
time, APRS, Meshtastic, Reticulum and MeshCore, start from the
[activity hubs](activities/index.md).
"""


def render(
    manifests: dict[str, PackageManifest],
    vocabulary_path: Path,
    profiles: dict[str, list[str]],
) -> str:
    vocab = load_vocabulary(vocabulary_path)
    titles = {c.name: c for c in vocab.categories}
    by_tag: dict[str, list[str]] = {}
    for name in sorted(manifests):
        for tag in manifests[name].categories:
            by_tag.setdefault(tag, []).append(name)
    grouped = {c for g in vocab.groups for c in g.categories}
    stray = sorted(set(by_tag) - grouped)
    if stray:
        raise SystemExit(f"tags in no group of the vocabulary: {', '.join(stray)}")

    in_profiles: dict[str, list[str]] = {}
    for pname, members in profiles.items():
        for member in members:
            in_profiles.setdefault(member, []).append(pname)

    out = [HEADER.format(count=len(manifests))]
    for group in vocab.groups:
        out.append(f"## {group.title}\n")
        out.append(f"{group.summary}\n")
        for tag in group.categories:
            members = by_tag.get(tag, [])
            if not members:
                continue
            cat = titles[tag]
            out.append(f"### {cat.title or tag}\n")
            out.append(f"{cat.summary}\n")
            for name in members:
                m = manifests[name]
                retired = " *(retired)*" if m.status is Status.retired else ""
                where = in_profiles.get(name)
                installed = (
                    "in " + ", ".join(f"[`{p}`](profiles/{p}.md)" for p in sorted(where))
                    if where
                    else "by name only"
                )
                out.append(f"- [{name}](packages/{name}.md){retired} — {m.summary} ({installed})")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    manifests = load_catalog(REPO_ROOT / "catalog" / "packages")
    loaded = load_profiles(REPO_ROOT / "catalog" / "profiles", manifests)
    profiles = {name: list(p.packages) for name, p in loaded.items()}
    body = render(manifests, REPO_ROOT / "catalog" / "categories.yaml", profiles)

    rel = OUT.relative_to(REPO_ROOT)
    if args.check:
        if not OUT.exists() or OUT.read_text() != body:
            print(f"{rel} is out of date; run scripts/gen_application_directory.py")
            return 1
        print(f"{rel} is up to date")
        return 0
    OUT.write_text(body)
    print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
