#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/reference/udev-inventory.md from the archive-wide udev sweep.

Follows `gen_blend_inventory.py`: parse machine-readable upstream data into a
committed document, never hand-edit the result. The Blend task lists and a
distribution's udev rules are the same kind of asset -- curated, maintained,
and nobody in this space has mined either.

**Why this is a method and not a fix.** The `rtl-sdr` entry carried three
identifiers; Debian's own `librtlsdr0` rule carries 42. The missing 39 were
Hauppauge, Terratec, Dexatek and Gigabyte sticks -- RTL2832U underneath, owned
by real people. Each one meant a working device with no `/dev` symlink and
nothing anywhere explaining why: the exact failure this catalog refuses to guess
its way into, arrived at by omission instead.

The question this document answers is whether that ratio holds anywhere else.

Input: `reference/probes/udev-<target>.tsv` from `scripts/run-udev-sweep.sh`.
"""

from __future__ import annotations

import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.manifest.load import load_hardware  # noqa: E402

PROBES = REPO_ROOT / "reference" / "probes"
OUT = REPO_ROOT / "docs" / "reference" / "udev-inventory.md"

# Sections whose packages plausibly describe hardware this project cares about.
# Everything is swept; this only decides what gets a detailed table versus a
# counted line, and the split is stated in the document so it is not a silent cap.
RF_SECTIONS = {"hamradio", "electronics", "comm", "embedded", "libs", "science", "net", "misc"}

FIELDS = (
    "package",
    "section",
    "rules_file",
    "vendor",
    "product",
    "symlink",
    "comment",
    "vendor_name",
    "product_name",
    "enabled",
    "disabled_reason",
)


def read_rows(path: Path, *, enabled_only: bool = True) -> list[dict[str, str]]:
    """Rows from the sweep.

    Disabled rules are excluded by default and counted separately: a rule a
    distribution shipped and commented out is evidence about an identifier, not
    a claim that the identifier is supported, and mixing the two would inflate
    every coverage number in this document by thirteen.
    """
    rows = []
    for line in path.read_text(errors="replace").splitlines():
        parts = line.split("\t")
        if len(parts) != len(FIELDS):
            continue
        row = dict(zip(FIELDS, parts, strict=True))
        if enabled_only and row["enabled"] == "0":
            continue
        rows.append(row)
    return rows


def catalog_identifiers() -> set[tuple[str, str]]:
    """Every (vendor, product) the catalog already carries."""
    classes, devices = load_hardware(REPO_ROOT / "catalog" / "hardware")
    return {
        (usb.vendor.lower(), usb.product.lower())
        for entry in (*classes.values(), *devices.values())
        for usb in entry.usb_ids
        if usb.product
    }


def render(target: str, rows: list[dict[str, str]], held: set[tuple[str, str]]) -> str:
    pairs = {(r["vendor"], r["product"]) for r in rows}
    new = pairs - held
    by_package: dict[str, set[tuple[str, str]]] = defaultdict(set)
    section_of: dict[str, str] = {}
    for row in rows:
        by_package[row["package"]].add((row["vendor"], row["product"]))
        section_of[row["package"]] = row["section"] or "(none)"

    sections = Counter(section_of[p] for p in by_package)
    rf_packages = sorted(
        (p for p in by_package if section_of[p] in RF_SECTIONS),
        key=lambda p: len(by_package[p] - held),
        reverse=True,
    )

    lines = [
        "# udev identifier inventory",
        "",
        "Generated by `scripts/gen_udev_inventory.py` from the sweep in",
        "`scripts/udev-sweep.sh`. Do not edit by hand — regenerate.",
        "",
        f"**Swept:** {date.today().isoformat()}, `{target}`  ",
        f"**Packages shipping udev rules:** {len(by_package)}  ",
        f"**Distinct USB identifiers found:** {len(pairs)}  ",
        f"**Already in our hardware catalog:** {len(pairs & held)}  ",
        f"**Available and not yet carried:** {len(new)}",
        "",
        "## What this is",
        "",
        "A distribution's udev rules are a primary source about hardware we will "
        "never own, written and maintained by the people who ship the drivers. "
        "They are the same kind of asset as the Debian Blend task lists: curated, "
        "machine-readable, and unmined by anyone in this space.",
        "",
        "The `rtl-sdr` entry is why this exists. It carried three identifiers "
        "and Debian's `librtlsdr0` rule carries 42 — the missing 39 being "
        "rebadged DVB-T sticks from Hauppauge, Terratec, Dexatek and Gigabyte, "
        "all RTL2832U underneath. Every one of those meant a working device with "
        "no `/dev` symlink and no error message anywhere in the chain, which is "
        "the failure this catalog refuses to *guess* its way into, reached by "
        "omission instead.",
        "",
        "**Nothing is filtered out of the sweep.** Every package in the archive "
        "that ships a udev rule is downloaded and read — a curated shortlist is "
        "how the `rtl-sdr` gap happened in the first place. The section split "
        "below decides only what gets a detailed table.",
        "",
        "## By archive section",
        "",
        "| Section | Packages | Identifiers | Not yet carried |",
        "|---|---:|---:|---:|",
    ]
    for section, count in sections.most_common():
        section_pairs: set[tuple[str, str]] = set()
        for package in by_package:
            if section_of[package] == section:
                section_pairs |= by_package[package]
        mark = "**" if section in RF_SECTIONS else ""
        lines.append(
            f"| {mark}{section}{mark} | {count} | {len(section_pairs)} "
            f"| {len(section_pairs - held)} |"
        )
    lines += [
        "",
        "Bold sections are the ones detailed below. The others are printers, "
        "scanners, storage, input devices and desktop plumbing — swept and "
        "counted, not tabulated.",
        "",
        "## Packages worth mining",
        "",
        "Ordered by how many identifiers they carry that we do not.",
        "",
        "| Package | Section | Rule file | Identifiers | Not yet carried |",
        "|---|---|---|---:|---:|",
    ]
    for package in rf_packages:
        missing = by_package[package] - held
        if not missing:
            continue
        rule = next(r["rules_file"] for r in rows if r["package"] == package)
        lines.append(
            f"| `{package}` | {section_of[package]} | `{rule}` "
            f"| {len(by_package[package])} | **{len(missing)}** |"
        )

    carried = [p for p in rf_packages if not (by_package[p] - held)]
    if carried:
        lines += [
            "",
            f"Fully carried already: {', '.join(f'`{p}`' for p in sorted(carried))}.",
        ]

    lines += [
        "",
        "## What the first sweep found",
        "",
        "Curated, like the blocking assessment in `gen_hardware_gaps.py`: the "
        "counts above are measured, this section is judgement.",
        "",
        "**Two gaps closed without owning anything.**",
        "",
        '- **LimeSDR.** The entry said *"no USB identifier confirmed, and the '
        "maintainer does not own the hardware to confirm one\"*. Debian's "
        "`limesuite-udev` ships `64-limesuite.rules`, which names the board: "
        "`1d50:6108`, plus the FT601 the Mini uses. Now `status: supported` with "
        "no `maintainer_verified` — the D-027 shape exactly.",
        "- **Flipper Zero.** Debian packages `qflipper` and its rule names all "
        "three modes. A device the catalog should obviously have carried, "
        "surfaced by a sweep rather than by someone remembering it.",
        "",
        "**The hazard, which is the mirror image of the gap this method fixed.**",
        "",
        "Not every identifier in a rule identifies the device the rule is for. "
        "`64-limesuite.rules` also lists `0403:6001` (FTDI FT232 serial) and "
        "`04b4:8613` (the stock Cypress FX2 development kit); LimeSuite matches "
        "them because it *probes*, not because they mean LimeSDR. A `SYMLINK` on "
        "`0403:6001` would name every FTDI adapter on the machine `/dev/limesdr`.",
        "",
        "`0483:df11` is the sharper case: it is STMicroelectronics' generic "
        "STM32 DFU identifier, and this sweep found it in **both** `qflipper`'s "
        "rule and `dmrconfig`'s, where it is a TYT MD-UV380 radio. Two unrelated "
        "devices, one pair. It is safe as a firmware target, where the operator "
        "chose the device, and unsafe as a symlink rule, where the kernel matches "
        "whatever is attached — so the Flipper entry records it under `firmware` "
        "and not under `usb_ids`.",
        "",
        "Under-matching is silent and over-matching is silent. **A sweep produces "
        "candidates, not answers**, and the judgement about which is which is the "
        "part that cannot be generated.",
        "",
        "**Still on the table**, in rough order of value to this project:",
        "",
        "| Source | Identifiers | What it is |",
        "|---|---:|---|",
        "| `qdmr`, `dmrconfig` | 3 each | DMR radio programming — TYT MD-UV380, Baofeng RD-5R/TD-5R |",
        "| `gpsd` | 11 | GPS receivers: u-blox 5/6/7/8, Garmin, DeLorme. CLAUDE.md names GPS as a hardware need |",
        "| `gr-funcube` | 2 | FUNcube Dongle Pro and Pro+ |",
        "| `spectools` | 9 | MetaGeek Wi-Spy 2.4 GHz spectrum analysers |",
        '| `direwolf` | 1 | The "All In One Cable" packet interface |',
        "| `tucnak` | 3 | OK1ZIA contest hardware and an antenna rotator |",
        "| `libsigrok4t64` | 88 | Logic analysers and bench instruments — a plausible `electronics` profile |",
        "| `openocd`, `stlink-tools`, `avrdude`, `flashrom`, `openfpgaloader` | 200+ | Programmers and flashers, for a hardware-hacking profile |",
        "",
        "The 1,800-odd remaining identifiers are printers, scanners, cameras, "
        "game controllers and desktop plumbing. Counted above so the number is "
        "honest, and deliberately not mined: an identifier is only worth carrying "
        "when a device entry gives it a purpose.",
        "",
        "## How to use this",
        "",
        "An identifier here is **evidence, not a device entry**. Adding one means "
        "deciding which device or class it belongs to and writing the prose that "
        "makes it useful — this document says what is available, not what is "
        "already decided.",
        "",
        "Every identifier added from a sweep cites the rule file it came from in "
        "its `evidence` field, exactly as a capture from real hardware cites the "
        "`lsusb` that produced it. Both are primary sources; neither is a guess.",
        "",
        "This closes gaps for hardware nobody here owns, which is most of it. It "
        "does **not** make a device `maintainer_verified` — that is a separate "
        "claim about whether anyone ran it, and D-027 keeps the two apart.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    probes = sorted(PROBES.glob("udev-*.tsv"))
    probes = [p for p in probes if p.stat().st_size > 0]
    if not probes:
        print(
            "no sweep output found. Run: scripts/run-udev-sweep.sh debian-13",
            file=sys.stderr,
        )
        return 1
    probe = probes[0]
    target = probe.stem.removeprefix("udev-")
    rows = read_rows(probe)
    if not rows:
        print(f"{probe} has no parseable rows", file=sys.stderr)
        return 1
    OUT.write_text(render(target, rows, catalog_identifiers()))
    print(f"wrote {OUT.relative_to(REPO_ROOT)} from {probe.name} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
