#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Build the ambiguous-identifier dataset from measured evidence.  D-028.

An identifier that names a *chip* cannot safely name a `/dev` node. A udev rule
matching `10c4:ea60` alone claims every CP2102 adapter on the machine — a
rig-control cable, a GPS puck, a Meshtastic node — after whichever device the
rule was written for. The operator gets a symlink pointing at the wrong
hardware, with no error anywhere.

That is the mirror image of the gap that started this: `rtl-sdr` carried three
identifiers where Debian carries 42, so a Hauppauge stick got no symlink and no
error. **Under-matching is silent and over-matching is silent.** Neither can be
left to review, which is why the result of this script is catalog data the
schema enforces against, not a document someone is supposed to read.

Two measured sources, neither of them an opinion:

* `reference/probes/modules-alias-debian-13.tsv` — the kernel's own USB
  id → driver table, generated by `depmod`. A pair in `cp210x`'s or
  `ftdi_sio`'s table is one the kernel maintainers classified as a bridge.
* `reference/probes/udev-debian-13.tsv` — the archive-wide udev sweep. A pair
  appearing in two or more packages' rules under different device names is
  shared by construction.

Writes `catalog/hardware/ambiguous-ids.yaml` (data, CC0) and
`docs/reference/usb-ambiguity.md` (the argument and the surprises).
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field, replace
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PROBES = REPO_ROOT / "reference" / "probes"
DATA_OUT = REPO_ROOT / "catalog" / "hardware" / "ambiguous-ids.yaml"
DOC_OUT = REPO_ROOT / "docs" / "reference" / "usb-ambiguity.md"

# Kernel drivers that bind a pair because of the BRIDGE CHIP on the board, not
# because of what the board is. A pair in one of these tables identifies
# silicon. Kept explicit rather than pattern-matched on the name: `pn533_usb`
# also ends in _usb and is a device driver, and getting that backwards would
# suppress a legitimate symlink.
GENERIC_SERIAL_DRIVERS = {
    "cp210x",
    "ch341",
    "ftdi_sio",
    "pl2303",
    "cdc_acm",
    "usbserial",
    "ti_usb_3410_5052",
    "mos7840",
    "mct_u232",
    "ark3116",
    "oti6858",
    "spcp8x5",
    "f81232",
    "cp210x_usb",
    "io_edgeport",
    "keyspan",
    "belkin_sa",
    "digi_acceleport",
    "ipaq",
    "ir_usb",
    "kl5kusb105",
    "kobil_sct",
    "navman",
    "omninet",
    "qcaux",
    "safe_serial",
    "symbolserial",
    "usb_debug",
    "visor",
    "whiteheat",
    "xsens_mt",
}


# A pair living in a bridge driver's table is not automatically generic: FTDI,
# Silicon Labs and Prolific sell blocks of product ids, so a vendor's own PID is
# device-specific even though ftdi_sio must know about it. What separates the
# two is what `usb.ids` calls the pair -- a chip or function name means the pair
# describes silicon; a product name means somebody bought an id for a product.
CHIP_NAME = re.compile(
    r"UART Bridge|Serial \(UART\)|serial converter|Virtual COM Port|USB-Serial"
    r"|FIFO IC|in DFU Mode|USB <-> Serial|Serial Port|USB Serial|Converter",
    re.IGNORECASE,
)


def names_a_chip(name: str) -> bool:
    """True when usb.ids describes silicon or a function rather than a product.

    An EMPTY name counts as chip-like, and deliberately: usb.ids not knowing the
    pair is not evidence that it identifies a device. The two error directions
    here cost very different amounts -- a false positive costs one extra
    `match_product` line in a manifest, a false negative costs a symlink
    silently pointing at the wrong hardware -- so the unknown case errs safe.
    """
    return not name.strip() or bool(CHIP_NAME.search(name))


@dataclass(frozen=True)
class Finding:
    """One identifier that names a chip or a function rather than a device."""

    basis: str
    usbids: str = ""
    drivers: tuple[str, ...] = field(default_factory=tuple)
    packages: tuple[str, ...] = field(default_factory=tuple)
    names: tuple[str, ...] = field(default_factory=tuple)


def read_tsv(path: Path, fields: int) -> list[list[str]]:
    if not path.is_file():
        return []
    rows = []
    for line in path.read_text(errors="replace").splitlines():
        parts = line.split("\t")
        if len(parts) == fields:
            rows.append(parts)
    return rows


def main() -> int:
    aliases = read_tsv(PROBES / "modules-alias-debian-13.tsv", 4)
    sweep = read_tsv(PROBES / "udev-debian-13.tsv", 11)
    lora = read_tsv(PROBES / "lora-identifiers.tsv", 6)
    if not aliases:
        print("no kernel alias probe; run scripts/kernel-alias-probe.sh", file=sys.stderr)
        return 1

    driver_of: dict[tuple[str, str], set[str]] = defaultdict(set)
    kernel_name: dict[tuple[str, str], str] = {}
    for vendor, product, driver, name in aliases:
        driver_of[(vendor, product)].add(driver)
        if name:
            kernel_name[(vendor, product)] = name

    # Sweep evidence: which packages name a pair, and under what device name.
    packages_of: dict[tuple[str, str], set[str]] = defaultdict(set)
    names_of: dict[tuple[str, str], set[str]] = defaultdict(set)
    usbids_name: dict[tuple[str, str], str] = {}
    # A rule the distribution shipped and commented out, with the reason it
    # gave. Strongest evidence in the whole dataset -- see below.
    disabled_by: dict[tuple[str, str], set[str]] = defaultdict(set)
    for (
        package,
        _section,
        _rules,
        vendor,
        product,
        _link,
        comment,
        _vn,
        pn,
        enabled,
        reason,
    ) in sweep:
        key = (vendor, product)
        if enabled == "0":
            disabled_by[key].add(f"{package}: {reason}" if reason else package)
            continue
        packages_of[key].add(package)
        if comment:
            names_of[key].add(comment)
        if pn:
            usbids_name[key] = pn

    findings: dict[tuple[str, str], Finding] = {}

    # FIRST source, because it outranks every inference below it. A distribution
    # shipping a rule and switching it off is not us deducing that a pair names
    # silicon -- it is a maintainer having reached that conclusion and acted on
    # it, in a file they ship. Debian's 60-gpsd.rules says so in as many words:
    # "rule disabled in Debian as it matches too many other devices".
    for key, sources in sorted(disabled_by.items()):
        findings[key] = Finding(
            basis="distribution_disabled",
            usbids=kernel_name.get(key, usbids_name.get(key, "")),
            drivers=tuple(sorted(driver_of.get(key, ()))),
            packages=tuple(sorted(packages_of.get(key, ()))),
            names=tuple(sorted(sources)),
        )

    vendor_specific = 0
    for key, drivers in driver_of.items():
        generic = sorted(drivers & GENERIC_SERIAL_DRIVERS)
        if not generic:
            continue
        name = kernel_name.get(key, usbids_name.get(key, ""))
        if not names_a_chip(name):
            vendor_specific += 1
            continue
        if key in findings:
            # Already carried on stronger evidence; do not demote it.
            continue
        findings[key] = Finding(
            basis="kernel_generic_driver",
            usbids=name,
            drivers=tuple(generic),
            packages=tuple(sorted(packages_of.get(key, ()))),
            names=tuple(sorted(names_of.get(key, ()))),
        )

    # Third source: LoRa mesh firmware board definitions. Meshtastic and
    # MeshCore publish a PlatformIO board file per supported product, each
    # naming the identifiers its flasher looks for. A pair claimed by two or
    # more DIFFERENT boards is shared by construction -- and this is where the
    # sharing is most extreme, because a hundred products are built on a handful
    # of modules.
    boards_of: dict[tuple[str, str], set[str]] = defaultdict(set)
    for project, board_file, board_name, vendor, product, source in lora:
        if source == "platformio":
            boards_of[(vendor, product)].add(f"{project}:{board_name or board_file}")

    for key, boards in boards_of.items():
        if len(boards) < 2:
            continue
        existing = findings.get(key)
        listed = sorted(boards)[:6]
        note = (
            f"Claimed by {len(boards)} LoRa mesh board definitions across "
            f"Meshtastic and MeshCore, e.g. {', '.join(listed)}."
        )
        if existing is None:
            findings[key] = Finding(
                basis="shared_across_products",
                usbids=kernel_name.get(key, usbids_name.get(key, "")),
                drivers=tuple(sorted(driver_of.get(key, ()))),
                packages=tuple(sorted(packages_of.get(key, ()))),
                names=(note,),
            )
        else:
            findings[key] = replace(existing, names=(*existing.names, note))

    for key, packages in packages_of.items():
        if key in findings or len(packages) < 2 or len(names_of.get(key, ())) < 2:
            continue
        findings[key] = Finding(
            basis="shared_across_products",
            usbids=usbids_name.get(key, ""),
            drivers=tuple(sorted(driver_of.get(key, ()))),
            packages=tuple(sorted(packages)),
            names=tuple(sorted(names_of[key])),
        )

    write_data(findings)
    write_doc(findings, len(aliases), len(sweep), vendor_specific, len(lora))
    print(
        f"wrote {DATA_OUT.relative_to(REPO_ROOT)} and {DOC_OUT.relative_to(REPO_ROOT)}: "
        f"{len(findings)} ambiguous identifiers"
    )
    return 0


def write_data(findings: dict[tuple[str, str], Finding]) -> None:
    lines = [
        "# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC",
        "# SPDX-License-Identifier: CC0-1.0",
        "",
        "# GENERATED by scripts/gen_usb_ambiguity.py. Do not edit by hand.",
        "#",
        "# USB identifiers that name a chip or a function rather than a device, so",
        "# a udev rule matching one alone claims unrelated hardware. D-028.",
        "#",
        "# Evidence, not opinion:",
        "#   kernel_generic_driver   the kernel's modules.alias binds the pair to a",
        "#                           general-purpose USB-serial driver",
        "#   shared_across_products  the archive sweep found it in two or more",
        "#                           packages' rules naming different devices",
        "",
        "kind: ambiguity-list",
        f"generated: {date.today().isoformat()}",
        "source: debian-13",
        "identifiers:",
    ]
    for (vendor, product), info in sorted(findings.items()):
        lines.append(f'  - id: "{vendor}:{product}"')
        lines.append(f"    basis: {info.basis}")
        if info.usbids:
            lines.append(f"    usb_ids_name: {info.usbids}")
        if info.drivers:
            lines.append(f"    kernel_drivers: [{', '.join(info.drivers)}]")
        if info.packages:
            lines.append(f"    seen_in: [{', '.join(info.packages)}]")
        for name in info.names:
            lines.append(f"    # named: {name}")
    DATA_OUT.write_text("\n".join(lines) + "\n")


def write_doc(
    findings: dict[tuple[str, str], Finding],
    aliases: int,
    sweep: int,
    vendor_specific: int,
    lora: int,
) -> None:
    by_basis: dict[str, int] = defaultdict(int)
    for info in findings.values():
        by_basis[info.basis] += 1

    interesting = sorted(
        (k for k, v in findings.items() if v.basis == "shared_across_products"),
        key=lambda k: -len(findings[k].packages),
    )

    lines = [
        "# Ambiguous USB identifiers",
        "",
        "Generated by `scripts/gen_usb_ambiguity.py`. Do not edit by hand —",
        "regenerate.",
        "",
        f"**Generated:** {date.today().isoformat()}, Debian 13  ",
        f"**Kernel id→driver pairs read:** {aliases}  ",
        f"**udev rule identifiers read:** {sweep}  ",
        f"**LoRa mesh board definitions read:** {lora}  ",
        f"**Identifiers that name a chip, not a device:** {len(findings)}",
        "",
        "| Basis | Count |",
        "|---|---:|",
        f"| `distribution_disabled` | {by_basis.get('distribution_disabled', 0)} |",
        f"| `kernel_generic_driver` | {by_basis.get('kernel_generic_driver', 0)} |",
        f"| `shared_across_products` | {by_basis.get('shared_across_products', 0)} |",
        "",
        f"**{vendor_specific} pairs were considered and NOT flagged**: they sit "
        "in a bridge driver's table but `usb.ids` names a product, which means a "
        "vendor bought an identifier for a device rather than reusing the chip "
        "maker's default. `ftdi_sio` alone knows about hundreds of those.",
        "",
        "## Why this is enforced rather than reviewed",
        "",
        "A udev rule matching `10c4:ea60` alone claims **every CP2102 adapter on "
        "the machine** — a rig-control cable, a GPS puck, a Meshtastic node — "
        "after whichever device the rule was written for. The operator gets a "
        "symlink pointing at the wrong hardware and no error anywhere.",
        "",
        "That is the mirror image of the gap that started this work: `rtl-sdr` "
        "carried three identifiers where Debian carries 42, so a Hauppauge stick "
        "got no symlink and no error either. **Under-matching is silent and "
        "over-matching is silent.** Neither can be left to review, which is why "
        "this is catalog data the schema enforces against rather than a document "
        "somebody is meant to have read.",
        "",
        "`DeviceManifest` and `DeviceClass` refuse a symlink resting on an "
        "identifier marked ambiguous unless the rule also carries "
        "`match_product` or `match_serial`. Same shape as the missing "
        "`method: script` and the mandatory `sha256`: unrepresentable, not "
        "discouraged.",
        "",
        "## Where the evidence comes from",
        "",
        "**`kernel_generic_driver`** — the kernel's own `modules.alias`, "
        "generated by `depmod` from the module tree. If a pair sits in "
        "`cp210x`'s or `ftdi_sio`'s table, the kernel maintainers put it in a "
        "*bridge* driver, which is as close to an authoritative statement of "
        '"this is silicon, not a product" as exists. The driver list is '
        "explicit rather than pattern-matched on the name, because `pn533_usb` "
        "also ends in `_usb` and is a device driver — getting that backwards "
        "would suppress a legitimate symlink.",
        "",
        "**`shared_across_products`** — the archive sweep found the pair in two "
        "or more packages' rules *under different device names*. The "
        "different-names requirement matters: `libnitrokey-common` and "
        "`scdaemon` both name the same Nitrokey, which is agreement, not "
        "ambiguity.",
        "",
        "## The identifiers shared between unrelated devices",
        "",
        "The `kernel_generic_driver` findings are mostly unsurprising — they are "
        "the bridge chips. These are the ones the sweep caught by seeing the "
        "same pair used for genuinely different hardware:",
        "",
        "| Identifier | usb.ids | Packages | Named as |",
        "|---|---|---|---|",
    ]
    for key in interesting[:25]:
        info = findings[key]
        names = "; ".join(info.names)[:120]
        packages = ", ".join(f"`{p}`" for p in info.packages)
        lines.append(f"| `{key[0]}:{key[1]}` | {info.usbids or '—'} | {packages} | {names} |")

    lines += [
        "",
        "## What hardware found that this could not",
        "",
        "Three identifiers were captured against real hardware on 2026-08-26 "
        "that this list does not contain, and each one is a different limit of "
        "the method:",
        "",
        "| Identifier | Why the sweep missed it |",
        "|---|---|",
        "| `303a:1001` | Espressif's native USB-serial-JTAG. No Debian package "
        "names it and the kernel claims it by interface class, so neither source "
        "sees it. Two captures — a Clip-Boy and the ESP32-S3 inside a Free-WiLi 2 "
        "— report the same pair **and the same product string**. |",
        "| `2e8a:00c0` | A bare RP2040 running Arduino-core firmware, which is "
        "what a CatSniffer v3 presents. Claimed by `cdc_acm` on class, invisible "
        "to both sources for the same reason. |",
        "| `1a86:55d3` | Flagged correctly by the sweep — noted here because it is the "
        "one the catalog had GUESSED WRONG. badgelife carried `1a86:55d4` as a "
        '"widely reported" CH9102 identifier; the C5 Wardriver actually '
        "presents `55d3`. One digit out, and the guess is still unconfirmed. |",
        "| `2d2d:504d` | Not ambiguous at all — proxmark.org registered its own "
        "vendor id. Listed here for the opposite problem: the device supplies no "
        "product string and **no serial**, so two units are indistinguishable "
        "even to `/dev/serial/by-id/`. The identifier is fine; the descriptor is "
        "empty. |",
        "| `1fc9:000c` | Shared, and Debian's rule says so in a comment — "
        '"NXP Semiconductors DFU mode (HackRF and rad1o)". The sweep missed '
        "it because `shared_across_products` requires the pair in TWO packages, "
        "and here one rule names two devices in one comment. |",
        "| `1d50:6089` | **A false negative, not a blind spot.** The sweep saw "
        'this pair and excluded it: `usb.ids` calls it "Great Scott Gadgets '
        'HackRF One SDR", a product name, which the generator treats as '
        "evidence a vendor bought an id for one device. A HackRF Pro capture "
        "shows the successor board reuses it, differing only in product string. |",
        "",
        "The first two are honest limits — a pair no package names and no driver "
        "claims by id cannot be inferred from packages and drivers. **The third "
        "is a wrong inference**, and the useful one: a product name in `usb.ids` "
        "is evidence that an identifier once meant one device, not that it still "
        "does. Vendors reuse identifiers across a product line, and the database "
        "records the first name it was given.",
        "",
        "That rule is not tightened in response, because tightening it — treating "
        "every product-named pair as ambiguous — would flag the 777 currently "
        "excluded and make the list useless. The correct handling is what "
        "happened: the sweep produces a floor, hardware raises it, and an entry "
        "may carry a hand-written `ambiguity` block the generator never "
        "suggested. Both `hackrf-one` and `hackrf-pro` now do.",
        "",
        "## What this does not do",
        "",
        "It does not decide which device an identifier belongs to. An ambiguous "
        "pair is still the right identifier to *match on* for permissions and "
        "for firmware tools, where the operator has chosen the device — it is "
        "only unsafe as the sole basis for a name in `/dev`, where the kernel "
        "matches whatever is attached.",
        "",
        "That distinction is why `flipper-zero` records `0483:df11` under "
        "`firmware` and not under `usb_ids`, and it is stated as a rule in "
        "D-028 rather than re-derived per entry.",
        "",
    ]
    DOC_OUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
