#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate catalog/data/geofabrik-countries.yaml: which country each Geofabrik region is in.

The address-search fix (D-057 amendment, 2026-09-28): maptool files a town
under a country only by testing it against that country's closed
``admin_level=2`` boundary, and a sub-country extract carries only the
in-region pieces of it. The engine merges a closed boundary from Natural
Earth into each region before conversion, and this file says which
country's boundary: every region path in Geofabrik's region index, mapped to
the ISO 3166-1 alpha-2 codes :func:`hammunition.geofabrik.countries_from_index`
finds for it (its own codes, else its nearest ancestor's). A region with no
country above it (a continent, ``dach``, ``us-northeast``) is absent, and its
conversion merges nothing and says so.

The engine reads this file at plan time with no network, which is why it is
generated and committed rather than asked for on every install.

The index is a measurement, kept under the gitignored ``reference/``::

    scripts/gen_geofabrik_countries.py --fetch   # ask Geofabrik, then write
    scripts/gen_geofabrik_countries.py           # regenerate from the kept index
    scripts/gen_geofabrik_countries.py --check   # is the file current? writes nothing
    scripts/gen_geofabrik_countries.py --fetch --check   # the weekly CI job

``--fetch`` downloads ``index-v1-nogeom.json`` (0.51 MB, measured
2026-09-28) to ``reference/geofabrik/``; without it a missing index is an
error naming the file and the flag, never an empty table. The ``measured``
date is the index file's mtime, not the day the page was written (D-031).

``--check`` compares the ``regions:`` mapping only. The ``measured`` line
moves whenever the index is fetched again, so comparing it would make the
weekly ``--fetch --check`` red every week for no change in a region.
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.geofabrik import BASE, UrllibProbe, countries_from_index  # noqa: E402

OUT = REPO_ROOT / "catalog" / "data" / "geofabrik-countries.yaml"
INDEX = REPO_ROOT / "reference" / "geofabrik" / "index-v1-nogeom.json"
INDEX_URL = f"{BASE}/index-v1-nogeom.json"
GENERATED_MARK = "GENERATED by scripts/gen_geofabrik_countries.py"

HEADER = f"""\
# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: CC0-1.0

# {GENERATED_MARK}. Do not edit by hand.
#
# The ISO 3166-1 alpha-2 countries each Geofabrik region lies in, from the
# region index ({INDEX_URL}): a region's own
# iso3166-1:alpha2 and iso3166-2 codes, else its nearest ancestor's. The
# navit-maptool converter merges each named country's closed boundary into
# the region before maptool runs, so towns are filed under a country and
# address search finds them (D-057 amendment, 2026-09-28). A region absent
# here merges nothing, and its conversion step says so.
#
# Regenerate: scripts/gen_geofabrik_countries.py --fetch
# Check:      scripts/gen_geofabrik_countries.py --check
"""


def read_index(path: Path = INDEX) -> str:
    try:
        return path.read_text()
    except FileNotFoundError:
        raise SystemExit(
            f"{path} is missing: it is the measurement this file is generated from. "
            f"Run scripts/gen_geofabrik_countries.py --fetch to ask Geofabrik for it."
        ) from None


def measured(path: Path = INDEX) -> str:
    return datetime.date.fromtimestamp(path.stat().st_mtime).isoformat()


def render(index_json: str, when: str) -> str:
    table = countries_from_index(index_json)
    body = yaml.safe_dump(
        {
            "measured": when,
            "source": INDEX_URL,
            "regions": {region: list(codes) for region, codes in table.items()},
        },
        sort_keys=False,
        default_flow_style=None,
        width=100,
    )
    return f"{HEADER}\n{body}"


def _regions(text: str) -> object:
    data = yaml.safe_load(text)
    return data.get("regions") if isinstance(data, dict) else None


def fetch(path: Path = INDEX) -> None:
    text = UrllibProbe().text(INDEX_URL)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--fetch", action="store_true", help="ask Geofabrik for the index first")
    parser.add_argument(
        "--check", action="store_true", help="report whether the regions are current"
    )
    args = parser.parse_args(argv)
    if args.fetch:
        fetch()
    text = render(read_index(), measured())
    if args.check:
        if OUT.is_file() and _regions(OUT.read_text()) == _regions(text):
            print(f"{OUT.relative_to(REPO_ROOT)} is up to date")
            return 0
        print(
            f"{OUT.relative_to(REPO_ROOT)} is stale; run scripts/gen_geofabrik_countries.py",
            file=sys.stderr,
        )
        return 1
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO_ROOT)} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
