#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/projects.md — every upstream project the catalog installs.

The maintainer, 2026-09-30: the site should "at least link to each of the
projects". Every manifest already carries `documentation.upstream_url` (the
schema refuses one without it), so the list is catalog data and is generated,
never typed: CLAUDE.md, "any doc that duplicates manifest data by hand is a
defect".

The page is laid out the way the desktop menu is (D-050, D-054): the
vocabulary's groups in their `order`, then each group's categories in the
order the group lists them. A unit appears once, under its **first**
category — the one a toolkit's menu entry nests under too — so the page is a
list of projects, not a list of tags. Its package page lists the rest.

An upstream URL that is a distribution's package tracker rather than the
project's own site is said so in the row: it is where the catalog could find
a maintained home, and a reader deserves to know they are not on the
author's page.

Usage:
    scripts/gen_projects_page.py            # regenerate
    scripts/gen_projects_page.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

import yaml  # noqa: E402

from hammunition.manifest.load import load_catalog  # noqa: E402
from hammunition.manifest.schema import PackageManifest, Status  # noqa: E402

OUT = REPO_ROOT / "docs" / "projects.md"
CATEGORIES = REPO_ROOT / "catalog" / "categories.yaml"

# Hosts that are a distribution's page about a package, not the project's own.
DISTRIBUTION_TRACKERS = {
    "tracker.debian.org",
    "packages.debian.org",
    "salsa.debian.org",
    "launchpad.net",
}

HEADER = """\
<!-- Generated by scripts/gen_projects_page.py. Do not edit by hand -->

# The projects we install

Hammunition writes none of the radio software it installs. Every program
below is somebody else's work — often one person's, maintained for years
in their spare time — and the catalog only describes how to install it
well. This page links each one to its own home, so the credit and the
support questions go where they belong.

**{count} programs and packages** from the catalog, laid out the way the
desktop menu is. Each appears once, under its first category; its page in
the [package reference](packages/index.md) lists the others, what it
needs before it works, its known problems and where to get help with it.

Where a row says *Debian package page*, the link is the distribution's
page for the package rather than the author's own site: that was the
maintained home the catalog could find.

The six projects whose curation seeded the catalog are credited on
[Credits](credits.md).
"""


def _link_text(url: str) -> str:
    parsed = urlparse(url)
    path = parsed.path.rstrip("/")
    text = parsed.netloc + path
    return text.removeprefix("www.")


def _row(m: PackageManifest) -> str:
    url = m.documentation.upstream_url
    host = urlparse(url).netloc
    where = f"[{_link_text(url)}]({url})"
    if host in DISTRIBUTION_TRACKERS:
        where += " — *Debian package page*"
    name = f"[{m.name}](packages/{m.name}.md)"
    if m.status is Status.retired:
        name += " *(retired)*"
    summary = m.summary.replace("|", "\\|")
    return f"| {name} | {summary} | {where} |"


def render(manifests: dict[str, PackageManifest], vocabulary: dict[str, Any]) -> str:
    categories = {c["name"]: c for c in vocabulary["categories"]}
    groups = sorted(vocabulary["groups"], key=lambda g: g["order"])

    home: dict[str, list[PackageManifest]] = {}
    for m in manifests.values():
        home.setdefault(m.categories[0], []).append(m)

    out = [HEADER.format(count=len(manifests))]
    placed = 0
    for group in groups:
        members = [c for c in group["categories"] if home.get(c)]
        if not members:
            continue
        out.append(f"## {group['title']}\n")
        out.append(f"{group['summary']}\n")
        for cat in members:
            units = sorted(home[cat], key=lambda m: m.name)
            placed += len(units)
            out.append(f"### {categories[cat]['title']}\n")
            out.append("| Project | What it is | Its home |")
            out.append("|---|---|---|")
            out.extend(_row(m) for m in units)
            out.append("")
    if placed != len(manifests):
        # A first category the vocabulary's groups do not list would drop a
        # project from the page silently. tests/test_categories.py forbids
        # that already; this makes the page refuse rather than rely on it.
        raise SystemExit(f"placed {placed} of {len(manifests)} manifests; a category has no group")
    return "\n".join(out).rstrip() + "\n"


def _check_or_write(body: str, check: bool) -> int:
    if check:
        if not OUT.exists() or OUT.read_text() != body:
            print(f"{OUT.relative_to(REPO_ROOT)} is out of date; run scripts/gen_projects_page.py")
            return 1
        print(f"{OUT.relative_to(REPO_ROOT)} is up to date")
        return 0
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    manifests = load_catalog(REPO_ROOT / "catalog" / "packages")
    vocabulary = yaml.safe_load(CATEGORIES.read_text())
    return _check_or_write(render(manifests, vocabulary), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
