#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/profiles/ — one page per profile, plus an index.

CLAUDE.md's documented structure: "profiles/ — one page per profile, generated
from manifests plus prose." The profile schema already refuses a manifest
without its documentation block (what_it_installs, why_together,
deliberately_excludes, manual_configuration), which is what makes this
generator possible rather than a hand-written duplication of the YAML.

What it adds beyond the YAML: the resolved package list rendered as links into
the package reference, any consent disclosure surfaced where someone deciding
whether to install will see it, and any suggestion groups (the mail-client and
serial-terminal pickers) explained. Nothing here is hand-written; the no-op
test asserts an edit to an output file goes red naming this script.

Usage:
    scripts/gen_profile_reference.py            # regenerate
    scripts/gen_profile_reference.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.manifest.load import load_catalog, load_profiles  # noqa: E402
from hammunition.manifest.schema import ProfileManifest  # noqa: E402

CATALOG = REPO_ROOT / "catalog" / "packages"
PROFILES = REPO_ROOT / "catalog" / "profiles"
OUT = REPO_ROOT / "docs" / "profiles"

HEADER = "<!-- Generated by scripts/gen_profile_reference.py. Do not edit by hand -->"


def _pkg_link(name: str, known: set[str]) -> str:
    return f"[`{name}`](../packages/{name}.md)" if name in known else f"`{name}`"


def page(profile: ProfileManifest, known: set[str]) -> str:
    doc = profile.documentation
    lines = [
        HEADER,
        "",
        f"# Profile: {profile.name}",
        "",
        f"> {profile.summary}",
        "",
        f"**Stage:** {profile.stage}"
        + ("  ·  **consent-gated**" if profile.consent else ""),
        "",
        "## What it installs",
        "",
        doc.what_it_installs,
        "",
    ]
    if doc.disk_footprint_hint:
        lines += [f"**Disk footprint:** {doc.disk_footprint_hint}", ""]
    lines += [
        "## Why these belong together",
        "",
        doc.why_together,
        "",
        f"## Packages ({len(profile.packages)})",
        "",
        ", ".join(_pkg_link(p, known) for p in profile.packages),
        "",
        "## What it deliberately excludes",
        "",
        doc.deliberately_excludes,
        "",
        "## What you configure by hand afterward",
        "",
        doc.manual_configuration,
        "",
    ]
    if profile.consent:
        gate = profile.consent
        lines += [
            "## Consent gate",
            "",
            "This profile is **consent-gated** (D-021): it discloses a capability "
            "and requires an affirmative acknowledgement before installing. "
            f"`hammunition show {profile.name}` prints the full disclosure, and "
            f"`--yes` cannot satisfy it — a person affirms, or sets "
            f"`{gate.env_var}`.",
            "",
            "Risk categories declared:",
            "",
        ]
        lines += [f"- {line}" for line in gate.risk_lines]
        lines.append("")
    for group in profile.suggests_one_of:
        rec = f" (recommended: `{group.recommended}`)" if group.recommended else ""
        lines += [
            f"## Optional: {group.name}{rec}",
            "",
            f"{group.reason} The engine detects an existing one "
            f"(`{'`, `'.join(group.detect_commands)}`) and respects it; only when "
            f"none is found does an interactive install offer: "
            f"{', '.join(_pkg_link(o, known) for o in group.options)}. Never "
            f"installed silently; `--yes` skips with a note.",
            "",
        ]
    return "\n".join(lines)


def index(profiles: dict[str, ProfileManifest]) -> str:
    lines = [
        HEADER,
        "",
        "# Profiles",
        "",
        "Named bundles of software that belong together. Flat tags with overlap, "
        "never nested (D-003) — compose them freely. Each page is generated from "
        "the profile's manifest.",
        "",
        "| Profile | Stage | Packages | Summary |",
        "|---|---|---:|---|",
    ]
    for name in sorted(profiles):
        p = profiles[name]
        gated = " 🔒" if p.consent else ""
        lines.append(
            f"| [{name}]({name}.md){gated} | {p.stage} | {len(p.packages)} | {p.summary} |"
        )
    lines += ["", "🔒 = consent-gated (D-021).", ""]
    return "\n".join(lines)


def render() -> dict[str, str]:
    catalog = load_catalog(CATALOG)
    profiles = load_profiles(PROFILES, catalog)
    known = set(catalog)
    files = {f"{name}.md": page(p, known) for name, p in profiles.items()}
    files["index.md"] = index(profiles)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    files = render()
    if args.check:
        existing = {p.name: p.read_text() for p in OUT.glob("*.md")} if OUT.exists() else {}
        if existing != files:
            print("docs/profiles/ is out of date; run scripts/gen_profile_reference.py")
            return 1
        print(f"docs/profiles/ is up to date ({len(files)} files)")
        return 0

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    for name, body in files.items():
        (OUT / name).write_text(body)
    print(f"wrote {len(files)} files to {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
