#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/reference/json-interface.md from the document dataclasses.

The documents ``--json`` prints are the published interface front ends are
written against (D-059). A hand-written page describing them would drift the
first time a field was added, so this walks every document class under
``src/hammunition/interface/`` -- found by their ``KIND`` class variable, not
listed -- and renders each one's docstring, a table of its fields with the
text their ``described()`` call carries, and the JSON Schema pydantic derives
from the same class. The tests validate every golden document against that
schema.

Usage:
    scripts/gen_json_reference.py            # regenerate
    scripts/gen_json_reference.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import dataclasses
import inspect
import json
import sys
import types
import typing
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from pydantic import TypeAdapter  # noqa: E402

from hammunition.interface.envelope import SCHEMA, kinds  # noqa: E402

OUT = REPO_ROOT / "docs" / "reference" / "json-interface.md"
HEADER = "<!-- Generated by scripts/gen_json_reference.py. Do not edit by hand -->"

INTRO = f"""
Every command in the table below takes `--json`, before or after the verb:
`hammunition --json status` and `hammunition status --json` are the same run.
With it, the command prints **one JSON document on stdout and nothing else
there**. Everything else it would have printed -- notes, warnings, the reason
for a refusal -- goes to stderr. The exit code is the one the text run returns
(the table is in `docs/reference/cli.md`), and a run that refuses still prints
a document: its own kind when it got far enough to have one (a refused plan is
a `plan` with `outcome: "refused"`), otherwise an `error` document carrying
the exit code and everything written to stderr.

Every document starts with the same three fields:

```json
{{"schema": "{SCHEMA}", "kind": "<kind>", "engine": "<version>"}}
```

`schema` versions the whole interface. A field may be added within a major
version; removing a field or changing what one means bumps the major, and a
front end refuses a major it does not know, by name. `engine` is the installed
engine's version.

**A real install is never driven through JSON.** `install --json` and
`uninstall --json` require `--dry-run`: their document is the plan. A front
end runs the real command in the operator's own terminal, where sudo, every
consent gate (D-021) and every disclosure are the CLI's, then reads
`status --json` again. A command with no JSON form refuses `--json` with an
`error` document and runs nothing.

**These documents are for local programs, not for pasting.** `station` carries
the callsign, grid square and every other station value, because a local front
end needs them to fill a form. Do not paste one into an issue, a forum or a
chat: a callsign resolves to a name and a licence address. `doctor` and
`update` keep the count-only rule their text follows.

`--help` and `--version` under `--json` print to stderr and emit no document.
"""


def _type_name(annotation: object) -> str:
    if annotation is type(None):
        return "null"
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin in (typing.Union, types.UnionType):
        return " or ".join(_type_name(a) for a in args)
    if origin is tuple:
        return f"list of {_type_name(args[0])}"
    if origin is dict:
        return "object"
    if isinstance(annotation, type) and dataclasses.is_dataclass(annotation):
        return f"[`{annotation.__name__}`](#{annotation.__name__.lower()})"
    if annotation is str:
        return "string"
    if annotation is int:
        return "integer"
    if annotation is bool:
        return "boolean"
    return str(annotation)


def _nested(cls: type) -> list[type]:
    """Dataclasses reachable from *cls*, depth first, in field order, once each."""
    found: list[type] = []

    def walk(tp: object) -> None:
        for arg in typing.get_args(tp):
            walk(arg)
        if isinstance(tp, type) and dataclasses.is_dataclass(tp) and tp not in found:
            found.append(tp)
            for hint in typing.get_type_hints(tp).values():
                walk(hint)

    for hint in typing.get_type_hints(cls).values():
        walk(hint)
    return found


def _table(cls: type) -> list[str]:
    hints = typing.get_type_hints(cls)
    lines = ["| field | type | meaning |", "|---|---|---|"]
    for f in dataclasses.fields(cls):
        doc = str(f.metadata.get("doc", "")).replace("|", "\\|")
        lines.append(f"| `{f.name}` | {_type_name(hints[f.name])} | {doc} |")
    return lines


def render() -> str:
    found = kinds()
    out = [HEADER, "", "# The JSON interface", "", INTRO.strip(), "", "## Kinds", ""]
    out += ["| kind | document |", "|---|---|"]
    out += [f"| `{kind}` | [`{cls.__name__}`](#{kind}) |" for kind, cls in found.items()]
    out.append("")
    documented: list[type] = []
    for kind, cls in found.items():
        out += [f"### {kind}", "", inspect.cleandoc(cls.__doc__ or ""), "", *_table(cls), ""]
        for nested in _nested(cls):
            if nested in documented:
                continue
            documented.append(nested)
            out += [f"#### `{nested.__name__}`", "", inspect.cleandoc(nested.__doc__ or "")]
            out += ["", *_table(nested), ""]
        schema = json.dumps(TypeAdapter(cls).json_schema(), indent=2, ensure_ascii=False)
        out += ["<details><summary>JSON Schema</summary>", "", "```json", schema, "```"]
        out += ["", "</details>", ""]
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    content = render()
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print(
                "docs/reference/json-interface.md is out of date; run scripts/gen_json_reference.py"
            )
            return 1
        print("docs/reference/json-interface.md is up to date")
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
