#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/reference/capability-matrix.md.

CLAUDE.md: "Not every profile works everywhere. Manifests declare per-distro
support and the engine reports honest gaps rather than faking coverage."

`scripts/capability_matrix.py` answers a narrower question -- does a manifest
*resolve* to an install block on a given target -- and it answers it correctly.
What it cannot answer is whether the block would then work, and after this
catalog grew past two hundred manifests the difference stopped being academic:
most entries carry ONE unconditional apt block on purpose, because apt reports
the truth at plan time where a `when:` selector would freeze one evening's
measurement. Resolution therefore says "apt" for every target, including the
four where `sdrangel` does not exist.

This generator merges the resolution with a measured `apt-cache policy` sweep,
so a row says which targets actually offer the package rather than which
targets would try. Refresh the sweep first:

    scripts/apt-policy-sweep.sh <target> <image> reference/install-tests/catalog-apt.txt

**This is still the weaker of the two checks.** `apt-cache policy` proves the
archive offers a package; it does not prove dependency resolution succeeds.
`docs/reference/install-verification.md` is the stronger one and covers a
subset. Source and git rows are weaker again -- they say a build is declared,
not that it succeeds, and the manifests that HAVE been built say so in their
own notes.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

import yaml  # noqa: E402

from hammunition.distro import Target  # noqa: E402
from hammunition.manifest.load import load_catalog  # noqa: E402
from hammunition.manifest.schema import AptInstall, PackageManifest  # noqa: E402

CATALOG = REPO_ROOT / "catalog" / "packages"
TARGETS = REPO_ROOT / "containers" / "targets.yaml"
PROBES = REPO_ROOT / "reference" / "probes"
OUT = REPO_ROOT / "docs" / "reference" / "capability-matrix.md"

#: What a cell can say. Ordered worst to best for the summary counts.
ABSENT = "—"
NO_CANDIDATE = "apt ✗"
APT = "apt"


def targets() -> list[tuple[str, Target]]:
    data = yaml.safe_load(TARGETS.read_text())
    out = []
    for entry in data["targets"]:
        out.append(
            (
                entry["name"],
                Target(
                    distro=entry["os_release_id"],
                    version=str(entry["os_release_version"]),
                    arch=entry["arch"],
                ),
            )
        )
    return out


def availability(name: str) -> dict[str, str] | None:
    """Measured `apt-cache policy` answers for one target, or None if unswept."""
    path = PROBES / f"policy-cat-{name}.tsv"
    if not path.exists():
        return None
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        if "\t" in line:
            pkg, version = line.split("\t", 1)
            out[pkg] = version
    return out


def cell(
    m: PackageManifest, target: Target, offered: dict[str, str] | None
) -> tuple[str, list[str]]:
    """Return (cell text, missing apt package names)."""
    block = m.resolve(target.distro, target.version, target.arch)
    if block is None:
        return ABSENT, []
    install = block.install
    if not isinstance(install, AptInstall):
        return install.method, []
    if offered is None:
        return "apt ?", []
    missing = [p for p in install.packages if offered.get(p, "-") == "-"]
    return (NO_CANDIDATE if missing else APT), missing


def render(catalog: dict[str, PackageManifest]) -> str:
    names = targets()
    offered = {name: availability(name) for name, _ in names}
    swept = [n for n, o in offered.items() if o is not None]

    rows: dict[str, dict[str, str]] = {}
    gaps: dict[str, dict[str, list[str]]] = {}
    for m in sorted(catalog.values(), key=lambda m: m.name):
        rows[m.name] = {}
        for name, target in names:
            text, missing = cell(m, target, offered[name])
            rows[m.name][name] = text
            if missing:
                gaps.setdefault(m.name, {})[name] = missing

    out: list[str] = [
        "<!-- Generated by scripts/gen_capability_matrix.py. Do not edit by hand -->",
        "",
        "# Capability matrix",
        "",
        "Generated by `scripts/gen_capability_matrix.py`. Do not edit by hand —",
        "regenerate.",
        "",
        f"**Generated:** {date.today().isoformat()}  ",
        "**Method:** manifest resolution against each target's declared "
        "`(distro, version, arch)`, merged with a measured `apt-cache policy` "
        "sweep inside that target's own image.",
        "",
        "Resolution alone would overstate coverage. Most manifests here carry one",
        "unconditional apt block on purpose — apt reports the truth at plan time,",
        "where a `when:` selector would freeze one evening's measurement — so",
        "resolution says `apt` for every target including the ones where the",
        "package does not exist. The sweep is what separates those.",
        "",
        "| Cell | Meaning |",
        "|---|---|",
        f"| `{APT}` | Resolves to an apt block **and every package has a candidate**. |",
        f"| `{NO_CANDIDATE}` | Resolves to apt, and at least one package is **not in that archive**. Listed below. |",
        "| `source` / `git` | Resolves to a build. Declared, not verified here — see below. |",
        f"| `{ABSENT}` | No install block resolves. The manifest does not claim this target. |",
        "| `apt ?` | Resolves to apt and this target was not swept. |",
        "",
        "**This is the weaker of the two checks this repository runs.**",
        "`apt-cache policy` proves the archive *offers* a package; it does not",
        "prove dependency resolution succeeds. `install-verification.md` is the",
        "stronger check and covers a subset. `source` and `git` cells are weaker",
        "again: they say a build is declared, not that it succeeds. Manifests whose",
        "build HAS been run in a container say so in their own install notes.",
        "",
        "---",
        "",
        "## Summary",
        "",
    ]

    header = "| Target | " + " | ".join(("apt", "apt ✗", "build", "no block", "unswept")) + " |"
    out.append(header)
    out.append("|---|---:|---:|---:|---:|---:|")
    for target_name, _ in names:
        counts = {APT: 0, NO_CANDIDATE: 0, "build": 0, ABSENT: 0, "apt ?": 0}
        for cells in rows.values():
            value = cells[target_name]
            if value in {"source", "git", "binary", "venv", "pipx"}:
                counts["build"] += 1
            else:
                counts[value] += 1
        suffix = "" if target_name in swept else " *(unswept)*"
        out.append(
            f"| {target_name}{suffix} | {counts[APT]} | {counts[NO_CANDIDATE]} | "
            f"{counts['build']} | {counts[ABSENT]} | {counts['apt ?']} |"
        )
    out.append("")
    out.append(f"**{len(catalog)} manifests** against **{len(names)} targets**.")
    out.append("")

    if gaps:
        out.append("---")
        out.append("")
        out.append("## Resolves to apt, and the archive does not have it")
        out.append("")
        out.append(
            "Each of these is an honest gap the engine reports at plan time rather "
            "than a defect. Where a manifest expects it, its install note says so."
        )
        out.append("")
        out.append(
            "**A package behind a third-party repository appears here and is not a "
            "gap.** The sweep measures each target's stock archive; it does not add "
            "the repositories a manifest declares in `apt_repos`, because adding one "
            "is a system modification that must be shown to the operator before it "
            "happens. `code` and `codium` are the two in this catalog and they are "
            "why this paragraph exists."
        )
        out.append("")
        out.append("| Package | Target | Missing apt package(s) |")
        out.append("|---|---|---|")
        for gapped in sorted(gaps):
            for where in sorted(gaps[gapped]):
                names_missing = ", ".join(f"`{p}`" for p in gaps[gapped][where])
                out.append(f"| `{gapped}` | {where} | {names_missing} |")
        out.append("")

    out.append("---")
    out.append("")
    out.append("## Every manifest")
    out.append("")
    out.append("| Package | " + " | ".join(n for n, _ in names) + " |")
    out.append("|---" * (len(names) + 1) + "|")
    for listed in sorted(rows):
        out.append(f"| `{listed}` | " + " | ".join(rows[listed][n] for n, _ in names) + " |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    body = render(load_catalog(CATALOG))
    if args.check:
        if not OUT.exists() or _without_date(OUT.read_text()) != _without_date(body):
            print(f"{OUT.relative_to(REPO_ROOT)} is out of date; regenerate it")
            return 1
        print(f"{OUT.relative_to(REPO_ROOT)} is up to date")
        return 0
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


GENERATED_LINE = re.compile(r"^\*\*Generated:\*\*")


def _without_date(text: str) -> list[str]:
    """Compare content, not the day it was written."""
    return [ln for ln in text.splitlines() if not GENERATED_LINE.match(ln)]


if __name__ == "__main__":
    raise SystemExit(main())
