#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/reference/lora-inventory.md from the LoRa firmware sweep.

Meshtastic and MeshCore build with PlatformIO, so every supported board ships a
`boards/*.json` naming the USB identifiers its flasher looks for. That is the
same class of asset as the Debian Blend task lists and the archive's udev rules:
curated, machine-readable, maintained by the people who ship the software.

It is also the only way this catalog's `meshtastic` entry can be closed. The
maintainer's boards were lost in a flood, and "Meshtastic" was never one device
to begin with — it is firmware that runs on a hundred of them. Upstream
publishes what all hundred present, and none of them has to be on a desk.

Input: `reference/probes/lora-identifiers.tsv` from `scripts/lora-sweep.sh`.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

import yaml  # noqa: E402

from hammunition.manifest.load import load_hardware  # noqa: E402

PROBE = REPO_ROOT / "reference" / "probes" / "lora-identifiers.tsv"
AMBIGUITY = REPO_ROOT / "catalog" / "hardware" / "ambiguous-ids.yaml"
HARDWARE = REPO_ROOT / "catalog" / "hardware"
OUT = REPO_ROOT / "docs" / "reference" / "lora-inventory.md"

FIELDS = ("project", "board_file", "board_name", "vendor", "product", "source")


def product_strings() -> dict[str, set[str]]:
    """Product strings the catalog has actually read, keyed by identifier.

    Cross-referenced rather than assumed, because the answer changes what is
    worth asking a contributor for. An identifier whose product string is a
    *chip* constant — the ESP32-S3's ROM reports "USB JTAG/serial debug unit" on
    every board that uses it — cannot be disambiguated by a product string at
    all, and asking somebody to send one is asking them to confirm something
    already known three times over.
    """
    classes, devices = load_hardware(HARDWARE)
    found: dict[str, set[str]] = defaultdict(set)
    for holder in (*classes.values(), *devices.values()):
        for usb in holder.usb_ids:
            if usb.product_string and usb.product:
                found[f"{usb.vendor}:{usb.product}"].add(usb.product_string)
    return found


def ambiguous_ids() -> set[str]:
    if not AMBIGUITY.is_file():
        return set()
    data = yaml.safe_load(AMBIGUITY.read_text()) or {}
    return {str(e["id"]) for e in data.get("identifiers") or []}


def main() -> int:
    if not PROBE.is_file():
        print("no LoRa sweep output; run scripts/lora-sweep.sh", file=sys.stderr)
        return 1

    rows = [
        dict(zip(FIELDS, line.split("\t"), strict=True))
        for line in PROBE.read_text(errors="replace").splitlines()
        if len(line.split("\t")) == len(FIELDS)
    ]
    if not rows:
        print(f"{PROBE} has no parseable rows", file=sys.stderr)
        return 1

    boards: dict[str, set[str]] = defaultdict(set)
    projects: dict[str, set[str]] = defaultdict(set)
    for row in rows:
        if row["source"] != "platformio":
            continue
        pair = f"{row['vendor']}:{row['product']}"
        board = row["board_name"] or row["board_file"]
        boards[pair].add(f"{row['project']}:{board}")
        projects[row["project"]].add(board)

    udev_pairs = {f"{r['vendor']}:{r['product']}" for r in rows if r["source"] == "udev"}
    total_boards = sum(len(v) for v in projects.values())
    shared = {p: b for p, b in boards.items() if len(b) > 1}
    flagged = ambiguous_ids()

    ranked = sorted(boards.items(), key=lambda kv: -len(kv[1]))
    top_share = sum(len(b) for _, b in ranked[:6])

    lines = [
        "# LoRa mesh hardware identifiers",
        "",
        "Generated by `scripts/gen_lora_inventory.py` from the sweep in",
        "`scripts/lora-sweep.sh`. Do not edit by hand — regenerate.",
        "",
        f"**Generated:** {date.today().isoformat()}  ",
        f"**Board definitions read:** {total_boards} across {', '.join(sorted(projects))}  ",
        f"**Distinct USB identifiers:** {len(boards)}  ",
        f"**Identifiers claimed by more than one board:** {len(shared)}  ",
        f"**Already flagged ambiguous:** {len(set(boards) & flagged)} of {len(boards)}",
        "",
        "## Why this source exists",
        "",
        "Meshtastic and MeshCore build with PlatformIO, so every supported board "
        "ships a `boards/*.json` naming the identifiers its flasher looks for. "
        "Curated, machine-readable, and maintained by the people who ship the "
        "firmware — the same reasons Debian's udev rules were worth mining.",
        "",
        "It is also the only way this catalog's `meshtastic` entry can be "
        "closed. The maintainer's boards were lost in a flood, and *Meshtastic "
        "was never one device* — it is firmware that runs on a hundred. Upstream "
        "publishes what all hundred present, and none has to be on a desk.",
        "",
        "## The finding",
        "",
        f"**{total_boards} board definitions. {len(boards)} identifiers. The top "
        f"six cover {top_share} of them.**",
        "",
        "That is the D-028 argument arriving from a third independent direction, "
        "and in its most extreme form yet. The Debian sweep found bridge chips "
        "shared by unrelated products; this finds an entire product category "
        "built on a handful of modules, where the identifier tells you which "
        "*module* a board uses and nothing whatever about which board it is.",
        "",
        "| Identifier | Boards | Flagged | Examples |",
        "|---|---:|:---:|---|",
    ]
    for pair, board_set in ranked[:15]:
        mark = "yes" if pair in flagged else "**no**"
        examples = ", ".join(sorted(board_set)[:3])
        lines.append(f"| `{pair}` | {len(board_set)} | {mark} | {examples} |")

    lines += [
        "",
        f"{len(boards) - len(shared)} identifiers are claimed by exactly one "
        "board definition. Those are the ones a udev rule could safely name — "
        "and being single-use in *this* dataset is not proof of being "
        "single-use in the world, which is why they are not promoted to safe "
        "on that basis alone.",
        "",
        "## What this does not settle",
        "",
        "**A board definition is what the flasher matches, not necessarily what "
        "the board reports.** These identifiers come from firmware build "
        "metadata; a running board's descriptor may carry a manufacturer or "
        "product string the JSON never mentions, and that string is exactly what "
        "would make a safe symlink possible. Only a capture shows it.",
        "",
        "So this closes the *identifier* question for a hundred boards and "
        "leaves the *distinguishability* question open for all of them. The "
        f"{len(udev_pairs)} identifiers taken from udev rules shipped alongside "
        "the firmware are on the same footing.",
        "",
        "**Nothing here is `maintainer_verified`.** D-027 keeps that separate: "
        "upstream metadata is good evidence that an identifier is correct and no "
        "evidence at all that anyone here has run the hardware.",
        "",
        "## Which product strings are worth asking for",
        "",
        "Not all of them, and working out which is the useful part. A product "
        "string is only worth collecting where it can *distinguish* a board — "
        "and for the largest identifier family here it provably cannot.",
        "",
        "| Identifier | Boards | Product string here | Worth asking? |",
        "|---|---:|---|---|",
    ]
    known = product_strings()
    askable: set[str] = set()
    for pair, board_set in ranked:
        seen = sorted(known.get(pair, ()))
        if seen and len(board_set) > 1:
            # Read on several unrelated boards and identical every time: the
            # string belongs to the silicon, so no capture can separate them.
            verdict = "**no** — the string is the chip's, not the board's"
            shown = ", ".join(f"`{x}`" for x in seen)
        elif seen:
            verdict = "already read"
            shown = ", ".join(f"`{x}`" for x in seen)
        else:
            verdict = "**yes**"
            shown = "not read here"
            # Union, not a sum: one board claims up to four of these, and adding
            # the column would report 196 boards out of a corpus of 107.
            askable |= board_set
        lines.append(f"| `{pair}` | {len(board_set)} | {shown} | {verdict} |")

    lines += [
        "",
        f"**{len(askable)} of the {total_boards} board definitions sit behind an "
        "identifier whose product string nobody here has read.** Those are the "
        "useful captures. The "
        "ESP32-S3 family is deliberately excluded: `303a:1001` was captured "
        "three times on 2026-08-26 — a Clip-Boy, a Minino and the ESP32-S3 "
        "inside a Free-WiLi 2 — and all three reported the identical product "
        "string, `USB JTAG/serial debug unit`. That is the ROM's, not the "
        "board's. No capture of an ESP32-S3 board using native USB can "
        "distinguish it from another, which is worth knowing before asking "
        "49 boards' worth of owners for one.",
        "",
        "The nRF52840 families are the opposite case: their UF2 bootloaders are "
        "built per board, so the string is usually the board's own name. That is "
        "where a thirty-second capture buys something, and it is what "
        "`.github/ISSUE_TEMPLATE/lora-product-string.yml` asks for.",
        "",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}: {total_boards} boards, {len(boards)} identifiers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
