#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/hardware/ — one page per catalogued device, plus an index.

CLAUDE.md's documented structure: "hardware/ — per-device setup: SDRs, rigs,
CAT interfaces, GPS, LoRa." The device schema already refuses a manifest
without its documentation block (what_it_is, what_you_can_do_with_it,
setup_steps), which is what makes this generator possible rather than a
hand-written duplication of the YAML.

What it adds beyond the YAML: D-027 rendered where an operator will read it —
``status`` and ``maintainer_verified`` are separate answers to separate
questions, and every page says both; identifier ambiguity warnings surfaced
beside the identifiers they qualify; and the identification gaps stated as
prominently as the identifications, because the reason a gap is open matters
as much as the fact that it is.

Usage:
    scripts/gen_hardware_reference.py            # regenerate
    scripts/gen_hardware_reference.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.manifest.hardware import DeviceClass, DeviceManifest  # noqa: E402
from hammunition.manifest.load import load_catalog, load_hardware  # noqa: E402

HARDWARE = REPO_ROOT / "catalog" / "hardware"
CATALOG = REPO_ROOT / "catalog" / "packages"
OUT = REPO_ROOT / "docs" / "hardware"

HEADER = "<!-- Generated by scripts/gen_hardware_reference.py. Do not edit by hand -->"


def _pkg_link(name: str, known: set[str]) -> str:
    return f"[`{name}`](../packages/{name}.md)" if name in known else f"`{name}`"


def verification_line(device: DeviceManifest) -> str:
    """D-027: status and maintainer_verified are separate fields, said separately."""
    status = {
        "supported": "**supported** — the identifiers and setup recipe are believed correct",
        "untested": "**untested** — catalogued from documented sources, not yet proven here",
        "planned": "**planned** — catalogued ahead of hardware existing to test",
    }[device.status]
    if device.maintainer_verified:
        mv = device.maintainer_verified
        verified = f"**Maintainer-verified** {mv.date} on {mv.distro}: {mv.what_was_tested.strip()}"
    else:
        verified = (
            "**Not maintainer-verified**: nobody on this project has run this "
            "hardware yet. The two facts are recorded separately on purpose "
            "(D-027) — a correct recipe and a tested device are different claims."
        )
    return f"Status: {status}.\n\n{verified}"


def page(
    device: DeviceManifest,
    classes: dict[str, DeviceClass],
    known: set[str],
) -> str:
    doc = device.documentation
    lines = [
        HEADER,
        "",
        f"# {device.name}",
        "",
        f"> {device.summary}",
        "",
        f"**Vendor:** {device.vendor}"
        + (
            f"  ·  **class:** [{device.device_class}](#)".replace(
                "(#)", f"({device.device_class}-class.md)"
            )
            if device.device_class
            else ""
        ),
        "",
        verification_line(device),
        "",
        "## What it is",
        "",
        doc.what_it_is,
        "",
        "## What you can do with it",
        "",
        doc.what_you_can_do_with_it,
        "",
        "## Setup",
        "",
        doc.setup_steps,
        "",
    ]
    if doc.known_problems:
        lines += ["## Known problems", "", doc.known_problems, ""]

    if device.usb_ids:
        lines += [
            "## How it identifies itself",
            "",
            "| USB id | What | Confirmed | Node |",
            "|---|---|---|---|",
        ]
        for usb in device.usb_ids:
            confirmed = "yes" if usb.confirmed else "no"
            lines.append(
                f"| `{usb.vendor}:{usb.product}` | {usb.description} | {confirmed} | {usb.node_kind} |"
            )
        lines.append("")
        for usb in device.usb_ids:
            if usb.ambiguity:
                shared = ", ".join(usb.ambiguity.also_used_by)
                lines += [
                    f"**⚠ `{usb.vendor}:{usb.product}` is not unique to this device** "
                    f"({usb.ambiguity.basis}; also used by: {shared}). "
                    f"{usb.ambiguity.evidence.strip()}",
                    "",
                ]

    if device.identification_gap:
        closure = {
            "maintainer_hardware": (
                "the maintainer owns this hardware; the gap closes at the next capture session"
            ),
            "unverified_by_maintainer": (
                "nobody on this project owns one — an operator who does can close "
                "it with one lsusb ([how](../contributing/hardware.md))"
            ),
            "not_applicable": "nothing to capture; the gap is documentation, not measurement",
        }
        lines += ["## What is not yet known", "", device.identification_gap.strip(), ""]
        if device.gap_closure:
            lines += [f"*Who can close it:* {closure[device.gap_closure]}.", ""]

    inherited = classes.get(device.device_class) if device.device_class else None
    groups = list(device.groups) + (list(inherited.groups) if inherited else [])
    if groups or device.udev:
        lines += ["## Access and permissions", ""]
        if groups:
            unique = sorted(set(groups))
            lines += [
                f"Group membership required: {', '.join(f'`{g}`' for g in unique)} "
                f"— added at install, applies at next login.",
                "",
            ]
        if device.udev:
            udev = device.udev
            parts = [f"a `/dev/{udev.symlink}` symlink"] if udev.symlink else []
            parts.append(f"mode `{udev.mode}`")
            if udev.group:
                parts.append(f"group `{udev.group}`")
            match = (
                f", matched on the product string `{udev.match_product}` because the "
                f"bare identifier is ambiguous"
                if udev.match_product
                else ""
            )
            lines += [
                f"The generated udev rule provides {', '.join(parts)}{match}.",
                "",
            ]

    if device.firmware:
        lines += ["## Firmware modes", ""]
        for fw in device.firmware:
            pkgs = ", ".join(_pkg_link(p, known) for p in fw.packages) or "—"
            lines.append(f"- **{fw.kind}** — tooling: {pkgs}")
            if fw.note:
                lines.append(f"  {fw.note.strip()}")
        lines.append("")

    packages = list(device.packages) + (list(inherited.packages) if inherited else [])
    if packages:
        unique_pkgs = sorted(set(packages))
        lines += [
            "## Software that makes it useful",
            "",
            ", ".join(_pkg_link(p, known) for p in unique_pkgs),
            "",
        ]
    if doc.upstream_url:
        lines += [f"**Upstream:** <{doc.upstream_url}>", ""]
    return "\n".join(lines)


def class_page(cls: DeviceClass, devices: dict[str, DeviceManifest], known: set[str]) -> str:
    members = sorted(n for n, d in devices.items() if d.device_class == cls.name)
    doc = cls.documentation
    lines = [
        HEADER,
        "",
        f"# {cls.name} (device class)",
        "",
        f"> {cls.summary}",
        "",
        doc.what_it_is,
        "",
        "## Devices in this class",
        "",
    ]
    lines += [f"- [{m}]({m}.md)" for m in members] or ["*None catalogued yet.*"]
    lines += ["", "## Shared setup", "", doc.setup_steps, ""]
    if cls.packages:
        lines += [
            "## Shared tooling",
            "",
            ", ".join(_pkg_link(p, known) for p in sorted(set(cls.packages))),
            "",
        ]
    return "\n".join(lines)


def index(devices: dict[str, DeviceManifest], classes: dict[str, DeviceClass]) -> str:
    lines = [
        HEADER,
        "",
        "# Hardware",
        "",
        "One page per catalogued device: what it is, how it identifies itself "
        "on USB, what permissions it needs, and what software makes it useful. "
        "**Status** and **verified** are separate columns on purpose (D-027): "
        "a correct setup recipe and a device someone here has actually run are "
        "different claims, and conflating them is how catalogs lie.",
        "",
        "| Device | Status | Verified | Summary |",
        "|---|---|---|---|",
    ]
    for name in sorted(devices):
        d = devices[name]
        verified = "✅" if d.maintainer_verified else "—"
        lines.append(f"| [{name}]({name}.md) | {d.status} | {verified} | {d.summary} |")
    lines += [
        "",
        "## Device classes",
        "",
        "Families with shared Linux needs; a device in a class inherits its rules and tooling.",
        "",
    ]
    lines += [f"- [{name}]({name}-class.md) — {classes[name].summary}" for name in sorted(classes)]
    lines += [
        "",
        "Own hardware that is not here, or is marked untested? "
        "[Closing a gap takes one lsusb](../contributing/hardware.md).",
        "",
    ]
    return "\n".join(lines)


def render() -> dict[str, str]:
    classes, devices = load_hardware(HARDWARE)
    known = set(load_catalog(CATALOG))
    files = {f"{name}.md": page(d, classes, known) for name, d in devices.items()}
    files |= {f"{name}-class.md": class_page(c, devices, known) for name, c in classes.items()}
    files["index.md"] = index(devices, classes)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    files = render()
    if args.check:
        existing = {p.name: p.read_text() for p in OUT.glob("*.md")} if OUT.exists() else {}
        if existing != files:
            print("docs/hardware/ is out of date; run scripts/gen_hardware_reference.py")
            return 1
        print(f"docs/hardware/ is up to date ({len(files)} files)")
        return 0

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    for name, body in files.items():
        (OUT / name).write_text(body)
    print(f"wrote {len(files)} files to {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
