#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the Forest Service FSTopo quad index, and grow its pins.
D-068, amended 2026-10-01.

``catalog/data/fstopo-quads.txt`` names every FSTopo 7.5-minute quad in the
Forest Service's GTAC index, one per line:

    <south> <west> <north> <east> <secoord> <vintage> <ST> <cell name>

so the plan can choose a region's sheets with no network. The input is the
ArcGIS feature layer ``FSTopo_Index_GTAC`` (USDA Forest Service, Geospatial
Technology and Applications Center): each feature's polygon gives the box,
``secoord`` names the sheet to the raster gateway, ``vintage`` its edition
(a two-digit year, 0 where the layer gives none: 6,560 of 18,188 on
2025-08-08), ``primary_state`` and ``cell_name`` its state and name. The
header records the layer's ``dataLastEditDate`` (D-031: an input's date,
never the day this ran). A feature with no secoord, no name or no state is
left out and counted.

The Forest Service publishes **no checksum** for a sheet: the gateway's
ETag is Apache's inode-size-mtime. ``catalog/data/fstopo-pins.yaml`` holds
the sha256 and size of the sheets the maintainer has measured, grown one
sheet at a time with ``--pin``, which downloads the sheet; it starts empty.
A sheet with no pin is fetched unverified, and the plan says so by name.

    scripts/gen_fstopo_index.py --fetch                       # about 19 pages
    scripts/gen_fstopo_index.py --save-features F             # save the pages
    scripts/gen_fstopo_index.py --fetch --features F          # from saved pages
    scripts/gen_fstopo_index.py --pin SECOORD [SECOORD ...]   # downloads each sheet
    scripts/gen_fstopo_index.py --check [--offline]

``--check --offline`` checks the index's shape and the pins file. Plain
``--check`` also fetches the layer again and exits 1 naming each carried
quad that is gone or whose box changed; a new quad or a new vintage is
counted, not failed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.fstopo import (  # noqa: E402
    FsQuad,
    FstopoError,
    GatewayProbe,
    load_pins,
    parse_index,
    parse_row,
    render_row,
)

INDEX = REPO_ROOT / "catalog" / "data" / "fstopo-quads.txt"
PINS = REPO_ROOT / "catalog" / "data" / "fstopo-pins.yaml"
LAYER = (
    "https://services1.arcgis.com/gGHDlz6USftL5Pau/arcgis/rest/services/"
    "FSTopo_Index_GTAC/FeatureServer/0"
)
FIELDS = "secoord,cell_name,primary_state,vintage"
PAGE = 1000
TIMEOUT = 60.0
GENERATED_MARK = "GENERATED by scripts/gen_fstopo_index.py"
_COUNTS = re.compile(r"# quads: (\d+); left out, no secoord, name or state: (\d+)")
_EDITED = re.compile(r"# index: FSTopo_Index_GTAC, last edited (\d{4}-\d{2}-\d{2})")

HEADER = """\
# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: CC0-1.0

# {mark} --fetch. Do not edit by hand.
#
# Every Forest Service FSTopo 7.5-minute quad in the GTAC index (US federal
# work, public domain), one per line: south west north east (degrees, NAD83),
# secoord (the sheet's number at the raster gateway), vintage (the index's
# edition, a two-digit year; 0 where it gives none), primary state, and the
# cell name. A region's sheets are those whose box
# overlaps a 1/8-degree cell its outline touches. The Forest Service
# publishes no checksum; a sheet with a row in fstopo-pins.yaml is checked by
# that sha256, and any other is fetched unverified, the plan saying so.
#
# index: FSTopo_Index_GTAC, last edited {edited}
# quads: {total}; left out, no secoord, name or state: {missing}
#
# Regenerate: scripts/gen_fstopo_index.py --fetch
# Check:      scripts/gen_fstopo_index.py --check (the layer again, no sheet)
"""

PINS_HEADER = """\
# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: CC0-1.0

# {mark} --pin. Do not edit by hand.
#
# The FSTopo sheets whose sha256 the maintainer measured, by secoord. The
# Forest Service publishes no checksum; a sheet listed here is checked
# against this sha256 and size ("sha256, pinned by Hammunition"), and any
# other is fetched unverified, the plan saying so by name. A pin goes stale
# when the Forest Service re-issues the sheet: the plan then refuses it by
# name, and --pin measures it again.
"""


#: The layer names a sheet's primary state in full; the index carries the
#: postal code, which is how a sheet's file name starts.
STATES = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR", "California": "CA",
    "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE", "District of Columbia": "DC",
    "Florida": "FL", "Georgia": "GA", "Hawaii": "HI", "Idaho": "ID", "Illinois": "IL",
    "Indiana": "IN", "Iowa": "IA", "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA",
    "Maine": "ME", "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI",
    "Minnesota": "MN", "Mississippi": "MS", "Missouri": "MO", "Montana": "MT",
    "Nebraska": "NE", "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ",
    "New Mexico": "NM", "New York": "NY", "North Carolina": "NC", "North Dakota": "ND",
    "Ohio": "OH", "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA",
    "Puerto Rico": "PR", "Rhode Island": "RI", "South Carolina": "SC",
    "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT", "Vermont": "VT",
    "Virginia": "VA", "Virgin Islands": "VI", "Washington": "WA", "West Virginia": "WV",
    "Wisconsin": "WI", "Wyoming": "WY",
}  # fmt: skip


class GeneratorError(Exception):
    """An input could not be read, or a carried file is not what it claims."""


@dataclass(frozen=True)
class Built:
    quads: tuple[FsQuad, ...]
    missing: int
    edited: str


def _degrees(value: float) -> str:
    text = f"{value:.7f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def _box(geometry: Mapping[str, Any]) -> tuple[float, float, float, float]:
    points = [p for ring in geometry.get("rings", ()) for p in ring]
    if not points:
        raise GeneratorError("a feature has no polygon")
    xs = [float(p[0]) for p in points]
    ys = [float(p[1]) for p in points]
    return min(ys), min(xs), max(ys), max(xs)


def build(features: Iterable[Mapping[str, Any]], edited: str) -> Built:
    """The index's quads from the layer's features."""
    quads: dict[int, FsQuad] = {}
    missing = 0
    for number, feature in enumerate(features, 1):
        attributes = feature.get("attributes", {})
        secoord, name = attributes.get("secoord"), attributes.get("cell_name")
        state, vintage = attributes.get("primary_state"), attributes.get("vintage")
        if not secoord or not name or not state or not str(state).strip():
            missing += 1
            continue
        code = STATES.get(str(state).strip())
        if code is None:
            raise GeneratorError(f"feature {number} ({name}): no postal code for {state!r}")
        south, west, north, east = _box(feature.get("geometry") or {})
        cell = " ".join(str(name).split())
        line = (
            f"{_degrees(south)} {_degrees(west)} {_degrees(north)} {_degrees(east)} "
            f"{int(float(secoord))} {int(vintage) if vintage else 0} "
            f"{code} {cell}"
        )
        try:
            quad = parse_row(line, number)
        except FstopoError as exc:
            raise GeneratorError(f"feature {number} ({name}): {exc}") from exc
        if quad.secoord in quads:
            # The index carries a few cells twice (a sheet split by a state
            # line); one sheet is one download, so the larger box is kept.
            kept = quads[quad.secoord]
            if (quad.north - quad.south) * (quad.east - quad.west) <= (kept.north - kept.south) * (
                kept.east - kept.west
            ):
                continue
        quads[quad.secoord] = quad
    ordered = tuple(sorted(quads.values(), key=lambda q: q.secoord))
    return Built(ordered, missing, edited)


def render(built: Built) -> str:
    body = "".join(f"{render_row(q)}\n" for q in built.quads)
    return (
        HEADER.format(
            mark=GENERATED_MARK, edited=built.edited, total=len(built.quads), missing=built.missing
        )
        + body
    )


def check_shape(text: str) -> Built:
    if GENERATED_MARK not in text:
        raise GeneratorError(f"{INDEX} lacks the line saying it is generated")
    counts, edited = _COUNTS.search(text), _EDITED.search(text)
    if counts is None or edited is None:
        raise GeneratorError(f"{INDEX} has no `# quads:` or `# index:` header line")
    try:
        quads = parse_index(text).quads
    except FstopoError as exc:
        raise GeneratorError(f"{INDEX}: {exc}") from exc
    numbers = [q.secoord for q in quads]
    if numbers != sorted(numbers):
        raise GeneratorError(f"{INDEX}: the rows are not sorted by secoord; regenerate it")
    if int(counts.group(1)) != len(quads):
        raise GeneratorError(
            f"{INDEX}: the header counts {counts.group(1)} quads and the file has "
            f"{len(quads)}; it was edited by hand. Regenerate it"
        )
    return Built(tuple(quads), int(counts.group(2)), edited.group(1))


def check_online(carried: Sequence[FsQuad], live: Sequence[FsQuad]) -> tuple[list[str], int]:
    """(what breaks an install -- a carried quad gone or its box changed --,
    how many quads are new or carry a new vintage)."""
    now = {q.secoord: q for q in live}
    problems: list[str] = []
    for quad in carried:
        found = now.get(quad.secoord)
        if found is None:
            problems.append(f"{quad.secoord} ({quad.cell}): no longer in the index")
        elif (found.south, found.west, found.north, found.east) != (
            quad.south,
            quad.west,
            quad.north,
            quad.east,
        ):
            problems.append(f"{quad.secoord} ({quad.cell}): its box changed")
    ours = {q.secoord: q.vintage for q in carried}
    changed = sum(1 for q in live if ours.get(q.secoord) != q.vintage)
    return problems, changed


def render_pins(pins: Mapping[str, tuple[int, str]]) -> str:
    rows = [
        {"secoord": int(secoord), "size": size, "sha256": sha256}
        for secoord, (size, sha256) in sorted(pins.items(), key=lambda i: int(i[0]))
    ]
    return PINS_HEADER.format(mark=GENERATED_MARK) + yaml.safe_dump(
        {"pins": rows}, sort_keys=False, default_flow_style=False
    )


# ---------------------------------------------------------------------------
# The network: the feature layer, and the gateway for --pin.
# ---------------------------------------------------------------------------


def _opener() -> urllib.request.OpenerDirector:
    opener = urllib.request.OpenerDirector()
    opener.add_handler(urllib.request.HTTPHandler())
    opener.add_handler(urllib.request.HTTPSHandler())
    return opener


def _get(url: str) -> bytes:
    if not url.startswith(LAYER + "?") and not url.startswith(LAYER + "/query?"):
        raise GeneratorError(f"refusing {url!r}: only the FSTopo index layer is asked")
    request = urllib.request.Request(url, headers={"User-Agent": "hammunition"})
    try:
        response = _opener().open(request, timeout=TIMEOUT)
    except (urllib.error.URLError, OSError) as exc:
        raise GeneratorError(f"{url} could not be reached: {exc}") from exc
    if response is None:  # pragma: no cover - no handler claimed the scheme
        raise GeneratorError(f"no handler would ask {url!r}")
    with response:
        if response.status != 200:
            raise GeneratorError(f"{url} answered HTTP {response.status}")
        body: bytes = response.read()
        return body


def _json(raw: bytes) -> dict[str, Any]:
    try:
        data = json.loads(raw)
    except ValueError as exc:
        raise GeneratorError(f"the layer answered something that is not JSON: {exc}") from exc
    if not isinstance(data, dict) or "error" in data:
        raise GeneratorError(f"the layer answered an error: {str(data)[:200]}")
    return data


def layer_edited(get: Callable[[str], bytes] = _get) -> str:
    """The layer's ``dataLastEditDate`` as a date."""
    data = _json(get(f"{LAYER}?f=json"))
    stamp = (data.get("editingInfo") or {}).get("dataLastEditDate")
    if not isinstance(stamp, int):
        raise GeneratorError("the layer reports no dataLastEditDate")
    return datetime.fromtimestamp(stamp / 1000, tz=UTC).strftime("%Y-%m-%d")


def list_features(get: Callable[[str], bytes] = _get) -> Iterator[dict[str, Any]]:
    offset = 0
    while True:
        query = {
            "where": "1=1",
            "outFields": FIELDS,
            "returnGeometry": "true",
            "outSR": "4269",
            "geometryPrecision": "7",
            "orderByFields": "objectid",
            "resultOffset": str(offset),
            "resultRecordCount": str(PAGE),
            "f": "json",
        }
        data = _json(get(f"{LAYER}/query?{urllib.parse.urlencode(query)}"))
        features = data.get("features") or []
        yield from features
        if not data.get("exceededTransferLimit") and len(features) < PAGE:
            return
        if not features:
            return
        offset += len(features)


def measure(secoord: int, probe: GatewayProbe, timeout: float = TIMEOUT) -> tuple[int, str]:
    """(size, sha256) of one sheet, downloaded from where the gateway points."""
    url, size = probe.locate(secoord)
    request = urllib.request.Request(url, headers={"User-Agent": "hammunition"})
    digest = hashlib.sha256()
    got = 0
    try:
        with _opener().open(request, timeout=timeout) as response:
            while chunk := response.read(1 << 16):
                got += len(chunk)
                if got > size:
                    raise GeneratorError(f"{url} sent more than the {size} bytes it announced")
                digest.update(chunk)
    except (urllib.error.URLError, OSError) as exc:
        raise GeneratorError(f"{url} could not be fetched: {exc}") from exc
    if got != size:
        raise GeneratorError(f"{url}: {size} bytes announced and {got} arrived")
    return size, digest.hexdigest()


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--fetch", action="store_true", help="regenerate the index")
    mode.add_argument("--check", action="store_true", help="check the carried index and pins")
    mode.add_argument("--save-features", type=Path, metavar="FILE", help="save the layer")
    mode.add_argument("--pin", nargs="+", type=int, metavar="SECOORD", help="measure sheets")
    parser.add_argument("--offline", action="store_true", help="with --check: shape only")
    parser.add_argument("--features", type=Path, help="with --fetch: a saved layer")
    args = parser.parse_args(argv)
    try:
        if args.save_features:
            saved = {"edited": layer_edited(), "features": list(list_features())}
            args.save_features.write_text(json.dumps(saved))
            print(f"saved {len(saved['features'])} features to {args.save_features}")
            return 0
        if args.fetch:
            if args.features:
                saved = json.loads(args.features.read_text())
                edited, features = saved["edited"], saved["features"]
            else:
                edited, features = layer_edited(), list(list_features())
            built = build(features, edited)
            INDEX.write_text(render(built))
            print(
                f"wrote {INDEX.relative_to(REPO_ROOT)}: {len(built.quads)} quads, "
                f"{built.missing} left out"
            )
            return 0
        if args.pin:
            carried = {q.secoord: q for q in check_shape(INDEX.read_text()).quads}
            pins = {k: (p.size, p.sha256) for k, p in load_pins(PINS).items()}
            probe = GatewayProbe()
            for secoord in args.pin:
                if secoord not in carried:
                    raise GeneratorError(f"{secoord} is not in {INDEX.name}")
                pins[secoord] = measure(secoord, probe)
                print(f"pinned {secoord}: {pins[secoord][0]} bytes, sha256 {pins[secoord][1]}")
            PINS.write_text(render_pins({str(k): v for k, v in pins.items()}))
            return 0
        carried_built = check_shape(INDEX.read_text())
        pinned = load_pins(PINS)
        unknown = [s for s in pinned if s not in {q.secoord for q in carried_built.quads}]
        if unknown:
            raise GeneratorError(f"{PINS.name} pins quads the index does not carry: {unknown}")
        print(
            f"{INDEX.relative_to(REPO_ROOT)} is well formed: {len(carried_built.quads)} quads, "
            f"{len(pinned)} pinned"
        )
        if args.offline:
            return 0
        live = build(list_features(), carried_built.edited).quads
        problems, changed = check_online(carried_built.quads, live)
        if changed:
            print(f"{changed} quad(s) are new or carry a new vintage; --fetch picks them up")
        if problems:
            print(f"{len(problems)} carried quad(s) no longer match the index:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            print("Regenerate: scripts/gen_fstopo_index.py --fetch", file=sys.stderr)
            return 1
        print("every carried quad is in the index with its box")
        return 0
    except (GeneratorError, FstopoError, OSError, KeyError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
