#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the config_files table in docs/guides/station-settings.md.

Usage:
    scripts/gen_station_settings.py
    scripts/gen_station_settings.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.manifest.load import load_catalog  # noqa: E402
from hammunition.manifest.schema import PackageManifest  # noqa: E402
from hammunition.station import DERIVED, Station  # noqa: E402

OUT = REPO_ROOT / "docs" / "guides" / "station-settings.md"
START = "<!-- Generated by scripts/gen_station_settings.py. Do not edit this table by hand. -->"
END = "<!-- End generated station settings -->"


def render_table(catalog: dict[str, PackageManifest]) -> str:
    lines = [
        "| Program | File | Station values | Missing-value behavior |",
        "|---|---|---|---|",
    ]
    for name, manifest in sorted(catalog.items()):
        for config in manifest.config_files:
            variables = config.station_variables
            values = []
            for variable in sorted(variables):
                value = f"`{variable}`"
                if variable in DERIVED:
                    value += f" (from `{DERIVED[variable][0]}`)"
                values.append(value)
            missing = Station().missing(variables)
            behavior = (
                "Defer this file only if any of "
                + ", ".join(f"`{field}`" for field in missing)
                + " is unset"
                if missing
                else "No station value required; no missing-value deferral"
            )
            lines.append(
                f"| [{name}](../packages/{name}.md) | `{config.path}` | "
                f"{', '.join(values) or 'None'} | {behavior} |"
            )
    return "\n".join(lines)


def render(page: str, catalog: dict[str, PackageManifest]) -> str:
    if page.count(START) != 1 or page.count(END) != 1:
        raise ValueError("station-settings.md must contain exactly one pair of generation markers")
    before, _, rest = page.partition(START)
    _, _, after = rest.partition(END)
    if END in before:
        raise ValueError("station-settings.md generation markers are out of order")
    return before + START + "\n\n" + render_table(catalog) + "\n\n" + END + after


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date; write nothing")
    args = parser.parse_args()
    current = OUT.read_text()
    content = render(current, load_catalog(REPO_ROOT / "catalog" / "packages"))
    if args.check:
        if current != content:
            print(
                "docs/guides/station-settings.md is out of date; "
                "run scripts/gen_station_settings.py"
            )
            return 1
        print("docs/guides/station-settings.md is up to date")
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
