#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate docs/packages/ — one page per manifest, plus an index.

CLAUDE.md: "Generate what can be generated. The package reference and
capability matrix come from manifests, so they cannot drift from reality. Any
doc that duplicates manifest data by hand is a defect."

The catalog carries the documentation fields already — the schema refuses a
manifest without `what_it_does`, `why_you_want_it` and an upstream URL, which
is what makes this generator possible at all. What it adds is the part a YAML
file cannot: an entry a person can read, an index they can browse by category,
and the install method and per-target caveats surfaced where someone deciding
whether to install something will actually see them.

**Nothing here is written by hand and nothing here may be edited by hand.**
`tests/test_docs_generated.py` asserts regeneration is a no-op, so an edit to
an output file goes red naming the script.

Usage:
    scripts/gen_package_reference.py            # regenerate
    scripts/gen_package_reference.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

import yaml  # noqa: E402

from hammunition.manifest.load import load_catalog  # noqa: E402
from hammunition.manifest.schema import (  # noqa: E402
    AptInstall,
    BinaryInstall,
    GitInstall,
    InstallBlock,
    PackageManifest,
    PipxInstall,
    SourceInstall,
    Status,
    VenvInstall,
)

CATALOG = REPO_ROOT / "catalog" / "packages"
VOCABULARY = REPO_ROOT / "catalog" / "categories.yaml"
OUT = REPO_ROOT / "docs" / "packages"

HEADER = "<!-- Generated by scripts/gen_package_reference.py. Do not edit by hand -->\n"


def method_of(block: InstallBlock) -> str:
    """A short human phrase for how one block installs, with its source."""
    install = block.install
    if isinstance(install, AptInstall):
        return "apt: `" + "`, `".join(install.packages) + "`"
    if isinstance(install, SourceInstall):
        return f"source ({install.build_system}) from {install.source.url}"
    if isinstance(install, GitInstall):
        return f"git ({install.build_system}) — {install.repo} at `{install.ref}`"
    if isinstance(install, BinaryInstall):
        return f"prebuilt {install.format} from {install.artifact.url}"
    if isinstance(install, VenvInstall):
        return "python venv: `" + "`, `".join(install.requirements) + "`"
    # No fallback branch: InstallMethod is a closed union and mypy proves the
    # chain above exhausts it. A `return install.method` here reads as
    # defensive and is unreachable, which mypy --strict rejects -- correctly,
    # because it would silently absorb a new install method instead of
    # failing to compile when one is added.
    assert isinstance(install, PipxInstall)
    return f"pipx: `{install.spec}`"


def selector_of(block: InstallBlock) -> str:
    """What restricts a block, in words. Empty when it is the default."""
    parts = []
    if block.when.distro:
        parts.append("on " + ", ".join(block.when.distro))
    if block.when.distro_version:
        parts.append("version " + ", ".join(block.when.distro_version))
    if block.when.arch:
        parts.append("arch " + ", ".join(a.value for a in block.when.arch))
    return "; ".join(parts)


def status_line(m: PackageManifest) -> str | None:
    if m.status is Status.supported:
        return None
    bits = [f"**Status: {m.status.value}.**"]
    if m.status_reason:
        bits.append(m.status_reason.strip())
    if m.status_date:
        bits.append(f"Recorded {m.status_date.isoformat()}.")
    if m.status_verdict:
        bits.append(f"Verdict {m.status_verdict.value} by us.")
    return " ".join(bits)


def page(m: PackageManifest) -> str:
    d = m.documentation
    out = [HEADER, f"# {m.name}\n", f"**{m.summary}**\n"]

    status = status_line(m)
    if status:
        out.append(f"> {status}\n")

    out.append(f"- **Version recorded:** {m.version}")
    out.append("- **Categories:** " + ", ".join(f"`{c}`" for c in sorted(m.categories)))
    out.append(f"- **Upstream:** <{d.upstream_url}>")
    if m.provides:
        out.append("- **Also provides:** " + ", ".join(f"`{p}`" for p in m.provides))
    if m.depends:
        out.append("- **Needs first:** " + ", ".join(f"`{p}`" for p in m.depends))
    if m.after:
        out.append("- **Install after:** " + ", ".join(f"`{p}`" for p in m.after))
    if m.supersedes:
        out.append("- **Supersedes:** " + ", ".join(f"`{p}`" for p in m.supersedes))
    if m.superseded_by:
        out.append(f"- **Superseded by:** `{m.superseded_by}`")
    if not m.recommended_default:
        out.append("- **Not a recommended default** — installed only when asked for.")
    out.append("")

    out.append("## What it does\n")
    out.append(d.what_it_does.strip() + "\n")
    out.append("## Why you would want it\n")
    out.append(d.why_you_want_it.strip() + "\n")

    if d.prerequisites:
        out.append("## Before it will work\n")
        out.append(d.prerequisites.strip() + "\n")

    out.append("## How it installs\n")
    for block in m.install:
        where = selector_of(block)
        lead = f"- {method_of(block)}"
        if where:
            lead += f" — *{where}*"
        out.append(lead)
        if block.build_depends:
            out.append(
                "  - build dependencies: " + ", ".join(f"`{b}`" for b in block.build_depends)
            )
        flags = getattr(block.install, "compiler_flags", None)
        if flags:
            out.append(
                "  - compiler flags: "
                + ", ".join(f"`{f}`" for f in flags)
                + " — without these it does not build on a current toolchain"
            )
        if getattr(block.install, "provides_install_target", True) is False:
            out.append(
                "  - the project's build system has no install rule; the binaries "
                "listed below are copied into the prefix instead"
            )
        if block.note:
            out.append("  - " + " ".join(block.note.split()))
    out.append("")

    if m.binaries:
        out.append("Binaries this produces:\n")
        for b in m.binaries:
            same = " " if b.produced.split("/")[-1] == b.install_as else " installed as "
            out.append(f"- `{b.produced}`" + ("" if same == " " else f" → `{b.install_as}`"))
        out.append("")

    if m.conflicts_with_repo_package:
        out.append(
            "This displaces the distribution's own "
            + ", ".join(f"`{p}`" for p in m.conflicts_with_repo_package)
            + " (**D-022**: coexist, disclose, never remove silently).\n"
        )

    if m.system_modifications:
        out.append("## What it changes on your machine\n")
        for mod in m.system_modifications:
            reverse = mod.reverse_hint or "not reversible"
            out.append(f"- **{mod.kind}** — {mod.description.strip()}")
            out.append(f"  - {mod.detail.strip()}")
            out.append(f"  - undo: {reverse}")
        out.append("")

    if m.config_files:
        out.append("## Configuration it writes\n")
        for cfg in m.config_files:
            backup = "existing file backed up" if cfg.backup_existing else "no backup"
            out.append(f"- `{cfg.path}` (mode {cfg.mode}, {backup})")
        out.append("")

    if d.known_problems:
        out.append("## Known problems\n")
        out.append(d.known_problems.strip() + "\n")

    if m.toolkit_risk:
        out.append("## Toolkit risk\n")
        for risk in m.toolkit_risk:
            note = f" — {' '.join(risk.note.split())}" if risk.note else ""
            out.append(
                f"- `{risk.framework}`: {risk.upstream_port_status.replace('_', ' ')}, "
                f"checked {risk.checked.isoformat()}{note}"
            )
        out.append("")

    out.append("## Keeping it current\n")
    probe = m.update.probe
    how = probe.method.replace("_", " ")
    out.append(f"- probe: {how}" + (f" (`{probe.repo}`)" if probe.repo else ""))
    out.append(f"- strategy: {m.update.strategy}")
    if m.update.cadence_hint:
        out.append("- " + " ".join(m.update.cadence_hint.split()))
    out.append("")

    if d.upstream_support:
        out.append("## Where to get help with the software itself\n")
        out.append(d.upstream_support.strip() + "\n")

    out.append(
        f"*Source: [`catalog/packages/{m.name}.yaml`](../../catalog/packages/{m.name}.yaml)*\n"
    )
    return "\n".join(out)


def index(catalog: dict[str, PackageManifest], vocabulary: dict[str, str]) -> str:
    by_category: dict[str, list[PackageManifest]] = {name: [] for name in vocabulary}
    for m in catalog.values():
        for c in m.categories:
            by_category[c].append(m)

    out = [
        HEADER,
        "# Package reference\n",
        "Every piece of software in the catalog, one page each. Generated from "
        "`catalog/packages/` by `scripts/gen_package_reference.py` — it cannot "
        "drift from what the engine would actually install, because it is the "
        "same data.\n",
        f"**{len(catalog)} packages** across **{len(vocabulary)} categories**. "
        "Categories are flat tags (**D-003**): they overlap freely and never "
        "nest, so most packages appear under more than one.\n",
        "## By category\n",
    ]
    for name in sorted(vocabulary):
        members = sorted(by_category[name], key=lambda m: m.name)
        out.append(f"### `{name}` — {len(members)}\n")
        out.append(" ".join(vocabulary[name].split()) + "\n")
        for m in members:
            out.append(f"- [{m.name}]({m.name}.md) — {m.summary}")
        out.append("")

    out.append("## Everything, alphabetically\n")
    out.append("| Package | Summary | Installs by |")
    out.append("|---|---|---|")
    for m in sorted(catalog.values(), key=lambda m: m.name):
        methods = sorted({b.install.method for b in m.install})
        out.append(f"| [{m.name}]({m.name}.md) | {m.summary} | {', '.join(methods)} |")
    out.append("")
    return "\n".join(out)


def render(catalog: dict[str, PackageManifest], vocabulary: dict[str, str]) -> dict[str, str]:
    files = {f"{name}.md": page(m) for name, m in catalog.items()}
    files["index.md"] = index(catalog, vocabulary)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the output is not up to date")
    args = parser.parse_args()

    catalog = load_catalog(CATALOG)
    vocabulary = {
        c["name"]: c["summary"] for c in yaml.safe_load(VOCABULARY.read_text())["categories"]
    }
    files = render(catalog, vocabulary)

    if args.check:
        existing = {p.name: p.read_text() for p in OUT.glob("*.md")} if OUT.exists() else {}
        if existing != files:
            missing = sorted(set(files) - set(existing))
            extra = sorted(set(existing) - set(files))
            changed = sorted(n for n in set(files) & set(existing) if files[n] != existing[n])
            print("docs/packages/ is out of date; run scripts/gen_package_reference.py")
            for label, names in (("missing", missing), ("stale", extra), ("changed", changed)):
                if names:
                    print(f"  {label}: {', '.join(names[:8])}{' …' if len(names) > 8 else ''}")
            return 1
        print(f"docs/packages/ is up to date ({len(files)} files)")
        return 0

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    for name, body in files.items():
        (OUT / name).write_text(body)
    print(f"wrote {len(files)} files to {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
