#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate catalog/data/geofabrik-pins.yaml: sha256 pins for Geofabrik extracts.

Geofabrik publishes an MD5 beside every extract and nothing stronger. For the
regions listed in ``REGIONS`` Hammunition carries its own sha256, measured
here: each region's current yearly snapshot (``<region>-YY0101.osm.pbf``) and
current monthly snapshot (``<region>-YYMM01.osm.pbf``) is streamed, hashed
and sized, and the bytes are discarded. Nothing is kept or mirrored.

A full pass downloads about 10 GB (the 50 US states and DC, twice), so it is
run on the maintainer's machine, never in CI and never in the test suite::

    scripts/gen_geofabrik_pins.py                      # every region
    scripts/gen_geofabrik_pins.py --region north-america/us/vermont
    scripts/gen_geofabrik_pins.py --check              # HEAD sizes only

``--region`` replaces only the named regions' rows and keeps every other
row. A region must be in ``REGIONS`` first: adding one is a line here and a
regeneration, so the pinned set is always what this file says it is.

``--check`` downloads nothing. It asks each pinned URL for its ``HEAD`` and
exits 1 naming every pin whose URL no longer answers 200 or whose
``Content-Length`` is not the pinned size. Geofabrik keeps about three monthly
snapshots, so a monthly pin ages out within a quarter; the weekly CI job runs
``--check`` and goes red when one does, with the command to regenerate. A
dated file never redirects, so a 3xx is a failure too: whatever it points at
is not the file that was hashed.

The region names are Geofabrik's own download paths under
``north-america/us/``, lowercase and hyphenated, as its region index
(https://download.geofabrik.de/index-v1.json) names them. They were written
here literally, not fetched; a wrong one fails the first real pass by URL.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import urllib.error
import urllib.request
from collections.abc import Callable, Iterable, Iterator, Sequence
from datetime import date
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "catalog" / "data" / "geofabrik-pins.yaml"
BASE = "https://download.geofabrik.de"
REGION_PATTERN = re.compile(r"[a-z0-9-]+(/[a-z0-9-]+)*")
SNAPSHOT_PATTERN = re.compile(r"\d{6}")
SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")
GENERATED_MARK = "GENERATED by scripts/gen_geofabrik_pins.py"
TIMEOUT = 60.0
CHUNK = 1024 * 1024

_STATES = (
    "alabama",
    "alaska",
    "arizona",
    "arkansas",
    "california",
    "colorado",
    "connecticut",
    "delaware",
    "district-of-columbia",
    "florida",
    "georgia",
    "hawaii",
    "idaho",
    "illinois",
    "indiana",
    "iowa",
    "kansas",
    "kentucky",
    "louisiana",
    "maine",
    "maryland",
    "massachusetts",
    "michigan",
    "minnesota",
    "mississippi",
    "missouri",
    "montana",
    "nebraska",
    "nevada",
    "new-hampshire",
    "new-jersey",
    "new-mexico",
    "new-york",
    "north-carolina",
    "north-dakota",
    "ohio",
    "oklahoma",
    "oregon",
    "pennsylvania",
    "rhode-island",
    "south-carolina",
    "south-dakota",
    "tennessee",
    "texas",
    "utah",
    "vermont",
    "virginia",
    "washington",
    "west-virginia",
    "wisconsin",
    "wyoming",
)

#: The pinned regions: the 50 US states and DC, as Geofabrik paths.
REGIONS: tuple[str, ...] = tuple(f"north-america/us/{s}" for s in _STATES)

HEADER = f"""\
# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: CC0-1.0

# {GENERATED_MARK}. Do not edit by hand.
#
# sha256 pins for Geofabrik OpenStreetMap extracts. Each row is one dated
# file, <region>-<snapshot>.osm.pbf under
# {BASE}/, streamed, hashed and discarded on the
# `measured` date. A region the operator selects that has a row here is
# verified by this sha256; any other is verified by Geofabrik's own MD5
# only, and the plan says which.
#
# Regenerate: scripts/gen_geofabrik_pins.py (about 10 GB downloaded per pass)
# Check:      scripts/gen_geofabrik_pins.py --check (HEAD sizes only)
"""

Stream = Callable[[str], Iterable[bytes]]
Head = Callable[[str], tuple[int, int | None]]


def url_for(region: str, snapshot: str) -> str:
    return f"{BASE}/{region}-{snapshot}.osm.pbf"


def snapshots(today: date) -> list[str]:
    """This year's 1 January and this month's 1st; one file in January."""
    yearly, monthly = f"{today:%y}0101", f"{today:%y%m}01"
    return [yearly] if yearly == monthly else [yearly, monthly]


def measure(url: str, stream: Stream) -> tuple[int, str]:
    digest = hashlib.sha256()
    size = 0
    try:
        for chunk in stream(url):
            digest.update(chunk)
            size += len(chunk)
    except OSError as exc:
        raise SystemExit(f"{url}: could not be downloaded: {exc}") from exc
    if size == 0:
        raise SystemExit(f"{url}: the server sent no bytes; nothing to pin")
    return size, digest.hexdigest()


def generate(regions: Sequence[str], *, today: date, stream: Stream) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for region in regions:
        for snapshot in snapshots(today):
            url = url_for(region, snapshot)
            print(f"measuring {url}", file=sys.stderr, flush=True)
            size, sha256 = measure(url, stream)
            rows.append(
                {
                    "region": region,
                    "snapshot": snapshot,
                    "size": size,
                    "sha256": sha256,
                    "measured": today.isoformat(),
                }
            )
    return rows


def render(rows: Sequence[dict[str, Any]]) -> str:
    ordered = sorted(rows, key=lambda r: (r["region"], r["snapshot"]))
    body = yaml.safe_dump({"pins": ordered}, sort_keys=False, default_flow_style=False)
    return f"{HEADER}\n{body}"


def parse(text: str) -> list[dict[str, Any]]:
    """The rows of a pin file, refused by name when malformed."""
    if GENERATED_MARK not in text:
        raise SystemExit(
            "the pin file does not carry the generated-by line; it was not written "
            "by scripts/gen_geofabrik_pins.py"
        )
    data = yaml.safe_load(text) or {}
    rows = data.get("pins")
    if not isinstance(rows, list):
        raise SystemExit("the pin file has no `pins:` list")
    for row in rows:
        if not isinstance(row, dict):
            raise SystemExit(f"pin row is not a mapping: {row!r}")
        region, snapshot = str(row.get("region")), str(row.get("snapshot"))
        if not REGION_PATTERN.fullmatch(region):
            raise SystemExit(f"pin row has a malformed region: {row!r}")
        if not SNAPSHOT_PATTERN.fullmatch(snapshot):
            raise SystemExit(f"pin row has a malformed snapshot: {row!r}")
        if not isinstance(row.get("size"), int) or row["size"] <= 0:
            raise SystemExit(f"pin row has a malformed size: {row!r}")
        if not SHA256_PATTERN.fullmatch(str(row.get("sha256"))):
            raise SystemExit(f"pin row has a malformed sha256: {row!r}")
    return rows


def check(rows: Sequence[dict[str, Any]], head: Head) -> list[str]:
    problems = []
    for row in rows:
        url = url_for(row["region"], row["snapshot"])
        status, length = head(url)
        if status != 200:
            problems.append(f"{url}: answered HTTP {status}, not 200")
        elif length != row["size"]:
            problems.append(f"{url}: Content-Length {length}, pinned {row['size']}")
    return problems


# -- the network, used only when nothing is injected --------------------------


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *args: Any, **kwargs: Any) -> None:
        return None


def _opener(*, follow_redirects: bool) -> urllib.request.OpenerDirector:
    # Only the HTTP handlers, as hammunition.fetch does: build_opener would
    # also add file:// and ftp:// handlers.
    director = urllib.request.OpenerDirector()
    redirect: urllib.request.BaseHandler = (
        urllib.request.HTTPRedirectHandler() if follow_redirects else _NoRedirect()
    )
    for handler in (
        urllib.request.HTTPSHandler(),
        redirect,
        urllib.request.HTTPErrorProcessor(),
        urllib.request.HTTPDefaultErrorHandler(),
    ):
        director.add_handler(handler)
    return director


def real_stream(url: str) -> Iterator[bytes]:
    request = urllib.request.Request(url, headers={"User-Agent": "hammunition"})
    with _opener(follow_redirects=False).open(request, timeout=TIMEOUT) as response:
        while chunk := response.read(CHUNK):
            yield chunk


def real_head(url: str) -> tuple[int, int | None]:
    request = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "hammunition"})
    try:
        with _opener(follow_redirects=False).open(request, timeout=TIMEOUT) as response:
            length = response.headers.get("Content-Length")
            return response.status, int(length) if length is not None else None
    except urllib.error.HTTPError as exc:
        return exc.code, None
    except OSError as exc:
        raise SystemExit(f"{url}: could not be probed: {exc}") from exc


# -- entry point ---------------------------------------------------------------


def main(
    argv: Sequence[str] | None = None,
    *,
    stream: Stream | None = None,
    head: Head | None = None,
    today: date | None = None,
    out: Path = OUT,
) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0] if __doc__ else "")
    parser.add_argument(
        "--check",
        action="store_true",
        help="HEAD every pinned URL and compare its size; download and write nothing",
    )
    parser.add_argument(
        "--region",
        action="append",
        default=[],
        metavar="R",
        help="regenerate only this region's rows (repeatable); others are kept",
    )
    args = parser.parse_args(argv)
    shown = out.relative_to(REPO_ROOT) if out.is_relative_to(REPO_ROOT) else out

    if args.check:
        rows = parse(out.read_text())
        problems = check(rows, head or real_head)
        if problems:
            print(f"{shown}: {len(problems)} pin(s) no longer match Geofabrik:")
            for problem in problems:
                print(f"  {problem}")
            print("Regenerate with scripts/gen_geofabrik_pins.py and commit the result.")
            return 1
        pinned = len({r["region"] for r in rows})
        print(
            f"{shown} is up to date: {len(rows)} pin(s) probed, "
            f"{pinned} of {len(REGIONS)} regions pinned"
        )
        return 0

    unknown = [r for r in args.region if r not in REGIONS]
    if unknown:
        raise SystemExit(
            f"not in the pinned region list: {', '.join(unknown)}. Add it to REGIONS "
            f"in scripts/gen_geofabrik_pins.py first."
        )
    regions = list(dict.fromkeys(args.region)) or list(REGIONS)
    kept: list[dict[str, Any]] = []
    if args.region and out.exists():
        kept = [r for r in parse(out.read_text()) if r["region"] not in regions]
    rows = generate(regions, today=today or date.today(), stream=stream or real_stream)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(kept + rows))
    print(f"wrote {shown}: {len(kept) + len(rows)} pin(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
