#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate the US Topo quad index.  D-068.

``catalog/data/ustopo-quads.txt`` names every current USGS US Topo
7.5-minute quad that has a GeoTIFF, one per line:

    <south> <west> <north> <east> <size> <etag> <ST>/<stem>_<date>

so the plan can choose a region's quads, print their sizes and check each
download against its publisher's ETag with no network. Two inputs:

* ``ustopo_current.zip`` from USGS (``StagedProducts/Maps/Metadata/``,
  10.5 MB, rebuilt daily): ``ustopo_current.csv``, one row per current quad
  with its bounding box and dated file name, and ``ustopo_current.txt``,
  whose ``Last Updated`` date is the one the header records (D-031: an
  input's date, never the day this ran);
* a listing of the bucket's ``StagedProducts/Maps/USTopo/GeoTIFF/`` prefix
  (273 ``ListObjectsV2`` pages on 2026-09-29): every GeoTIFF edition's key,
  size and ETag. The TNM Access API lists only the PDFs.

The current edition's GeoTIFF is used where the bucket has it. Where the
current edition exists only as a PDF (817 quads on 2026-09-29, all 2026
editions), the newest GeoTIFF edition the bucket holds is used and counted
in the header; a quad with no GeoTIFF at all is left out and counted.

    scripts/gen_ustopo_index.py --fetch                  # about 10.5 MB + the listing
    scripts/gen_ustopo_index.py --fetch --zip Z --listing L   # from saved inputs
    scripts/gen_ustopo_index.py --save-listing L          # save a listing to reuse
    scripts/gen_ustopo_index.py --check [--offline]

``--check --offline`` checks the file's shape: the generated mark, the
header's counts against the rows, rows sorted and every row parsed. Plain
``--check`` also lists the bucket and exits 1 naming each carried key that
is gone or whose size or ETag changed, because that breaks an install. A
newer edition appearing is counted and does not fail it: ``--fetch`` picks
it up. The weekly pin-review job runs ``--check``; the test suite runs
``--check --offline``, since it blocks the network.
"""

from __future__ import annotations

import argparse
import csv
import io
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
import zipfile
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from hammunition.ustopo import (  # noqa: E402
    BUCKET,
    PREFIX,
    SUFFIX,
    Quad,
    UstopoError,
    parse_index,
    parse_row,
    render_row,
)

INDEX = REPO_ROOT / "catalog" / "data" / "ustopo-quads.txt"
ZIP_URL = f"{BUCKET}/StagedProducts/Maps/Metadata/ustopo_current.zip"
GENERATED_MARK = "GENERATED by scripts/gen_ustopo_index.py"
TIMEOUT = 60.0
#: The first ``ListObjectsV2`` element namespace.
S3 = "{http://s3.amazonaws.com/doc/2006-03-01/}"
_OBJECT = re.compile(rf"{re.escape(PREFIX)}([A-Z]{{2}})/(.+)_(\d{{8}}){re.escape(SUFFIX)}")
_PRODUCT = re.compile(r"(.+)_(\d{8})_TM_geo\.pdf")
_COUNTS = re.compile(
    r"# quads: (\d+) \(current edition: (\d+); older GeoTIFF edition, the current one "
    r"PDF only: (\d+)\); left out, no GeoTIFF at all: (\d+)"
)

HEADER = """\
# SPDX-FileCopyrightText: Copyright (C) 2026 Renegade Penguin LLC
# SPDX-License-Identifier: CC0-1.0

# {mark} --fetch. Do not edit by hand.
#
# Every current USGS US Topo 7.5-minute quad with a GeoTIFF (public domain),
# from USGS's ustopo_current.csv and a listing of the prd-tnm bucket, one per
# line: south west north east (degrees, NAD83), size (bytes), S3 ETag, and
# <ST>/<stem>_<date>, the object key between
# {prefix} and {suffix}.
# A region's quads are those whose box overlaps a 1/8-degree cell its outline
# touches. Each download is checked against this ETag, re-asked with a HEAD at
# plan time ("MD5 from the publisher's object metadata; not pinned by
# Hammunition").
#
# index: ustopo_current.csv, last updated {updated} ({rows} current quads)
# quads: {total} (current edition: {current}; older GeoTIFF edition, the current one PDF only: {older}); left out, no GeoTIFF at all: {missing}
#
# Regenerate: scripts/gen_ustopo_index.py --fetch
# Check:      scripts/gen_ustopo_index.py --check (a listing, no download)
"""


class GeneratorError(Exception):
    """An input could not be read, or the carried file is not what it claims."""


@dataclass(frozen=True)
class Edition:
    """One GeoTIFF object in the bucket."""

    folder: str
    stem: str
    date: str
    size: int
    etag: str

    @property
    def path(self) -> str:
        return f"{self.folder}/{self.stem}_{self.date}"


@dataclass(frozen=True)
class Built:
    quads: tuple[Quad, ...]
    rows: int
    current: int
    older: int
    missing: int


def parse_listing(entries: Iterable[tuple[str, int, str]]) -> dict[str, list[Edition]]:
    """Every GeoTIFF edition in a bucket listing, by stem, newest first."""
    editions: dict[str, list[Edition]] = {}
    for key, size, etag in entries:
        match = _OBJECT.fullmatch(key)
        if match is None:
            continue  # the prefix's own placeholder, or something not a quad
        folder, stem, date = match.groups()
        editions.setdefault(stem, []).append(
            Edition(folder, stem, date, size, etag.strip().strip('"'))
        )
    for found in editions.values():
        found.sort(key=lambda e: e.date, reverse=True)
    return editions


def _degrees(value: str) -> str:
    text = f"{float(value):.7f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def build(csv_text: str, editions: Mapping[str, Sequence[Edition]]) -> Built:
    """The index's quads from the CSV rows and the bucket's editions."""
    quads: list[Quad] = []
    rows = current = older = missing = 0
    for row in csv.DictReader(io.StringIO(csv_text)):
        rows += 1
        match = _PRODUCT.fullmatch(row["original_product"])
        if match is None:
            raise GeneratorError(
                f"CSV row {rows}: {row['original_product']!r} is not <stem>_<date>_TM_geo.pdf"
            )
        stem, date = match.groups()
        found = editions.get(stem, ())
        if not found:
            missing += 1
            continue
        exact = [e for e in found if e.date == date]
        edition = exact[0] if exact else found[0]
        if exact:
            current += 1
        else:
            older += 1
        south, west = _degrees(row["southbc"]), _degrees(row["westbc"])
        north, east = _degrees(row["northbc"]), _degrees(row["eastbc"])
        line = f"{south} {west} {north} {east} {edition.size} {edition.etag} {edition.path}"
        try:
            quads.append(parse_row(line, rows))
        except UstopoError as exc:
            raise GeneratorError(f"CSV row {rows} ({stem}): {exc}") from exc
    quads.sort(key=lambda q: q.path)
    return Built(tuple(quads), rows, current, older, missing)


def render(built: Built, updated: str) -> str:
    body = "".join(f"{render_row(q)}\n" for q in built.quads)
    return (
        HEADER.format(
            mark=GENERATED_MARK,
            prefix=PREFIX,
            suffix=SUFFIX,
            updated=updated,
            rows=built.rows,
            total=len(built.quads),
            current=built.current,
            older=built.older,
            missing=built.missing,
        )
        + body
    )


def read_zip(data: bytes) -> tuple[str, str]:
    """(CSV text, last-updated date) from ``ustopo_current.zip``'s bytes."""
    try:
        with zipfile.ZipFile(io.BytesIO(data)) as archive:
            text = archive.read("ustopo_current.csv").decode("utf-8")
            summary = archive.read("ustopo_current.txt").decode("utf-8")
    except (zipfile.BadZipFile, KeyError, UnicodeDecodeError) as exc:
        raise GeneratorError(f"ustopo_current.zip could not be read: {exc}") from exc
    match = re.search(r"Last Updated\s*\|\s*(\d{4}-\d{2}-\d{2})", summary)
    if match is None:
        raise GeneratorError("ustopo_current.txt has no `Last Updated` date")
    return text, match.group(1)


def check_shape(text: str) -> Built:
    """The carried file, parsed and checked against its own header."""
    if GENERATED_MARK not in text:
        raise GeneratorError(f"{INDEX} lacks the line saying it is generated")
    counts = _COUNTS.search(text)
    if counts is None:
        raise GeneratorError(f"{INDEX} has no `# quads:` header line")
    total, current, older, missing = (int(g) for g in counts.groups())
    try:
        quads = parse_index(text).quads
    except UstopoError as exc:
        raise GeneratorError(f"{INDEX}: {exc}") from exc
    paths = [q.path for q in quads]
    if paths != sorted(paths):
        raise GeneratorError(f"{INDEX}: the rows are not sorted by path; regenerate it")
    if total != len(quads) or current + older != total:
        raise GeneratorError(
            f"{INDEX}: the header counts {total} quads ({current} current, {older} older) "
            f"and the file has {len(quads)}; it was edited by hand. Regenerate it"
        )
    return Built(tuple(quads), 0, current, older, missing)


def check_online(quads: Sequence[Quad], editions: Mapping[str, Sequence[Edition]]) -> list[str]:
    """What breaks an install: a carried key that is gone, or whose size or ETag changed."""
    live = {e.path: e for found in editions.values() for e in found}
    problems: list[str] = []
    for quad in quads:
        edition = live.get(quad.path)
        if edition is None:
            problems.append(f"{quad.path}: no longer in the bucket")
        elif (edition.size, edition.etag) != (quad.size, quad.etag):
            problems.append(
                f"{quad.path}: the bucket has {edition.size} bytes, ETag {edition.etag}; "
                f"the index has {quad.size}, {quad.etag}"
            )
    return problems


def newer_editions(quads: Sequence[Quad], editions: Mapping[str, Sequence[Edition]]) -> int:
    count = 0
    for quad in quads:
        stem = quad.name.rsplit("_", 1)[0]
        found = editions.get(stem, ())
        if found and found[0].date > quad.edition:
            count += 1
    return count


# ---------------------------------------------------------------------------
# The network: the zip and the listing, from the bucket only.
# ---------------------------------------------------------------------------


def _opener() -> urllib.request.OpenerDirector:
    """HTTP(S) only, no redirect handler: the bucket answers directly."""
    opener = urllib.request.OpenerDirector()
    opener.add_handler(urllib.request.HTTPHandler())
    opener.add_handler(urllib.request.HTTPSHandler())
    return opener


def _get(url: str) -> bytes:
    if not url.startswith(BUCKET + "/"):
        raise GeneratorError(f"refusing {url!r}: only {BUCKET} is asked")
    request = urllib.request.Request(url, headers={"User-Agent": "hammunition"})
    try:
        response = _opener().open(request, timeout=TIMEOUT)
    except (urllib.error.URLError, OSError) as exc:
        raise GeneratorError(f"{url} could not be reached: {exc}") from exc
    if response is None:  # pragma: no cover - no handler claimed the scheme
        raise GeneratorError(f"no handler would ask {url!r}")
    with response:
        if response.status != 200:
            raise GeneratorError(f"{url} answered HTTP {response.status}")
        body: bytes = response.read()
        return body


def list_bucket(get: Callable[[str], bytes] = _get) -> Iterator[tuple[str, int, str]]:
    """(key, size, etag) of every object under the GeoTIFF prefix."""
    token: str | None = None
    while True:
        query = {"list-type": "2", "prefix": PREFIX}
        if token:
            query["continuation-token"] = token
        # The bucket's own XML: expat resolves no external entity, and the
        # response is from BUCKET alone (``_get`` refuses anything else).
        root = ET.fromstring(get(f"{BUCKET}/?{urllib.parse.urlencode(query)}"))
        for item in root.findall(f"{S3}Contents"):
            key, size, etag = (item.find(f"{S3}{name}") for name in ("Key", "Size", "ETag"))
            if key is None or size is None or etag is None:
                raise GeneratorError("a listing entry lacks its Key, Size or ETag")
            yield key.text or "", int(size.text or "0"), etag.text or ""
        truncated = root.find(f"{S3}IsTruncated")
        if truncated is None or truncated.text != "true":
            return
        following = root.find(f"{S3}NextContinuationToken")
        if following is None or not following.text:
            raise GeneratorError("a truncated listing page has no continuation token")
        token = following.text


def read_listing(path: Path) -> list[tuple[str, int, str]]:
    """A listing saved by ``--save-listing``: ``key<TAB>size<TAB>etag`` lines."""
    entries: list[tuple[str, int, str]] = []
    for number, line in enumerate(path.read_text().splitlines(), 1):
        parts = line.split("\t")
        if len(parts) != 3 or not parts[1].isdigit():
            raise GeneratorError(f"{path}: line {number} is not key, size, etag")
        entries.append((parts[0], int(parts[1]), parts[2]))
    return entries


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--fetch", action="store_true", help="regenerate the index")
    mode.add_argument("--check", action="store_true", help="check the carried index")
    mode.add_argument("--save-listing", type=Path, metavar="FILE", help="save a bucket listing")
    parser.add_argument("--offline", action="store_true", help="with --check: shape only")
    parser.add_argument("--zip", type=Path, help="with --fetch: a saved ustopo_current.zip")
    parser.add_argument("--listing", type=Path, help="with --fetch: a saved listing")
    args = parser.parse_args(argv)
    try:
        if args.save_listing:
            entries = list(list_bucket())
            args.save_listing.write_text(
                "".join(f"{key}\t{size}\t{etag}\n" for key, size, etag in entries)
            )
            print(f"saved {len(entries)} objects to {args.save_listing}")
            return 0
        if args.fetch:
            data = args.zip.read_bytes() if args.zip else _get(ZIP_URL)
            csv_text, updated = read_zip(data)
            entries = read_listing(args.listing) if args.listing else list(list_bucket())
            built = build(csv_text, parse_listing(entries))
            INDEX.write_text(render(built, updated))
            print(
                f"wrote {INDEX.relative_to(REPO_ROOT)}: {len(built.quads)} quads "
                f"({built.current} current, {built.older} older GeoTIFF edition), "
                f"{built.missing} left out"
            )
            return 0
        carried = check_shape(INDEX.read_text())
        print(f"{INDEX.relative_to(REPO_ROOT)} is well formed: {len(carried.quads)} quads")
        if args.offline:
            return 0
        editions = parse_listing(list_bucket())
        problems = check_online(carried.quads, editions)
        newer = newer_editions(carried.quads, editions)
        if newer:
            print(f"{newer} quad(s) have a newer GeoTIFF edition; --fetch picks them up")
        if problems:
            print(f"{len(problems)} carried quad(s) no longer match the bucket:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            print("Regenerate: scripts/gen_ustopo_index.py --fetch", file=sys.stderr)
            return 1
        print("every carried quad is in the bucket with its size and ETag")
        return 0
    except (GeneratorError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
